infrahq/infra

internal/cmd/list.go

Sort `infra list` outputs so it's stable. Without sorting, the ordering may change significantly between runs which will unexpected for the user

improve: sort infra list outputs

---

internal/cmd/grants.go
internal/cmd/list.go

Move `subjectNameFromGrants` to `cmd/grants.go` since that's the only place it's being used.

maintain: move subjectNameFromGrants to cmd/grants.go

---

internal/cmd/config.go
internal/cmd/info.go

Add `omitempty` to `cmd/config.go:ProviderID` so if the provider ID is not set, it will not be part of the config. Add a check in info to not call out to the providers API if provider ID is not set.
Resolves #

fix: info errors when invoked on an access key session

---

.github/pull_request_template.md

We use branch protection rules now, so github will tell us if actions are not run.
We also lint the commit message in CI, so our CI checks the commit conforms to our rules.

maintain: remove a couple items from PR checklist

---

docs/getting-started/introduction.md
docs/reference/cli-reference.md
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/kubernetes.go

`infra use` should allow referencing by name, i.e. without the `kubernetes.` prefix
Resolves #1552

fix: allow use by name alone

---

internal/access/access_test.go
internal/access/destination.go
internal/access/provider.go
internal/server/handlers.go
internal/server/models/grant.go

Instead of a user role that we grant to all identities, we can allow authenticated requests to list and get destinations.
This is effectively the same behaviour, without showing the extra grant in the list of grants.
Resolves #1585
* Do we need a migration for this to remove any existing grants for "infra user role" ?

Remove the infra user role

---

api/identity.go
docs/api/openapi3.json
internal/server/openapi.go

- generate an enum for one-of tags in open api spec
- refactor some duplicated tag reading code
- add "one of" to identity api struct
- fix /v1/identites in the right category
API structs that are validated to be "one of" set values should be enums in the OpenAPI spec.
Resolves #1496

docs: OpenAPI enum for oneof (#1496)

---

internal/server/debug.go
internal/server/debug_test.go
internal/server/routes.go

I found this `http.StripPrefix` which makes it easy to move the pprof handlers to `/v1`. This is probably good because any paths that start with a different prefix are assumed to be paths for serving the UI.
Would be a breaking change if anyone was using these, but I don't think anyone has a use for them yet.

improve(api): move /debug/pprof to /v1/debug/pprof

---

internal/server/routes.go

Server is not currently logging incoming requests. This was due to the logging middleware being (accidentally?) removed. 
Replacing the `IdentityAwareLoggingMiddleware` which doesn't work in the current state. It requires `identity` to exist in the context but `identity` is not set until much later in the `AuthenticationMiddleware`
Resolves #

fix: not logging api calls

---

docs/install/configure/secrets.md
helm/charts/infra/values.yaml
internal/cmd/cmd.go
internal/cmd/server.go
internal/cmd/server_test.go
internal/decode/decode.go
internal/server/config.go
internal/server/config_test.go
internal/server/server.go
internal/server/server_test.go
secrets/awssecretsmanager.go
secrets/awsssm.go
secrets/file.go
secrets/kubernetes.go
secrets/vault.go

Initially I thought the problem was simply the structure (a missing `config:` field), so the first few commits fix that problem and the docs. Then I realized it was the `UnmarshalYAML` methods, so I started converting those.
This PR changes the UnmarshalYAML hook to one that mapstructure understands.
Related to #1519 (but keys need the same fix, which I will do in a follow up PR)

Fix loading of secret providers from config file

---

internal/cmd/server_test.go
internal/server/config.go
internal/server/config_test.go
internal/server/server.go
internal/server/server_test.go
secrets/aws.go
secrets/awskms.go

Branched from #1520, so that will have to merge first.
Similar to #1520, this PR fixes loading of key providers from config. When we switched from yaml config to using viper and mapstructure the custom unmarshal method no longer worked.
Resolves #https://github.com/infrahq/infra/issues/1519

Fix loading of key providers from config

---

internal/logging/logger.go
internal/server/errors.go

Removes the IdentityAwareMiddleware as it did not work, and because we
can do this with a single middleware. It did not work for a few reasons.
It attempted to read an identity from the context before it existed, and
because the identity in the context is a model.Identity, not just an ID.
This new approach works because we read the identity out after the
request handler runs.
Tested manually and saw authenticated requests with an identity field,
and unauthenticated requests without.

improve: log identity name for logged in API request

---

internal/cmd/providers.go
internal/cmd/providers_test.go

Field tags for providers options was incorrect so the values wasn't being set correctly. Add a test to check for this
Resolves #1612

fix: infra providers add set client ID/secret

---

internal/server/data/migrations.go

Move re-indexing identity names to after they are de-duplicated in migration.
Resolves #1570

fix: re-index identities after de-duplication

---

docs/getting-started/key-concepts.md

Moved the architecture diagram to the top of the page and annotated the associated text to it numerically.

Fix: Moved architecture diagram

---

api/types.go
api/types_test.go

Previously it worked for pointers, but not values, because of the method receiver on MarshalJSON being a pointer.
I tried to call `time.Time.MarshalJSON`, but that uses the format `RFC3339Nano` , not `RFC3339`, so it's not exactly what we want.
Resolves #1614

fix(api): fix marshaling of api.Time values

---

internal/server/routes.go
internal/server/server.go
internal/server/server_test.go

(Best viewed by individual commit because it required moving a function to a different file).
We've had a couple regressions with the API middleware either applying to the wrong routes (ui routes), or not being applied to routes (missing logging on API routes). Even when we notice the problem it has been a challenge to fix it properly (requiring lots of back-and-forth or pairing).
I think there are a few constraints that make this challenging:
1. Our UI routes are applied as catch-all middleware with no path prefix. This makes it really easily to accidentally add a middleware to those routes without noticing.
2. The interface gin providers for constructing these routes is overly flexible and not well documented (I had to read the source to understand how/when middleware would be applied …

api: more robust structure for building routes

---

internal/cmd/about.go
internal/cmd/cmd.go
internal/cmd/server.go
internal/cmd/server_test.go
internal/cmd/types/url.go
internal/decode/decode.go
internal/openapigen/main.go
internal/server/config_test.go
internal/server/debug_test.go
internal/server/handlers_test.go
internal/server/openapi_test.go
internal/server/routes.go
internal/server/server.go
internal/server/server_test.go

Branched from #1611, so that will need to merge first
This PR does a bit of cleanup from previous changes. I had to introduce an error return value to a few methods that shouldn't need error returns.
To remove the error return I introduced a type for `url.Url` that can be decoded from command line flag or config file. This allows us to handle the parse error earlier. Handling it earlier should also be better for users, as it keeps our errors consistent, and would allow us to implement a validate config command later.

improve: remove error return from registerUIRoutes

---

docs/reference/cli-reference.md
internal/cmd/keys.go
internal/cmd/keys_test.go

I started by changing the fields from string to `time.Duration` to avoid the need to `ParseDuration`. Then I wrote a test for the command. The test was failing because `--extension-deadline` was not being passed to the API. I'm not sure why, the struct field tags look right. I don't think it was the change to the field types, because the `ttl` field was working and it had the same type.
I changed the command to use `DurationVar`, which got the test to pass.
This change removes support for setting these fields from environment variables, but that should be an easy thing to restore. I am working on a proposal for how we can do that with a single function, without the need for viper.
Since this is a CLI command that we expect humans to run, I guess no one is trying to use it with environment …

fix(cli): fix the extension-deadline flag

---

.github/workflows/human_pull_request.yml
.github/workflows/release_pull_request.yml

`on.pull_request.branches` refers to the base ref of the pull request, e.g. `main`, so the filter cannot be used to filter jobs based on the head ref, e.g. `release-please--branches--main`.

fix(ci): actions not running correctly

---

internal/access/access.go
internal/access/access_key.go
internal/access/credential.go
internal/access/grant.go
internal/access/group.go
internal/access/identity.go
internal/access/provider.go
internal/access/token.go
internal/logging/logger.go
internal/server/handlers.go
internal/server/handlers_test.go
internal/server/server_test.go
internal/server/telemetry.go

This PR contains 2 refactor commits. I was making these changes while writing a test for the `CreateGrant` API endpoint, and I thought I would PR them first to keep them separate from the test.
1. I was about to write a third copy of `CurrentIdentity` when I realized I had missed the existing one. I renamed `CurrentIdentity` to `AuthenticatedIdentity` with the hope that "authenticated identity" clarifies that this is getting the identity from the request. `AuthenticatedRequestIdentity` could also work, but is maybe a bit long. Also added some godoc to it.
2. refactor `setupServer` (our test helper for setting up a server for API tests) to accept functions to customize the options. I think we'll want to work on consolidating `setupServer` with `server.New` as much as possible. For now this …

Rename CurrentIdentity to AuthenticatedIdentity

---

internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/handlers_test.go

While working on something else I thought I had found a bug in list identities. I wrote a test for the API endpoint, and then realized the problem was I had typed the identity name wrong.
This commit:
* orders identities by name ascending
* adds a test for `ListIdentities` API endpoint
* improves the tests for `data.ListIdentities` by asserting an order
Related to #1606, but only for list identities.

api: sort list identities by name

---

api/client.go
api/setup.go
api/signup.go
docs/api/openapi3.json
docs/getting-started/quickstart.md
internal/access/credential.go
internal/access/credential_test.go
internal/access/signup.go
internal/access/signup_test.go
internal/cmd/identities.go
internal/cmd/identities_test.go
internal/cmd/login.go
internal/cmd/server.go
internal/cmd/server_test.go
internal/server/data/migrations.go
internal/server/data/settings.go
internal/server/handlers.go
internal/server/models/settings.go
internal/server/routes.go
internal/server/server.go
internal/server/server_test.go

Rework the `setup` workflow to instead run a `sign-up` workflow. Sign-up will allow the first user to immediate create an admin user without running subsequent infra commands.
* Consolidate prompt validation with `survey.Validator`s
* Revert prompt formatting since it does not look very good
Resolves #1518

feat: create admin user on first login

---

api/client.go
api/client_test.go
internal/cmd/cmd.go

This commit adds support to `api.Client` for setting headers.
The CLI uses this support to add a more descriptive user agent header, which should look something like this:
Infra CLI/0.10.3 (darwin/arm64)
Infra CLI/0.10.3 (linux/amd64)
This will allow us to identify traffic from different sources.

improve(cli): add user agent to requests

---

internal/server/handlers_test.go
internal/server/models/model.go

This PR adds a test for `CreateGrant` (`POST /v1/grants`). I believe this is the first API test that is strict about the API response body, so it includes some new helper functions. We don't necessarily need to write every API test in this way, but I think we should have at least one test for each API endpoint that makes assertions about the body of the response. 
There are other ways of testing APIs. We could decode the response into the `api` type. The problem with that approach is that we will mask regressions in the API. If we change the `api` type, the test doesn't fail! It is easy to unintentionally change API responses, and tests like this help prevent API regressions.  It does mean that when we add fields we will have to update these tests. That's probably a good reason to have a …

Add a test for CreateGrant API endpoint

---

internal/server/server.go
internal/server/server_test.go
internal/server/static_fs.go
internal/server/static_fs_test.go

Fixes:
* ui routes falling through to the NotFound handler in development
* Embedded FS not detecting `.html` files exist – (e.g. when the user loads `/a/path` it should check if `/a/path.html` exists as well as `/a/path`

fix: fix 404 and proxy ui routes

---

api/signup.go
docs/api/openapi3.json
internal/cmd/login.go
internal/server/handlers.go

Changes `POST /v1/signup` to use `email` as a field)
Resolves #

feat: change signup request endpoint to use email

---

internal/cmd/cmd_test.go
internal/cmd/identities_test.go
internal/cmd/keys_test.go
internal/cmd/providers_test.go

Most CLI commands require a login first. In tests we simulate a login by writing out a `ClientConfig`. This PR extracts a test helper for building that `ClientConfig`, so that if we change the format of the config it'll be less work to migrate the tests.

improve: add a test helper for creating a ClientConfig

---

.github/workflows/pull_request.yml
docs/reference/cli-reference.md
internal/cmd/cliopts/flags.go
internal/cmd/cliopts/flags_test.go
internal/cmd/cmd.go
internal/cmd/destinations.go
internal/cmd/grants.go
internal/cmd/identities.go
internal/cmd/identities_test.go
internal/cmd/info.go
internal/cmd/keys.go
internal/cmd/list.go
internal/cmd/login.go
internal/cmd/providers.go
internal/cmd/tokens.go

(best viewed by individual commit, more details in the commit messages)
This PR adds a new `cliopts.DefaultsFromEnv` for loading default values for flags from environment variables. The new function is used in two commands for now: `infra login`, and `infra identities edit`. This should be enough to demonstrate the pattern. I'll add it to other places once everyone is happy with this approach.
Also fixes a bug related to `cobra.Command.PersistentPreRunE` in a parent command clobbering the one from the root command. Fixing that bug was necessary to write tests for this, because `DefaultsFromEnv` is called from `PersistentPreRunE`.
Adds another test case for `infra id edit`, but nothing for `infra login` yet.

cli: use DefaultsFromEnv - part 1

---

internal/cmd/grants.go
internal/cmd/grants_test.go
internal/cmd/identities.go
internal/cmd/keys.go
internal/cmd/keys_test.go
internal/cmd/providers.go
internal/cmd/providers_test.go
uid/snowflake.go

Branched from #1655, and includes a commit with #1667, so those two will probably need to merge first
Converts the remaining "interactive" (short lived) CLI commands to remove the calls to `parseOptions`. The only two calls that are left are for the "long running" commands (`server` and `connector`) which will need a different approach.
Also adds some tests for the commands that changes, to show the options are passed to the API correctly.

cli: use DefaultsFromEnv - part 2

---

internal/cmd/about.go
internal/cmd/args.go
internal/cmd/cmd.go
internal/cmd/destinations.go
internal/cmd/grants.go
internal/cmd/identities.go
internal/cmd/info.go
internal/cmd/keys.go
internal/cmd/list.go
internal/cmd/providers.go
internal/cmd/server.go
internal/cmd/tokens.go
internal/cmd/version.go

So that if a user accidentally runs a command with positional
arguments, they get feedback about it. Without this, commands can be
misleading because they would print unexpected output when the user
forgets to add a flag.
Builds on #1674

cli: add 'no args' validator to commands

---

internal/server/handlers.go
internal/server/handlers_test.go

There was a bug in identity creation through the CLI that would set a one time password on machine identities by default. Fixing this behavior to not set a one time password on machine identity creation.
Resolves #1622

fix: do not set a otp on machine identities

---

internal/access/grant.go
internal/access/signup.go
internal/server/config.go
internal/server/data/grant.go

Show all grants when listing grants. This was fixed on the CLI side in #1533.
I kept the filter for `DeleteGrants` for now. I wanted to handle it explicitly with a more specific error, but that would break `infra grant delete` because it iterates over all grants. I think we should revisit that separately, it works well for now.
I tested it manually and saw this:
```
$ infra grant list
IDENTITY   ACCESS     DESTINATION  
admin      admin      infra        
connector  connector  infra        
```
To automate a test for this we need more of an integration test (with both CLI and a real API) and some way to capture the stdout of the CLI. We don't have a pattern for that yet, but it's something I'm going to look at adding soon.
Resolves #1669

improve: remove NotCreatedBy system filter for grants list

---

internal/cmd/cmd_test.go
internal/cmd/keys_test.go

I was wondering why my `~/.infra/config` always had unexpected servers in it. It turns out it was because I forgot to call `t.SetEnv()` in one test case.
This PR fixes the test where I missed it, and adds a safeguard to `TestMain`. With this safeguard, any test that tries to write to a file in `HOME`, or `KUBECONFIG` will fail with a helpful error message.
I tested this on linux, and darwin, hopefully it works the same way on windows.

Add safeguard for CLI tests

---

internal/connector/connector.go
internal/kubernetes/kubernetes.go

- separate checksum lookup and autoname functions
If the name is provided for the kubernetes connector we don't need to do the name look-up. Separate the function so that we can skip this and still get the checksum.
Resolves #1308

fix: do not look up k8s name when provided

---

internal/cmd/cli.go
internal/cmd/cli_test.go
internal/cmd/cmd.go
internal/cmd/destinations.go
internal/cmd/grants.go
internal/cmd/identities.go
internal/cmd/keys.go
internal/cmd/keys_test.go
internal/cmd/list.go
internal/cmd/providers.go
internal/cmd/testdata/TestKeysListCmd/filter_by_machine_name
internal/cmd/testdata/TestKeysListCmd/list_all
internal/docgen/main.go

One of the primary responsibilities of the CLI is to output things in a format that is easy for humans to consume. We should have some test coverage of that output, to prevent regressions. When we intentionally make change to the output it also gives us an easy way to preview the changes by looking at the tests.
This PR implements an approach that I've used previously to test CLI output.
1. the first commit adds a `CLI` type for passing around input and output streams. I think it's likely we'll add more fields to this type in the future. The `api.Client` could be one of the fields, common CLI flags that may be used in multiple commands is another one.
2. the second commit adds a test for `infra keys list` that uses the support added in 1
This PR uses [golden …

cli: support testing the stdout produced by CLI commands

---

internal/logging/logger.go

Only use color when stdin is a terminal. Tested with
```
./infra id list < /dev/null
```
Resolves #1719

fix: only use color logging with a terminal

---

ui/components/grant.js
ui/components/input.js

The dropdown reset back to `view` as the default after sharing with a user
Resolves #1683 
https://user-images.githubusercontent.com/63033505/165282730-cb85441c-3d05-4e1e-bbbd-1534e165a7fa.mov

fix: grant input dropdown reset after sharing with a user

---

internal/access/access_test.go
internal/access/identity.go
internal/access/provider.go
internal/cmd/login.go
internal/server/authn/oidc.go
internal/server/handlers.go

- set auth URL from provider well known endpoint
- make user info endpoint dynamic
OIDC Provider clients make some assumptions about the endpoints they should be connecting based on the Okta endpoints. We can prepare for general OIDC by automatically finding these endpoints at the `.well-known/openid-configuration` endpoint that OIDC providers publicly expose.
This change does not have any impact on the current user experience or backwards compatibility.
Resolves #1703

improve: generalize oidc client config

---

ui/lib/admin.js
ui/pages/settings/admin.js

1. hide revoke button for self in the admins page
2. disable add button when there is no input
Resolves #1685

fix: hide `revoke` button for self in settings > admins

---

ui/components/modals/delete.js

- remove the `Transition.Child` when open and close the delete dialog to prevent modal persisting and showing the incorrect data after deletion 
Resolves #1684

fix: remove transition animation

---

internal/cmd/cli.go
internal/cmd/cmd.go
internal/cmd/destinations.go
internal/cmd/grants.go
internal/cmd/identities.go
internal/cmd/info.go
internal/cmd/keys.go
internal/cmd/list.go
internal/cmd/login.go
internal/cmd/logout.go
internal/cmd/providers.go
internal/cmd/tokens.go
internal/cmd/version.go

Follow up to #1708
This PR removes the `TODO` type, and uses the new `CLI.Stdout` and `CLI.Stderr` in most places. There are a few more calls to `fmt.Printf` which will require a bit more work to change. We can probably address those when we write tests that require it. I'm hoping this passes the `CLI` struct to enough places to make it easy to use for new commands or new output.

Use CLI.Stdout more consistently

---

go.mod
go.sum
uid/snowflake.go
uid/snowflake_test.go

While working on a change to our API, I ran into some unexpected behaviour. I traced it to [this bug fix](https://github.com/bwmarrin/snowflake/commit/7511dd2b95883fdcd3fd35494451124fdc9b06cb), which we don't have yet because there has not been a release of this project for 3 years.
This PR adds some more tests, and updates the dependency.

Update snowflake dependency and add more tests

---

ui/components/input.js
ui/components/modals/fullscreen.js
ui/pages/destinations/add.js
ui/tailwind.config.js

- modified tailwind config file to add some custom colour 
- fixed varies cluster add page ui bugs
Resolves #1733

fix: cluster add page ui bugs

---

.github/workflows/pull_request.yml

Removes the -short flag from CI, so that all tests are run. Previously we were using it to skip tests that required docker containers and kubernetes.
Also update the version of gotestsum, which should use color by default.

maintain: run all tests in CI

---

internal/server/handlers_test.go
internal/server/server_test.go

Extracted out of #1740, since that PR needs more work

api: more tests for CreateIdentity and DeleteProvider

---

go.mod
go.sum
internal/cmd/cliopts/config.go
internal/cmd/cliopts/config_test.go
internal/cmd/cliopts/flat.go
internal/cmd/cliopts/hooks.go
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/server.go
internal/cmd/server_test.go
internal/server/config.go
internal/server/config_test.go

Original PR #1682
The last 2 commits here address the problem with flag default values overwriting settings from config.  Full details about the two options and trade-offs in the last commit message, copied here:
For long-running commands (infra server, and infra connector) all
options can be set from the config file, and most can be set from env vars,
but only a few will be set from command line flags.
Command line flags accept default values, but anything that uses
cliopts.Load can set defaults on the struct before calling Load.
Because of these two constraints, we end up with two options:
1. have cliopts honor the default values set in flags, allowing defaults
to be specified in two different ways.
2. only allow defaults to be set on the struct before calling
cliopts.Load.
This commit …

Replace viper with cliopts.Load (take 2)

---

api/client.go
api/client_test.go
internal/access/access_test.go
internal/server/authn/errors.go
internal/server/authn/oidc.go
internal/server/authn/oidc_test.go
internal/server/errors.go
internal/server/handlers.go

- check provider url and client are valid
- return better error message for a secret that does not exist
When an identity provider is added to Infra through the API or CLI check that the URL, client ID and client secret are valid. This relies on some information being present in the response from the identity provider. We will probably iterate on this as more identity providers are supported.
Example outputs:
```
$ infra providers add okta --url invalid-example.okta.com --client-id ${CLIENT_ID} --client-secret ${CLIENT_SECRET}
ERROR  POST "/v1/providers" responded 400: bad request: invalid provider url
$ infra providers add okta --url example.okta.com --client-id ${INVALID_CLIENT_ID} --client-secret ${CLIENT_SECRET}
ERROR  POST "/v1/providers" responded 400: bad request: invalid client id …
```

improve: validate provider fields

---

internal/server/server_test.go

The metrics server subtest was looking for the `http_request_duration_seconds` metric which only exists after an API request is performed. This was relying on other tests having run first.
This commit fixes the problem adding a call to `/v1/version` to make sure at least one API request was handled.

maintain: fix a potentially flaky test

---

api/access_key.go
docs/api/openapi3.json
docs/reference/cli-reference.md
internal/access/access_key.go
internal/cmd/keys.go
internal/cmd/keys_test.go
internal/server/config.go
internal/server/data/data.go
internal/server/data/identity.go
internal/server/data/provider.go
internal/server/handlers_test.go
internal/server/server_test.go

Move name positional parameter to a keyword parameter for infra keys add. If name is not specified, generate one based on the identity issuing the key and the current timestamp
Move `infraProviderCache` and `infraConnectorIdentityCache` to `data/data.go` and a way to reset the cache value. This is mainly used for tests as the database gets recreated frequently which causes the cache to point to a nonexistent object
Resolves #1479

feat(cmd): optional access key name

---

internal/access/signup.go
internal/server/server_test.go

anything labelled "created by system" is pruned on startup by config
loading. since the admin user/grant is not part of the config, it will
be pruned.
Resolves #1788

fix: do not label signup user grant as created by system

---

internal/cmd/identities.go
internal/cmd/logout.go

Update CLI outputs:
- Add a new line to logout confirmation
- Remove extra newline from `Debugf`
- Add a confirmation message when removing identities

maintain: cosmetic changes to CLI outputs

---

internal/access/grant.go
internal/server/handlers.go
internal/server/handlers_test.go

Block users from removing the last infra admin from the system. Admins have the permissions to remove other admins but this can lead to a situation where no admins remain making it more the service more difficult to manage.
Resolves #1744

fix: stop user from removing the last admin

---

internal/cmd/error.go
internal/cmd/error_test.go

Introduce cli errors. These will be used for outputting user facing messages in a consistent format, where as the original errors (`OriginalError`) should be used for debugging. 
See a draft of how this is to be used: #1760
Related #1394

feat: introduce cli errors

---

internal/access/signup.go
internal/access/signup_test.go

When connector is enabled in the same helm install as server, it will
create an identity and access key to allow the connector to communicate
with the server. This identity is created with "connector" which is
filtered out in the signup check leading to signup to be enabled.
Resolves #

fix: add additional signup check

---

internal/server/config.go
internal/server/errors_test.go
internal/server/handlers_test.go

A little more clean-up around the identity kind consolidation. Restoring an error test, removing a redundant test and updating a comment.
Restoring
Resolves #1657

maintain: restore required email error test

---

api/client.go
api/client_test.go
api/errors.go
internal/cmd/login.go
internal/cmd/logout.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/handlers.go

This PR attempts to address two problems:
1. Right now the `api.Client` doesn't expose enough detail about the request error. The caller of an `api.Client` method should be able to access all of the structured fields in the response body, so it can format a message appropriately. `api.Client` should also expose the underlying error code in some way, so that the caller can make a choice based on the error code.
2. Both the `internal` package and the `api` package had a set of error variables that are very similar. This makes it easy to use the wrong variable. This PR fixes one instance where an `api.ErrBadRequest` was used in place of `internal.ErrBadRequest`, which would result in a 500 status code, instead of a 400 status code. The `api` error variables are removed, and replaced with …

api: improve errors returned by api.Client

---

ui/components/input.js
ui/pages/destinations/add.js

- the input was having spelling check, and it is being removed
- the input width was always 100% but it is 85% if it is dropdown input
Resolves #1776

fix: share modal input bugs

---

docs/reference/cli-reference.md
internal/cmd/cmd.go
internal/cmd/info.go
internal/cmd/version.go

Add info and version into `other commands`. 
Remove flag versions of info and version. 
Resolves #1861

feat: move info and version from flags to other commands

---

internal/cmd/cmd_test.go
internal/cmd/kubernetes.go
internal/cmd/list.go

Changes AuthInfo inside of kube to use the infra email name for a user
Resolves #1851

feat: use email name for authinfo inside of kube

---

internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go

This PR adds a test that shows that `gorm.DB` methods always (at least for the cases I've tested), return a pointer to a copy of the `gorm.DB`. The logic for that is in [db.getInstance](https://github.com/go-gorm/gorm/blob/9b80fe9e96e6d9132f935a944a150777a3ffdf03/gorm.go#L362-L385), which seems to be called from most `gorm.DB` methods.
This PR also removes the `db2` variables. Those variables aren't necessary because the gorm methods return copies, and since the type is a pointer, the extra variable would not help if they did not return copies. Both variables would point at the same value.  Creating a copy using assignment only works for non-pointer values. You'd have to deference the pointer to make a copy (but that's not how gorm.DB is expected to be used). …

data: add a test to demonstrate gorm.DB clone behaviour

---

internal/server/debug.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/middleware.go
internal/server/routes.go
internal/server/telemetry.go

Following up on #1874
I noticed that now `sendAPIError` doesn't need to be a method anymore (it doesn't use `API`).
Also noticed the `Telemetry.Group` method was not being used. Should it be, or is it safe to remove for now?

api: remove unused method receiver and unused method

---

internal/access/access_test.go
internal/server/data/group.go
internal/server/data/group_test.go

While working on `ListGroups` I came across `data.BindGroupIdentities` which was only used in tests. I suspect this function was replaced by `data.AssignIdentityToGroups` at some point.
This PR removes `data.BindGroupIdentities` and the tests for it. The one test of other functionality that used this function was changed to use `data.AssignIdentityToGroups` to better mirror production code paths.

maintain: remove unused BindGroupIdentities

---

api/client.go
internal/access/grant.go
internal/cmd/cmd_test.go
internal/cmd/kubernetes.go
internal/cmd/list.go
internal/server/data/grant.go
internal/server/grants_test.go
internal/server/handlers.go
internal/server/handlers_test.go
internal/server/routes.go

Removes `ListIdentityGrants` and `ListGroupGrants` and moves those special authorization rules to `ListGrants`.
This PR keeps the old deprecated routes for now (as aliases of `ListGrants`), but maybe we should remove them.
Most of the change is the addition of API tests, best viewed by individual commit.
Related to #1680, but maybe the group endpoint should be changed in the same way before we close that issue.
TODO:

api: remove extra grant endpoints

---

go.mod
internal/cmd/about.go
internal/cmd/keys.go
internal/cmd/local_server.go
internal/connector/connector_test.go
internal/server/data/token.go

The lint runner is running the new golint version (1.6.0) and it is detecting some new warnings. This PR cleans up these problems.

fix: golint 1.6.0 errors

---

internal/connector/connector.go

Fixes an index out of bounds in connector when creating cluster roles
Resolves #1923

fix(connector): index out of bounds for namespace ClusterRole

---

internal/server/data/data.go
internal/server/middleware.go

I noticed about a 3-4x performance improvement from enabling sqlite's WAL, which oddly isn't enabled by default. This enables it.
In the course of testing the old database locked messages, I also noticed we were hiding some db errors which didn't seem correct, so I've fixed that too.

improve: enable Sqlite WAL

---

Makefile
docker-desktop.yaml.in
docs/contributing.md
internal/connector/connector.go
internal/server/server.go

`make dev` makes some assumptions about the code base, one of which is to set infra version. This has side effects since the introduction of API migrations which causes the connector to report its API version incorrectly.
1. Docker image will always tag `dev` docker images when build locally with `make dev`
2. `IMAGE_TAG` is no longer supported to change the docker image tag
3. The version is injected into the Docker image at build time with contents of `git describe --tag --abbrev=0`
4. Server and connector on start up with report their full version

fix: make dev using wrong version

---

docs/reference/cli-reference.md
internal/cmd/errors.go
internal/cmd/identities.go
internal/cmd/identities_test.go
internal/cmd/login.go

If password confirm does not match the first one, right now it prompts only the second one. 
This change remprompts both: 
**Old:**
```
Password: abc
Confirm password: abcd
Passwords do not match. 
Confirm password: abcd
```
**Now:**
```
Password: abc
Confirm password: abcd
Passwords do not match. Please try again.
Password: ...
Confirm password: ...
```
**Reason**
During admin signup, if user mistypes first password, they have no clear way to fix it. 
**Additional small changes**
- merges `promptUpdatePassword` and `promptConfirmPassword` because it only included a message `fmt.println`. Moved that msg out to the respective functions that call it, since the message is different each time.

improve: confirm password mismatch returns to first password prompt

---

internal/server/apimigrator.go
internal/server/apimigrator_test.go
internal/server/handlers.go
internal/server/openapi.go
internal/server/routes.go

stacked migrations were interacting oddly with the flush behavior, where flush would flush layers it didn't own. This was code adopted from gin that didn't make sense in this context. added tests and resolved.

fix: resolves issue with stacked response migrations

---

internal/cmd/logout.go
internal/cmd/logout_test.go

If the /logout api call fails for some reason, we should just delete the access key and continue; we don't really care why it failed, and the key will time out anyway.
Resolves #1863

fix: logout should always succeed

---

internal/server/migrations.go

When adding response migrations for grants the grants response was modified to match the response that was currently in main. It should have been migrated for the response in v0.12.2 instead. This fixes that v0.12.2 grants migrations and ensures v0.12.2 connectors work with the new version.
Resolves #1934

fix: migrate grants subject

---

api/client.go
docs/api/openapi3.json
internal/cmd/cmd_test.go
internal/cmd/grants_test.go
internal/cmd/keys_test.go
internal/cmd/logout_test.go
internal/cmd/providers_test.go
internal/cmd/users_test.go
internal/server/debug.go
internal/server/debug_test.go
internal/server/grants_test.go
internal/server/handlers_test.go
internal/server/migrations.go
internal/server/routes.go
internal/server/server_test.go

Replace API path `v1` with `api` since the API is no longer versioned by the path. Depends on #1943
TODO:
Resolves #1828

maintain: replace v1 with api

---

internal/cmd/users.go

Other commands such as `infra providers` also have a singular alias `infra provider`. `infra user` got missed in the migration from `infra id`.
Resolves #1949

fix: add singular alias for users

---

docs/guides/managing-admins.md

The infra `user` role no longer exists. Remove it from the docs.

fix: remove infra user role from docs

---

.github/release-please.json
.github/workflows/release.yml
.github/workflows/release_pull_request.yml
Dockerfile
Makefile
api/client.go
docker-compose.build.yaml
internal/cmd/version.go
internal/server/handlers.go
internal/version.go

- Unset `Prerelease` and `Metadata` fields when building release
- Set `Prerelease` to `rc` and unset `Metadata` when building release candidate
- Unset `Prerelease` and set `Metadata` to `dev` when building local docker image
- Update version string for server to `internal.FullVersion()` and client to `api.GetClientVersion()`
- Update `api.GetVersion()` to `api.GetServerVersion()`
- Split `BUILDVERSION` and `IMAGEVERSION` since they may be different
- Remove codeql-analysis since the value add is minimal at this point in time
Resolves #1952

fix: set correct version for release and release candidate builds

---

api/client.go
internal/cmd/version.go

This reverts part of 3662a6fab75ca77570fb19175dca27e950daf3a9.
The command line should report its binary version. The API version is used to describe the target API version so it's not appropriate to report as the version of the CLI

fix: revert client to report binary version, not api version

---

.github/labels.yaml
.github/workflows/fuzz.yaml

This PR adds a github workflow for running all the fuzz tests. The workflow runs daily (at 3am UTC), and can also be triggered on a PR by adding the `action/fuzz` label (also added in this PR).
The `go test -fuzz` flag can only be used to run a single Fuzz test at a time, so the fuzz workflow does this:
* start by finding all the fuzz tests
* uses the list of fuzz tests to create a `matrix` for the actual fuzz job
* runs a separate job for every fuzz test it finds
* the fuzz corpus should be cached, so each run should resume from where it stopped last time
The fuzzing will run for 30s in the nightly run, but only 5 minutes for the PR runs. We can change those times if we want.

ci: add daily schedule job to run fuzzing

---

.github/workflows/pull_request.yml

If the check is run from the release branch pull request, unset `Metadata` so the version is set correctly

fix: openapi gen should not set -dev version in release branches

---

.github/workflows/pull_request.yml
internal/openapigen/main.go
internal/server/apimigrator_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/handlers.go
internal/server/openapi.go
internal/server/openapi_test.go
internal/server/routes.go

Package-level variables make testing more challenging and can make code harder to reason about. They introduce [side effects](https://en.wikipedia.org/wiki/Side_effect_(computer_science)) that could be avoided.
This commit replaces the boolean to skip generation in tests (which likely makes the tests less like production) and replaces it with an `openapi3.T` document on the `API` struct. The document is now returned from `GenerateRoutes`, which also removes the risk of something referencing the static variable before it is fully populated. 
With this change, it's not a lot more obvious that `GenerateRoutes` is responsible for constructing the document, and it makes it a lot more difficult for tests to make changes to the real production document (because that is only saved explicitly by …

api: replace static openapi document with a field on API

---

.github/workflows/pull_request.yml
Makefile
internal/version.go

- `BUILDVERSION` gets unset since the Makefile sets it to an empty string. Instead remove it as it's set statically in the Dockerfile
- Use `GITHUB_HEAD_REF` instead of `GITHUB_REF_NAME`

fix: build for release candidates

---

.github/workflows/pull_request.yml
internal/server/data/data_test.go
internal/server/data/grant_test.go
internal/server/data/group_test.go

The `data` package is our abstraction for interacting with the database. We should run the tests in this package against all supported database (sqlite and postgres) to make sure that queries work in both scenarios.
This PR setups up CI config and adds supports for running the tests against postgres locally as well. Postgres is required in CI, but optional for local runs.
Tests in the `data` package should receive a db from `runDBTests`, to run against all databases.  I've only added this to a couple tests to demonstrate the pattern. I'll apply it to all the tests once we're happy with the approach.
Since there are plenty of whitespace changes, the diff is best viewed with [hide whitespace](https://github.com/infrahq/infra/pull/1922/files?diff=split&w=1).
TODO:

ci: run data package tests against all supported databases

---

internal/server/config.go
internal/server/config_test.go

Grant role is optional. In the case a grant does not have a role, Infra will grant it `connect` privileges, allowing the user to authenticate with Infra but does not configure any authorization for the destination infrastructure

fix: optional grant role

---

internal/cmd/cmd.go
internal/cmd/config.go
internal/cmd/info.go
internal/cmd/providers.go
internal/cmd/users.go

Update `infra providers` outputs to also print the OIDC URL for additional context. Removing providers should only say "removed" if something was found and removed. If nothing is found, it should not say it's been removed. In the future, not finding a match may error

maintain: update cli outputs

---

Makefile

`BUILDVERSION` was removed in an earlier commit. It's not necessary to set `--version` as it's set statically in `Chart.yaml` and incremented by the release

maintain: remove BUILDVERSION from helm target

---

docs/reference/cli-reference.md
internal/cmd/users.go
internal/cmd/users_test.go

Remove `--non-interactive`. This flag has no value. The only editable field is `password` which is explicitly not supported with `non-interactive`. If/when other editable fields are introduced, `non-interactive` may make a return.
Inform users of an updated password even if it's updating their own password

maintain: update infra users

---

internal/cmd/config.go
internal/cmd/errors.go
internal/cmd/login.go

Login will prompt user to change their password if server requires a new password. This should be set and updated before saving the session to disk. Otherwise the user can interrupt the password update and still end up with a valid session.
Update login errors to not inform users of their previous session. It's not possible to know definitively whether the session is valid from the client alone so to avoid misleading the user, omit this message completely.

fix: update password before saving session configs

---

internal/server/apimigrator.go
internal/server/apimigrator_test.go
internal/server/handlers_test.go
internal/server/routes.go

The general idea is that we build the list of redirect/rewrite middleware backwards from the defined migrations, and this lets us do the right thing when we encounter redirects etc. Redirects now basically fork the path and end up with multiple paths, and all of them get bound to gin. Before there was no way to make each path have its own middleware, but now each is selected so it will exactly have the correct versioning middleware for that particular path/version

improve: refactor api migrator to work nice with redirects

---

internal/claims/claims.go
internal/connector/connector_test.go
internal/server/data/token.go

This nonce claim is not needed and never used, it is from a very early version of Infra. The nonce is useful when preventing replay attacks (ex: an implicit OAuth flow), but not useful on JWTs that will be used repeatedly. 
Resolves #2014

fix: remove unneeded jwt nonce

---

docs/reference/helm-chart.md

Explicitly set service type to ClusterIP when configuring server Ingress. By default, server users service type LoadBalancer. This is unnecessary/undesirable when using Ingress so set it to ClusterIP instead
Resolves #2010

improve(docs): update ingress config examples

---

internal/cmd/kubernetes.go
internal/cmd/logout_test.go

Unset the current kubeconfig context if it's a infra context on logout. Otherwise leave it alone
Resolves #1855

fix: unset CurrentContext on infra logout

---

api/client.go
api/client_test.go
api/errors.go
docs/api/openapi3.json
internal/cmd/cmd.go
internal/cmd/config.go
internal/cmd/login.go

Move HTTP Path and Method to struct fields so they can still be referenced but keep them out of the error message.
Refactor `cmd/config.go`, removing duplication since some functions have been refactored
Resolves #2009

maintain: remove http path, method from api errors

---

internal/server/config.go
internal/server/config_test.go

It is now valid for a user identity to be assigned both a password and an access key in config. Updating to allow that and adding some more tests around config users.
Resolves #1958

fix: allow password and accesskey on config user

---

internal/cmd/kubernetes.go

When writing to the kube config file directly we run the risk of the write operation being terminated unexpectedly. This means we would be at risk of leaving the kube config file in an invalid state. Instead this change writes the new config file to a temp file, then moves that file to overwrite the `~/.kube/config` in an atomic operation.
Resolves #2030

maintain: atomic kube config updates

---

.github/workflows/pull_request.yml

This check is failing on the release branch, because the version on the release branch is different.  
It's fine to skip this check because it's only to catch problems introduced by PRs. The check is to prevent problems for contributors, not quality issues in the release, so skipping it is safe.

maintain: skip file check on release branch

---

ui/pages/destinations/index.js

The Infra Connector `updated` field is no longer updated if nothing has changed in cluster metadata. Using this field to signal cluster connectivity is no longer correct – removing this until we add the correct data in our API for this, and replacing the table column with a `Kind` field

fix: remove incorrect connection field until we support this in the API

---

internal/claims/claims.go
internal/connector/connector_test.go
internal/server/data/token.go

This JWT nonce is not needed, but it is marked as required on the claims struct so the struct will fail validation on previous versions of infra without this field. This is a transitional change that makes the `nonce` not required, we can remove it fully in a few versions when 0.13.0 connectors have been phased out.
Resolves #2081
Re-opened #2014 to track removing this completely.

fix: keep jwt nonce for version compatibility

---

go.mod
go.sum
internal/cmd/agent.go
internal/cmd/agent_test.go
internal/cmd/cmd.go
internal/cmd/list.go
internal/cmd/login.go
internal/logging/logger.go
internal/repeat/timer.go
internal/repeat/timer_test.go

In order to keep the user's local state up to date we need an agent that runs continuously in the background.  This change adds a hidden `infra agent` command which is executed on login and continues to run. The only task in the agent right now is to sync the Kubernetes configuration automatically. If the agent encounters an error it will stop running, this means that when a user logs out that the agent also quits.
The agent does not currently run on start-up. This requires different installation steps for different operating systems, and it will be a separate change.
Resolves #1820

feat: agent to keep kube config up to date

---

internal/server/config.go
internal/server/config_test.go

When an access key that is specified for a user in config is already specified for another user, fail fast. Access keys can only be linked to one user so this is an invalid configuration.
Ex:
```
users:
- name: test
accessKey: aaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbb
- name: anotherTest
accessKey: aaaaaaaaaa.bbbbbbbbbbbbbbbbbbbbbbbb
```
```
{"level":"error","ts":1653485595.127271,"caller":"infra/main.go:17","msg":"creating server: configs: load users: access key assigned to \"anotherTest\" is already assigned to another user, a user's access key must have a unique ID"}
```
Resolves #1983

fix: fail fast on duplicate config access key

---

api/client.go

The UserID arg to `Client.ListGroups` was not being passed to the query parameters map.
TODO: test coverage
The Client itself is pretty minimal. I suspect we'd be better off testing the CLI endpoint that uses it.

fix: pass the userID arg to the request

---

.goreleaser.yml
docs/api/openapi3.json

Goreleaser configs should also inject `Prerelease` and `Metadata` vars. Use env vars `BUILDVERSION_PRERELEASE` and and `BUILDVERSION_METADATA` but set reasonable defaults (empty strings)

fix: release build should not contain dev

---

api/client.go
internal/server/routes.go
internal/server/server_test.go

notFoundHandler no longer assumes how to send the response based on path, but based on the header of the request itself. Users should now specify `application/json`, `text/html` in the Accept header to receive the proper 404.
Resolves #1610

improve: modified notfoundhandler to check accept header

---

docs/reference/cli-reference.md
internal/cmd/grants.go
internal/cmd/info.go
internal/cmd/keys.go

- update keys command help to show the connector case
The help for grants commands was out of date, referencing "identities" rather than "users".
The help for adding a key was confusing in the case of adding a connector. Updated to reflect that common use-case.
Resolves #2104
Resolves #2004

fix: remove identity from CLI help

---

internal/server/server.go
pki/certificates_ext_test.go

This PR removes some unused `loadCertificate` logic and options from the server. We may restore this in the future when it is being used. For now I think it's better to remove it so that contributors are not distracted by it. Removing it also avoids doing unnecessary work on server startup.
This PR also moves one test file into the `pki` package. It was only testing things in that package.  The `pki` package is also not used, but at least it's well contained and is not called by any production code.

maintain: remove some unused server options

---

helm/charts/infra/templates/connector/deployment.yaml
helm/charts/infra/templates/server/deployment.yaml

Fixes issue where template doesn't use the right variable name for the replica count.
Resolves #2188

fix: fix replica count variable name

---

internal/cmd/kubernetes.go

Parsing destinations certificates for the TLS server name is no longer necessary so this code adds no value

maintain(cmd): remove certificate parsing

---

docs/reference/cli-reference.md
internal/cmd/users.go

`infra users edit` incorrectly mentions that `--password` sets the users' "one-time password" when it sets their permanent password. "one-time" has been removed from the help text to resolve the ambiguity.
Resolves #2146

fix: modify set-password help text

---

internal/cmd/users_test.go

We were pulling the user name out of the URL path with RawQuery which can change if `ListUsers()` ever gets modified (which it will, and it's really hard to debug this when it does). This change just pulls the name directly out of the `URL.Query()`

fix: make testuserscmd more resilient

---

internal/cmd/server_test.go
internal/connector/connector.go
internal/server/config.go
internal/server/config_test.go
internal/server/options_migrations.go
internal/server/server.go
internal/server/server_test.go

In #1755 we changed from using `mapstructure` tags to using `config` tags, but I forgot to remove or update all the existing struct tags.
Every other field continued to work because the struct field name matched the convention. Unfortunately `dbUsername` was the one case where it did not match convention and required the struct tag. A workaround was to use `dbUser` or `INFRA_SERVER_DB_USER`.
This PR fixes the bug by renaming the field to `DBUsername`.
It also adds test coverage for every field in `server.Options` to show this is the only field with the problem. 
I also removed the struct tags, since they no longer do anything and keeping them would be confusing. I'll leave some inline comments for where each of the fields is tested.

fix: loading of dbUsername field for server config

---

internal/certs/certs.go

This log message will only be printed once, when the cert is first generated. It would be nice to have it printed on every restart, but the way our TLS config is setup right now that is difficult. Maybe we'll be able to fix that as part of #2176 or #2067, which will involve some work in this area.
After the initial cert generation someone with access to the certificate can produce the fingerprint using `openssl`:
```
openssl x509 -noout -fingerprint -sha256 -inform pem -in
```
The certificate is stored in a file in the directory specified by the `tlsCache` server option.
This fingerprint will be used in #2177, for #1541.
I extracted a couple functions that I expect to use in #2177, but I've left them unexported for now.

server: print sha256 fingerprint of TLS cert to server logs

---

internal/errors.go
internal/server/data/data.go
internal/server/data/group_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/migrations.go
internal/server/data/provider_test.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/models/access_key.go
internal/server/models/credential.go
internal/server/models/destination.go
internal/server/models/encryption_key.go
internal/server/models/group.go
internal/server/models/provider.go

Inspect data errors to detect duplication and provide more details to user when unique constraints are violated.
Update `CreateUser` to _only_ create users and credentials. Previously it will accept the request if the user already exists and update their credentials. This use case should be fulfilled by the UpdateUser endpoint.
Resolves #1686

handle data duplicate errors

---

internal/server/config.go
internal/server/models/identity.go

With the users requiring email change the connector loaded in config was logging a warning. For now this is the only identity that we won't want to log this warning for.
Also remove an admin identity name that is no longer used.
Resolves #1878

fix: do not warn about the connector identity

---

docs/reference/cli-reference.md
internal/cmd/users.go

This period doesnt match the format of the rest of the command help outputs.

fix: remove period from users cmd help

---

docs/api/openapi3.json
internal/server/openapi.go

When users name became required as email I missed updating the generated API doc from a string field. Update the OpenAPI generation to specify that the name is of format "email".

fix: specify email fields in the API doc

---

.github/workflows/release.yml
docs/api/guidelines.md
docs/api/making-requests.md
docs/api/openapi3.json
internal/server/apimigrator.go
internal/server/apimigrator_test.go
internal/server/groups_test.go
internal/server/handlers_test.go
internal/server/openapi.go

The Infra-Version header works best if clients are required to supply it. This PR makes the header required and errors with a helpful message if it is not supplied.

improve: require Infra-Version header

---

docs/api/openapi3.json
internal/server/handlers.go
internal/server/handlers_test.go
internal/server/models/access_key.go

There's an edge case where IssuedFor may either not exist or not set. In this case IssuedForIdentity will be nil and cause a nil pointer dereference. Check if IssuedForIdentity is nil, default to empty string if identity is not found.
Resolves #2185

fix: nil check for AccessKey.IssuedForIdentity

---

docs/reference/cli-reference.md
internal/cmd/cmd.go
internal/cmd/destinations.go
internal/cmd/providers.go
internal/cmd/providers_test.go
internal/cmd/users.go

Introduces the `format` flag. Eg. `--format=json`. 
Introduces the json output for the existing table outputs. It is exactly 1-1 with the API. 
Implements #972

feat: introduce format flag, support json output

---

internal/cmd/grants.go

Grants list queries the server for each user or group which is exceedingly slow when more than a few users/groups exist. It's also unnecessary in a lot of use cases because users and groups will be duplicated for multiple grants. Instead, retrieve a list of users and groups once and lookup the user when necessary
Old code:
```
$ /usr/bin/time -h infra grants list | grep USER
USER (7702)        ACCESS         DESTINATION
20.20s real             1.21s user              0.82s sys
```
New code:
```
$ /usr/bin/time -h infra grants list | grep USER
USER (7702)        ACCESS         DESTINATION
0.28s real              0.14s user              0.05s sys
```
Tested against local Infra server with a permutation of ~100 users, 7 roles, and 10 destinations
Resolves #2231

fix: improve grants list performance

---

internal/cmd/kubernetes.go
internal/cmd/kubernetes_test.go

Respect the users namespace configuration for contexts that do not specify a namespace. Note, if the context is removed through logout or session timeout, the namespace configuration will also be reset. 
If a context managed by infra should have a context, reset it if there's a mismatch.
Resolves #2259

fix: respect context namespace if overwritten by user

---

api/client.go
api/client_test.go
api/types.go
docs/api/openapi3.json
internal/cmd/agent.go
internal/cmd/cmd.go
internal/cmd/list.go
internal/connector/connector.go

- automatically add User-Agent header to all api.Client requests
- refactor api client requests to use a single request func since there's duplication between existing `get`, `list`, and `request`
- update user agent string to include type of client
- update user agent to include api version

maintain: add user-agent to connector requests

---

internal/cmd/cmd.go
internal/cmd/list_test.go
internal/cmd/login.go
internal/cmd/logout.go

Parsing the url here does not do much. We always force the scheme to https, and most other errors won't be noticed until the request is performed.
I looked at using `types.url` as an arg to `apiClient`, but it turns out we expect a hostname in these places instead of a full url. So removing the error return accomplished the same thing with a much smaller change.
Resolves #1627

improve: remove error return from apiClient

---

internal/server/authn/oidc.go
internal/server/authn/oidc_test.go

- if user info response does not have required fields fail
- require the email claim on the id token to fail at the right spot
- check user info name for azure user validity
When a user is deleted from Azure active directory the user info endpoint continues to successfully respond. We use a failure response from this endpoint to determine if a user is still valid. Update this validity check to make sure that the expected fields are returned from the user-info response. This works to revoke Azure user access upon deletion as the user-info endpoint no longer returns their name on deletion. 
Resolves #2227

maintain: validate contents of user info response

---

helm/charts/infra/templates/connector/deployment.yaml
helm/charts/infra/templates/server/deployment.yaml

Provide a way for users to set log level using helm values. This change is necessary because `logLevel` is not read from config but retrieved directly from env var or command line parameter
Resolves #2079

fix: set logLevel from helm chart values

---

docs/reference/cli-reference.md
internal/cmd/agent.go
internal/cmd/login.go
internal/cmd/login_test.go

- add no-agent flag to disable the background process
- Inform the user that Infra is running in the background
> As part of infra login we start a desktop agent to keep the kubernetes config up-to-date. The user needs to be aware of this agent in case they need to stop it, and so that if it ever conflicts with another change to the kube config, they are not puzzle by why their change was dropped.
Resolves #2175

maintain: make the agent optional

---

api/access_key.go
api/destination.go
api/grant.go
api/group.go
api/pagination.go
api/provider.go
api/types.go
api/user.go
docs/api/openapi3.json
internal/access/access_key.go
internal/access/destination.go
internal/access/grant.go
internal/access/group.go
internal/access/identity.go
internal/access/identity_test.go
internal/access/provider.go
internal/server/data/selectors.go
internal/server/grants_test.go
internal/server/groups_test.go
internal/server/handlers.go
internal/server/handlers_test.go
internal/server/migrations.go
internal/server/models/pagination.go
internal/server/openapi.go

All lists can now be (optionally) paginated by specifying the page or limit as a query parameter. Later, pagination can be the default and entire-list queries can be done using multiple requests, but it is optional now.
```bash
$ curl --request GET \
--url "http://localhost/api/grants?page=1&limit=3" \
--header 'Accept: application/json' --header "Authorization: Bearer $ACCESSKEY" --header 'Infra-Version: 0.13.4' -k
{
"pagination_info": {
"page": 1,
"limit": 3
},
"items": [
{
"id": "7Yvd3ELXfs",
...
},
{
"id": "7YvgA9zUSW",
...
},
{
"id": "7YwqCVP4yL",
...
}
],
"count": 3
}
```

feat: added optional pagination to list endpoints

---

internal/cmd/login_test.go

Without this the console output may not contain a newline, which causes problems with `test2json` (ex: https://github.com/infrahq/infra/runs/6906405805?check_suite_focus=true#step:7:646) and can leave control sequences on the terminal after tests end:
```
^[[79;158R^[[79;10R^[[79;158R^[[79;13R^[[79;158R^[[79;21R^[[79;158R^[[79;10R^[[79;158R^[[79
```
A single newline seems to fix the problem.

maintain: add a newline to test output

---

ui/pages/destinations/index.js

Extremely simple fix to url running over (overflow scroll)
Resolves #2173

fix: url running over when clicking on cluster in ui

---

docs/getting-started/quickstart.md

It's not clear in the quickstart that the access key you create for the connector will expire in 30 days. Note it at the time of creation.

maintain: document default connector key lifetime

---

api/types.go
go.mod
go.sum
internal/cmd/format.go
internal/cmd/format_test.go
internal/cmd/keys.go
internal/cmd/testdata/TestKeysListCmd/list_all
internal/cmd/users.go

go-prettytime uses the wrong suffix when the value is between 1.5 and 2. Replace the library with a modified version of go-units formatting. The go-units implementation is much easier to follow and does not have that bug.
This PR also removes the `api.Time.Relative` method, and moves the implementation to the `cmd` package where it is used. Formatting values is the responsibility of the CLI.

Replace go-prettytime

---

api/client.go
docs/api/openapi3.json
internal/access/group.go
internal/cmd/groups.go
internal/server/data/identity.go
internal/server/groups_test.go
internal/server/handlers.go
internal/server/models/group.go
internal/server/routes.go

This change allows users to add and remove simple groups from the CLI, and also includes a new delete group endpoint.

Add and remove groups

---

.github/workflows/fuzz.yaml
.github/workflows/pull_request.yml

Downloading dependencies only takes 5 seconds for me locally (with an empty GOMODCACHE), but it appears to take ~2m30s
for every CI job that runs or builds the project.
This change should give us some idea of why it is so slow in CI.

ci: add timing and caching to go steps

---

internal/cmd/login_test.go
internal/race/norace.go
internal/race/race.go
internal/server/server.go

**Stop http servers on shutdown**
This shouldn't impact production at all, but when running a server for tests we were not
releasing the ports until the process exited. When running with `-count=`100 this could
consume all ports.
With this change the server is closed before the test ends, which closes the listener
and releases the ports.
**Reduce the chance of a timeout**
When the login test times out the t.Cleanup function could attempt to
close the pty at the same time as the login command running in a
separate goroutine is attempting to read from it.
We can't fix the data race because the survey library does not provide
any way to cancel the prompt. So instead we have to try and prevent
the timeout.
This PR increases the timeout used with expect when the race detector is
enabled.

Fix a couple problems with login tests

---

internal/access/identity.go
internal/cmd/users.go
internal/server/config.go
internal/server/data/access_key.go
internal/server/data/data.go
internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/data/provideruser.go

- remove access keys when a provider is removed
- remove provider_users when a provider is removed
- remove users if they have no more provider_users
Resolves #2260

fix: delete access keys and users when providers are removed

---

internal/certs/certs.go
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/config.go
internal/cmd/errors.go
internal/cmd/kubernetes.go
internal/cmd/list_test.go
internal/cmd/login.go
internal/cmd/login_test.go
internal/cmd/logout.go
internal/cmd/logout_test.go

This PR adds a new prompt to `infra login` when the servers TLS certificate is not already trusted. The prompt gives the user information about the server certificate and allows them to manually trust it.
Once trusted, the user will be able to login again to the same server without being prompted again.
This is a significant enhancement over `--skip-tls-verify` because even if the user doesn't properly inspect the fingerprint, the only opportunity for a man-in-the-middle attack is on that first request. Every subsequent request is secure.
In a follow up PR I will:
* add a command line flag to specify a trusted certificate
* add the same flag to the connector
* update the quickstart to remove `--skip-tls-verify`
Resolves #1541

cli: prompt to accept the server TLS certificate for manual verification

---

api/client.go
api/user.go
docs/api/openapi3.json
internal/access/credential.go
internal/access/identity.go
internal/access/identity_test.go
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/config.go
internal/cmd/config_migration.go
internal/cmd/errors.go
internal/cmd/grants.go
internal/cmd/info.go
internal/cmd/list.go
internal/cmd/list_test.go
internal/cmd/login.go
internal/cmd/login_test.go
internal/cmd/logout.go
internal/cmd/logout_test.go
internal/cmd/users.go
internal/generate/generate.go
internal/generate/generate_test.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/data.go
internal/server/data/provideruser.go
internal/server/data/token.go
internal/server/handlers.go
internal/server/handlers_test.go
internal/server/middleware_test.go

```
$ ./infra users edit joe@example.com --password
Error: existing credential: record not found
$ ./infra users add joe@example.com
Added user "joe@example.com"
Password: SJXiwhr1Kvcy
$ ./infra users edit joe@example.com --password
Temporary password for user "joe@example.com" set to: Y*Wv?|Ugv@mX
$ ./infra login localhost
? Select a login method: Login with username and password
? Username: joe@example.com
? Password: ************
Your password has expired. Please update your password (min. length 8).
? Password: *************
? Confirm Password: *************
Updated password.
Logged in as joe@example.com
$ ./infra users edit joe@example.com --password
Enter a new password (min. length 8):
? Password: ********
? Confirm Password: ********
Updated password
```
Resolves #2145

improve: resetting passwords for other users should create a temp password

---

internal/access/identity.go
internal/access/login.go
internal/access/signup_test.go
internal/server/authn/authn_method.go
internal/server/authn/authn_method_test.go
internal/server/authn/key_exchange.go
internal/server/authn/key_exchange_test.go
internal/server/authn/oidc.go
internal/server/authn/oidc_test.go
internal/server/authn/password_credentials.go
internal/server/authn/password_credentials_test.go
internal/server/handlers.go

By passing the context along from the API request
1. The `odic` and `oauth2` libraries can make use of an `http.Client` stored in the context values. We can set the `http.Client` in some API middelware. This allows us to log all the request, and possibly do something like #1793
2. if the client disconnects we can also cancel the request to the provider, so that the request can exit instead of continue to block waiting on the provider.
Using a logging transport I noticed we were requesting the `.well-known/openid-configuration` 3 times from the oidc provider as part of a single API login request. The last commit removes one of these calls by refactoring `tokenSource` a bit. I think to remove the second call we would need to create the `oidc.Provider` in `NewOIDC`, instead of doing it in …

Use request context for oidc calls

---

docs/reference/cli-reference.md
internal/cmd/cmd_test.go
internal/cmd/config.go
internal/cmd/list_test.go
internal/cmd/login.go
internal/cmd/login_test.go
internal/cmd/logout_test.go
internal/cmd/testdata/TestLoginCmd_TLSVerify/login_with_wrong_fingerprint
internal/cmd/types/file.go

This PR adds a new `--tls-trusted-cert` flag to `infra login`. The flag can be used to specify either the server TLS certificate, or a CA that was used to create the certificate.
This PR is branched from #2177, which adds most of the support that was needed. That PR will need to merge first.
Resolves #2177

cmd/login: add --tls-trusted-cert flag 

---

internal/access/identity.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/selectors.go
internal/server/handlers_test.go

Add a unit test to list users in a group. There are already unit tests for the data layer, however not currently one which accesses the actual http routes/handlers. 
Resolves #

maintain: add unit test for listing users in a given group

---

ui/pages/destinations/index.js

This fixes an issue where UI rendering feel erroneous:
1. When a cluster doesn't publish namespaces (e.g. an old connector)
2. When a non-admin user browses namespaces, the sidebar is currently blank, this adds back a (mostly empty) metadata section

fix(ui): fix a few edge cases around missing namespaces and no admin access

---

internal/access/identity.go
internal/server/authn/oidc.go
internal/server/authn/oidc_test.go
internal/server/data/provideruser.go
internal/server/data/selectors.go
internal/server/errors.go
internal/server/handlers.go
internal/server/providers/azure.go
internal/server/providers/errors.go
internal/server/providers/oidc.go
internal/server/providers/oidc_test.go
internal/server/providers/okta.go

- move provider logic to its own package
- move user info check into a general user sync function
- move token check to user sync
This change enables calling the Microsoft graph API to synchronize groups in the case of using Azure as an identity provider. It moves the provider logic into its own `provider` package and out of the `authn` package.
This change is notably lacking in tests because the provider code-paths rely so heavily on external APIs. I've opened #2354 for getting better test coverage here, and I'll work on that next. Testing these is probably going to require standing up a local server that responds to the requests as expected.
Resolves #

feat: azure groups

---

website/components/DocsLayout.js

Fixes loooong words in markdown causing layout issues because they don't break

fix(website): break words if necessary to avoid layout issues

---

internal/cmd/grants.go

Add a newline between user and group grants if output non-zero number of user grants. This makes the output much more readable
Resolves #2374

fix(cmd): insert newline between user and group grants

---

internal/certs/certs.go
internal/server/server.go

`SelfSignedOrLetsEncryptCert` is a closure. The closure was called with `serverName=""`, and the inner function also modified `serverName`, so after the first request the `serverName` would never change. It would also be set to the value of the first request.
This resulted in the wrong TLS certificate being returned to clients. The client would error because the hostnames do not match.
I attempted to write a test for this, but `httptest.Server.StartTLS` isn't ware of `tls.Config.GetCertificate`. It only looks at `tls.Config.Certificates`, so it never calls `SelfSignedOrLetsEncryptCert`.  We'd have to use a regular `http.Server`, but even that is a challenge because we throw away the CA used to generate these.
This will all be changing for #2176, so I'll write some more test cases as part …

fix: use the correct TLS certificate

---

docs/getting-started/quickstart.md

Related to #296
Give users a `kubectl` command in the quickstart to look up the fingerprint of the server's TLS certificate.

improve: add fingerprint lookup to quickstart

---

internal/server/data/migrations.go

`==` is a valid sqlite operator but not a valid postgresql operator. change it to `=` which is more portable
```
postgres      | 2022-06-24 01:29:55.564 UTC [34] ERROR:  operator does not exist: text == unknown at character 62
postgres      | 2022-06-24 01:29:55.564 UTC [34] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
postgres      | 2022-06-24 01:29:55.564 UTC [34] STATEMENT:  UPDATE "providers" SET "kind"=$1 WHERE kind IS NULL AND name == $2
postgres      | 2022-06-24 01:29:55.564 UTC [34] ERROR:  current transaction is aborted, commands ignored until end of transaction block
postgres      | 2022-06-24 01:29:55.564 UTC [34] STATEMENT:  UPDATE "providers" SET "kind"=$1 WHERE kind IS NULL
```
Resolves #

fix: db migration from 0.13.3

---

internal/server/providers/oidc.go

- provider user groups are updated in the data package when an identity is assigned to groups
This is an error from the Azure groups update which causes Okta groups to not be updated on a user. When a user's groups are updated from a provider the provider-user relation was being updated before the groups were assigned, this meant that the provider's groups were not seen as "new groups" in the data package when the user relation was updated.
Associated test is in the separate OIDC testing PR:
https://github.com/infrahq/infra/pull/2394/commits/c342c92ce42f9142ae6aabccb59941790178e1b8
Resolves #2412

fix: do not update provider user groups in sync

---

helm/charts/infra/templates/connector/deployment.yaml
internal/kubernetes/kubernetes.go

When more than one deployment of infra exists, the service query will possibly return the incorrect service endpoint since the selector it uses is common to all deployments. Instead mount and add the instance label to the selector as well. The instance selector, when deployed with Helm, is the name of the deployment and will be unique between deployments. This will allow the connector to find the right service.
Resolves #2365

fix: connector service query

---

internal/server/errors.go
internal/server/errors_test.go
internal/server/handlers.go

First I audited all the places we use `internal.ErrUnauthorized` to make sure all of them provide additional context. I fixed one error that did not have additional context, and one place where we hid the error (and only logged it with `Debug`).
Then I changed `sendAPIError` to make sure that we log the full error at `Warn` level, along with relevant request details.
Testing this with an automated test is difficult until we do #1609. I tested manually that these messages are at the warn level and contain the relevant context.

improve: log authn errors

---

.github/workflows/pull_request.yml
.gitignore
CODEOWNERS
internal/openapigen/main.go
internal/server/openapi.go
internal/server/openapi_test.go
internal/server/testdata/openapi3.json

Previously we were writing the openapi3 doc to the path that would be used forpublic docs.
This caused us problems because after a release we had to update the doc to the new version.
This commit moves the openspi3.json doc testdata. This allows us to preview any API changes, and catch any problems with doc generation in any PR that makes changes, without the problem of having to update the version.
As part of releasing the website we will generate this doc again, so the version will be correct on the website.

maintain: move openapi3 spec to testdata

---

internal/connector/connector.go
internal/connector/metrics.go
internal/server/metrics.go
internal/server/server.go

Add prometheus metric for connector version and other build information
Also use `internal.FullVersion` instead of just `internal.version`
Raw metric looks something like this:
```
build_info{branch="main",commit="",date="",version="0.13.5"} 1
```
Resolves #2429

feat: add connector build_info

---

internal/access/group.go
internal/server/data/group.go
internal/server/groups_test.go

The way we were looking up user IDs when adding or removing them from groups was fairly costly. This change uses the `ListIdentities()` call with the `ByIDs()` selector to verify that an ID exists. It also adds a couple of unit tests, and cleans up the `INSERT OR IGNORE` statement.

cleanup checking IDs while updating group membership

---

internal/server/providers/oidc_test.go

```
WARN [runner/nolint] Found unknown linters in //nolint directives: forcedtypeassert
```
Should be `forcetypeassert`

fix: unrecognized lint nolint directive

---

helm/charts/infra/templates/connector/secret.yaml

This PR changes the infra-connector-ca secret helm template to only `genCA` if there is not an existing secret. Also adds a few comments to the `{{ end }}` tags to make it easier to follow.
This `secret.yaml` is modeled after the one for infra server, added in #2401.

helm: refactor to not create a new CA on every connector deploy

---

internal/logging/logger.go
internal/server/handlers_test.go

With our recent logging changes the default log level changed from info to trace. This
caused most test failures to include tons of trace-level DB query logs. This logs make
the actual failure message harder to find.
Similarly, the gin default mode is debug. Calling SetMode sets it to release mode, while
still allowing for the GIN_MODE= environment variable to set it back to debug.

Make tests easier to debug by hiding unrelated output

---

api/client.go
api/client_test.go

The API client delete request does not use the common `request` function which means its missing things like `Infra-Version`, `User-Agent`, and other common configurations.

fix: client delete request

---

ui/pages/providers/add/details.js

Adding non-Okta providers through the UI that didn't have the same 'name' as their 'kind' would re-direct the user back to the provider screen when attempting to add. This fixes the behavior by removing this check and updates the relevant doc link also.
Related to #2353

fix: add provider buttons should not check name against kind

---

Makefile
helm/charts/infra/templates/server/configmap.yaml
helm/charts/infra/templates/server/deployment.yaml
helm/charts/infra/templates/server/secret.yaml
helm/charts/infra/values.yaml
internal/certs/certs.go
internal/cmd/list_test.go
internal/cmd/login_test.go
internal/cmd/server_test.go
internal/server/server.go
internal/server/server_test.go
internal/server/tls.go
internal/server/tls_test.go

The first commit moves some functions to `tls.go`, so best viewed by individual commit.
With the changes in this PR, a user has 3 options for configuring TLS:
1. set `tls.ACME=true`, to use ACME to create a publicly trusted certificate
2. set `tls.ca` and `tls.caPrivateKey`, which will be used to generate a TLS ceritifcate for any hostname the client requests.
3. set `tls.certificate` and `tls.privateKey` to use that certificate for TLS
We plan on setting a CA as part of the helm deploy, so the default for any user that uses our helm charts will be to specify nothing and use option 2.
ACME is no longer the default option. It has to be explicitly enabled, which is probably better because currently every single TLS request could make an ACME API request, even when it should never be used. …

tls: generate server TLS cert from CA

---

internal/cmd/login.go
internal/cmd/server_test.go
internal/server/tls.go

Branched from #2401
This ended up being easier than I thought. By adding the CA cert to the chain returned by the server the client side error already has the right cert.  Also log the CA fingerprint in the server on startup so that it is visible in logs.
Resolves #2362

improve: include the server TLS CA in the chain

---

ui/pages/login/finish.js
ui/pages/settings/password-reset.js
ui/pages/signup/index.js

- added password confirmation field on signup and initial password reset (#2108)
- prevent user to reset password that is invalid (#2373)
- improve confirmation password field error handling
Resolves #2108 
Resolves #2373

fix: password confirmation field and minor improvements

---

docs/configuration/working-with-users.md

Fix up some references in our docs which point to the unused `infra id` command to instead use `infra users`

maintain(docs): fix typos in the cli user docs

---

api/destination.go
internal/cmd/destinations.go
internal/server/handlers_test.go
internal/server/models/destination.go
internal/server/testdata/openapi3.json
ui/pages/destinations/index.js

- Add Destination `Status` API field
- Add columns for Status and Last Seen to CLI and UI list outputs
```
$ infra destinations list
NAME            URL                 STATUS        LAST SEEN
docker-desktop  localhost:123       Disconnected  never
docker-desktop  localhost:123       Disconnected  never
docker-desktop  10.98.125.93:10443  Connected     1 second ago
```
Resolves #2151

feat: add destination status and last seen to CLI and UI

---

internal/cmd/login.go
internal/cmd/login_test.go

- ensure we always get refresh token from google oidc
The Google OIDC login flow requires a special parameter to be specified in order to retrieve a refresh token. This differs from the more standard offline scope we use to get the refresh token. This change ensures we always get a refresh token from Google OIDC so that user sessions are valid longer.
Resolves #2499

fix: offline access for google

---

api/access_key.go
internal/cmd/format.go
internal/cmd/format_test.go
internal/cmd/keys.go
internal/cmd/keys_test.go
internal/cmd/server_test.go
internal/server/authn/key_exchange_test.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/errors.go
internal/server/data/migrations_test.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/testdata/openapi3.json

- output lifetime and extension deadline from keys add command
- specify when an access key was valid but is now expired
The connector key expired after 30 days by default. This was not clear in our workflow or docs and caused an unexpected failure for connectors after the 30 day period ends. This change alleviates the problem by specifying the access key lifetime on creation and giving info in the error response for expired keys that detail the actual problem.
The connector log will look something like this when the access key expires:
```
{"level":"error","time":1657026989645,"caller":"logging/logger.go:58","message":"initializing destination: error listing destinations: unauthorized: access key expired: extension deadline exceeded"}
```
Resolves #2293

feat: better feedback for connector key

---

ui/components/layouts/dashboard.js
ui/components/sidebar.js
ui/pages/destinations/index.js

Fixes  #2514:
Also fixes #2515 and an issue where clicking a destination row would expand it

fix(ui): fix minor issues in destinations dashboard

---

.github/workflows/build.yml
.github/workflows/publish.yml
.github/workflows/release.yml

- fix job dependency in release workflow
- revert setting GORELEASER_CURRENT_TAG; goreleaser requires this to exist which in the case of the dev build will never exist. Find another way to set the right version.

fix: build

---

.github/workflows/publish.yml

Container image already has it installed and `apt-get` exits with error

maintain: no need to install jq

---

api/client.go
internal/cmd/login.go
main.go

Earlier, the CLI would show EOF when the server wasn't ready/unable to connect to and the user tried to login (or use a different command upon update).
It now shows:
`Could not reach infra server, please wait a moment and try again.`
Resolves #2307

improve: eof errors are more user friendly

---

internal/validate/email.go
internal/validate/email_test.go
internal/validate/string.go
internal/validate/string_test.go
internal/validate/validate.go
internal/validate/validate_test.go

This is the first step in replacing our API request validation.
This PR adds a library with validation rules that we already use today. It does not integrate it into our API handler or openapi doc generation yet.
Follow up items:
* replace validate struct tags with this validation
* at the same time, integrate with openapi doc generation
Follow up PRs: #2501, #2527
Related to #1763

api: add a library for declarative request validation

---

internal/server/metrics.go

* Deleted entries are not filtered in metrics or other `Raw` queries. These are normally handled automatically by `gorm` but `Raw` is excluded
* Destination.Version maybe null or empty which will return two distinct metrics that look the same to Prometheus, causing it to error. Alternatively, can add a migration to explicitly set version to empty but that seems worse.

fix: server metrics

---

api/types.go
internal/server/apimigrator.go
internal/server/openapi.go
internal/server/testdata/openapi3.json
uid/polymorphic.go
uid/snowid.go

This commit moves schema descriptions for api types from being hard-coded in the openapi doc generation, to being methods on the types being described. This `DescribeSchema` method is the same interface we use in `internal/validate` to allow validation rules to describe themselves.
By using an interface it makes it easy for us to support new api types without modifying the openapi doc generation.

api: allow types to define their own default values for openapi schema

---

internal/server/data/settings.go
internal/server/data/settings_test.go
internal/server/server.go
internal/server/telemetry.go

Primarily this PR changes `InitializeSettings`, so that it only creates a new private key for JWT signing when there are not existing settings. Previously we were generating a private key and throwing it away on every server startup.
While working on that area I also did a bit of cleanup:
* Added tests for `data.InitializeSettings`
* Use the settings returned by `InitializeSettings`, and store it on the `Telemetry` struct instead of a package-level static variable.
* Remove the error return from NewTelemetry, a nil db is a programming error that should panic.
* Remove `configureTelemetry`. Call `NewTelemetry` directly and assign it to the server field directly, making the the code easier to trace.
* Call `Telemetry.Close` to flush telemetry on server shutdown, previously this was not …

Small improvement to InitializeSettings and Telemetry

---

internal/logging/logger.go
internal/logging/middleware.go
internal/logging/middleware_test.go

This PR makes a few improvements to our API log sampling, added in #2555.
* never sample requests if the status code is >= 400, errors should always be logged. Previously we were looking at `gin.Context.Errors` to determine this, but we are not populated it yet
* never sample non-GET requests. Any POST, PUT, or DELETE should be logged as they modify data and should not happen as frequently
* turn off sampling if the log level is set to `DEBUG` or `TRACE`. In those cases the user probably does not want sampling. This gives us an easy way to see all requests in development.
* update the tests to be a bit more strict about the expected log output, and include some test cases that use parameters in the URL to show the sampling works correctly with parameters.
* use a `sync.Map` instead of a …

api: only sample successful GET requests

---

internal/cmd/login.go
internal/cmd/login_test.go

In the most recent CLI version the auth URL is sent from the server, but old versions of the server do not send this value. For backwards compatibility, the CLI is now able to resolve the auth URL it needs from a provider in the case its not present. If we don't do this the CLI attempts to redirect the user to a local directory. 
Resolves #2553

fix: resolve the provider url when not provided

---

helm/charts/infra/templates/server/_helpers.tpl

Small typo fix in server's labels helper function, was referencing a non-existing key in the global values block
Resolves #

infra chart: typo in server labels helper function

---

api/access_key.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/handlers_test.go
internal/server/openapi.go
internal/server/routes.go
internal/server/testdata/openapi3.json
internal/server/tls_test.go

Branched from #2158
This PR adds validation rules to `CreateAccessKeyRequest`. Also updates the test for `CreateAccessKey` and adds a test case for failed validation.
It also integrates the `internal/validate` library with both the `routes.go` framework, and openapi doc generation.
* Handle the validation error in sendAPIError.
* Call Validate from the handler wrapper.
* Call DescribeSchema from openapi doc generation.
* Change the text of the required validation rule failure.
Related to #1763

api: integrate validation library

---

api/access_key.go
api/destination.go
api/group.go
api/provider.go
api/user.go
internal/server/destination_test.go
internal/server/handlers_test.go
internal/server/openapi.go
internal/server/testdata/openapi3.json
internal/validate/validate.go
internal/validate/validate_test.go

Branched from #2527
This PR adds validation rules to `CreateDestinationRequest` and `UpdateDestinationRequest`.
These are the first two structs that have nested validation, so most of the PR is adding support for nested rules.
The challenge with nested structs is that openapi doc generation uses reflection (don't see any way around that), but `Validate` does not. The `ValidationRules` on a struct can't return the rules for nested or embedded structs, since we'd see them described the wrong way in openapi doc generation.  
So `Validate` ends up needing to use reflection as well, to match `DescribeSchema`.
In the current state:
* openapi doc generation calls `DescribeSchema` on the nested fields
* `Validate` will call `ValidationRules` on the top level struct, and use reflection to traverse …

Support nested structs in request validation

---

.github/workflows/publish.yml
.github/workflows/release_candidate.yml

The default conditions for `latest` tag enable it in the release-please branch. This causes dev images to also be released as `latest` which is bad.
Also remove unnecessary `apt-get install jq`; `jq` is already installed on the github runners and this command also requires `sudo` which means it also errors.
Resolves #2581

fix: docker images tags latest for dev

---

internal/server/data/access_key_test.go
internal/server/data/selectors.go

Quick fix for keys list on postgres. Changes `is` to `=`.
Resolves #2451 
Resolves #2578

fix: infra keys list works with postgres

---

helm/charts/infra/templates/connector/configmap.yaml
helm/charts/infra/values.yaml
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/connector/authn.go
internal/connector/connector.go
internal/connector/connector_test.go
internal/server/tls.go

Branched from #2401
This PR adds support to the connector to trust the TLS CA or certificate of the server.
With this change, someone deploying a connector can set the trusted certificate instead of `skipTLSVerify`:
```
helm upgrade --install infra-connector ... --set connector.config.serverTrustedCertificate="$(cat server.ca)"
```
I think we can improve this by fetching the CA for them, if they've already trusted it in the CLI. We might also want to fetch it out of a previous config map to remove the need to set it every time. I think those could be follow up PRs.

connector: verify the server TLS

---

api/provider.go
internal/server/handlers.go
internal/server/handlers_test.go
internal/server/providers/oidc.go
internal/server/providers_test.go
internal/server/testdata/openapi3.json
internal/validate/string.go
internal/validate/string_test.go
internal/validate/validate_test.go

Branched from #2570
This PR adds a new `Enum` rule to `internal/validate`, and adds validation rules for `CreateProvider`, and `UpdateProvider`. Also adds API handler tests for those operations.
Best viewed by individual commit. There are a couple small cleanups in separate commits.
Related to https://github.com/infrahq/infra/issues/1763

Add validation rules to provider requests

---

.github/workflows/build.yml

The variable is a GitHub actions input variable and needs to be exposed to the env.
This fixes a miss in https://github.com/infrahq/infra/pull/2591 which causes the job to fail
Resolves #2522

fix: load env var RELEASE_NAME into goreleaser

---

.github/release-please.json

Minor cleanup: `docs/api/openapi3.json` doesn't exist anymore so these configurations are unnecessary

maintain: docs/api/openapi3.json no longer exists

---

internal/connector/connector.go
internal/server/metrics.go
internal/server/metrics_test.go
internal/server/openapi.go
internal/server/openapi_test.go
internal/server/testdata/TestMetrics/build_info
metrics/metrics.go

This test depends on the product version, so the expected value changes
every time we create a new release branch, and after every release.
This commit fixes the problem by using the existing shim we added for
openapi doc generation. We can patch that shim in a test to set a
hardcoded version.
This way the expected value does not change when the product version
changes.
The test failure can be seen here: https://github.com/infrahq/infra/runs/7362326501?check_suite_focus=true

Fix TestMetrics failing on the release branch

---

helm/charts/infra/templates/connector/configmap.yaml

fix: restore skipTLSVerify for connector helm template

---

internal/server/errors.go
internal/server/errors_test.go
internal/server/openapi.go
internal/server/routes.go
internal/server/server.go
internal/server/validator.go

Branched from #2593
Now that all API requests have been converted to `internal/validate` we can remove support for the `validate` tag from OpenAPI doc generation, and from the api handlers.
Other uses of pgValidate will be removed in #2583 
Resolves https://github.com/infrahq/infra/issues/1763

api: remove integration with go-playground/validator

---

.github/workflows/pull_request.yml

Because the latest is hanging in CI and never finishing.
Let's see if this works.

ci: pin golangci-lint version

---

api/access_key.go
api/client.go
api/destination.go
api/grant.go
api/group.go
api/pagination.go
api/provider.go
api/user.go
internal/cmd/destinations.go
internal/cmd/errors.go
internal/cmd/grants.go
internal/cmd/groups.go
internal/cmd/info.go
internal/cmd/keys.go
internal/cmd/kubernetes.go
internal/cmd/login.go
internal/cmd/pagination.go
internal/cmd/pagination_test.go
internal/cmd/providers.go
internal/cmd/users.go

The `infra list ___` command now compiles its list of Items through multiple API requests (multiple pages) if there are more than 100 records.
The main logic is added in the `Paginatable` interface and `listAll` function.

feat: pagination in cli

---

internal/server/data/destination.go
internal/server/data/destination_test.go
internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/metrics.go

postgres complains the last_seen_at select param isn't in `GROUP BY` even though it is because gorm templates out the comparison value as two distinct values.
Improve testability by moving the complex queries to the data package where it can be easily tested against both sqlite and postgres. Also revert the more basic count queries back to using `data.Count`. Changing these to a raw query was premature.

fix: destinations query errors in postgres

---

docs/configuration/granting-access.md
docs/getting-started/what-is-infra.md
internal/cmd/grants.go

Changed wording to be more consistent in `infra grants add` and `infra grants list` commands.
Resolves #2105

fix: inconsistencies between role and access terms in `infra grants add` and `infra grants list`

---

internal/cmd/local_server.go
internal/connector/connector.go
internal/server/server.go
internal/server/tls_test.go

fixes an issue with the upcoming 1.47.0 golangci linter
Resolves #

fix: linter: add read-header timeouts for all servers

---

internal/server/data/migrations.go
internal/server/providers/azure_test.go
internal/server/providers/oidc.go
internal/server/providers/oidc_test.go

We can provide better error messages by validating the fields manually, so no need to use `internal/validate` here.
Related to #2583

Remove pgValidate from providers

---

.github/workflows/fuzz.yaml
.github/workflows/pull_request.yml

The caching in the lint action duplicates the cache we already have from `setup-go`. Using the second cache causes ~23000 lines of warnings in the lint step.  Disabling the cache should prevent that.
Also restore the caching of the fuzz corpus. I had removed the cache because I thought the setup-go cache would take care of it, but it turns out that setup-go only caches go/cache/mod, not all of go/cache.

ci: disable caching in lint, and restore cache in fuzz

---

helm/charts/infra/templates/server/horizontalpodautoscaler.yaml
helm/charts/infra/values.yaml

By default, we should not set a scaling target for CPU since it may add undesirable conditions to the HPA. Instead, the operator should set these manually. Also added a note about setting the server.resources. Otherwise the HPA has no metric to target.
Changed the order of cpu/memory. The order makes a difference in something like ArgoCD because the output manifest is compared to the live manifest and if there's even a small difference, the controller will constantly try to reconcile the two.

maintain: unset default hpa scaling targets

---

internal/logging/middleware.go

Host may be misunderstood to mean the server the request is hosted
rather the address used to address the service. There's also a
nice symmetry between localAddr and remoteAddr.

improve: replace request log host with localAddr

---

ui/pages/providers/index.js

the provider icon on the table was too small - resize to `height: .75rem`
Resolves #2598

fix: resize provider icon on table

---

api/login.go
api/signup.go
internal/server/config.go
internal/server/config_test.go
internal/server/handlers.go
internal/server/login_test.go
internal/server/signup_test.go
internal/server/testdata/openapi3.json

When we removed identity `kinds` we standardized users to have a `name` rather than an `email`. This was before our migration code, so there was some manual conversion left in. This change cleans up these conversions.
Not adding this to the migrator as the change was on a much older version that is most likely not in use anywhere.
Resolves #1825

maintain: remove email migration from login

---

ui/components/layouts/dashboard.js

- await logout to complete before redirecting to login to prevent race condition
Occasionally when you click "logout" the UI would still display the dashboard. This was due to redirecting to login before the logout response was received. Awaiting the logout response ensures we always redirect to login when a user clicks "logout".
Resolves #2526

fix: wait for logout to complete

---

api/group.go
internal/server/access_keys_test.go
internal/server/testdata/openapi3.json
internal/validate/string.go
internal/validate/string_test.go
internal/validate/validate_test.go

Group names can come from providers, which may allow any characters. So we need to support all characters group names unless we do some kind of internal mapping between names. For now we'll need to remove our validation of group name.
Also improve the error message when the invalid character is a space

fix: remove group name validation

---

Dockerfile

Create and run as a non-root user (infra) by default.
Changing the run-as user through Kubernetes pod security contexts requires #2689. The server currently creates a `.infra` directory in the running user's home directory. If the security context `runAsUser` does not exist or does not have a home directory, Infra will errorneously try to create the `.infra` directory under `/` and error out with `permission denied`.
Resolves #2688

fix: run as non-root user by default

---

helm/charts/infra/values.yaml
internal/cmd/agent.go
internal/cmd/config.go
internal/server/server.go
internal/server/tls.go
internal/server/tls_test.go

Best practices for Kubernetes security suggest setting `readOnlyRootFilesystem` on pods to ensure they are always in the expected state. This change enables this flag by default and removes filesystem writes from the server runtime.
Resolves #2689

feat: make infra server read-only at runtime

---

helm/charts/infra/templates/server/deployment.yaml

If the runtime user changes, the sqlite database files must change owners otherwise the server will no longer have write access to the database. In this PR, we add a new init container to change the owner of the database files. 
The init container is only created if the server deployment has persistence enabled. Deployments with persistence disabled or are using an external database are not affected.
Resolves #2693

fix: migrate sqlite3 db owner if changing security contexts

---

ui/__test__/login.test.js
ui/pages/login/index.js
ui/pages/signup/index.js

Rename the input label to `Email` instead of `Username or Email` since we only accept email for this field and we also run the email validation on the field as well.

fix: rename input label

---

api/access_key.go
internal/server/testdata/openapi3.json

Changes name validation to have minLength of 2 and updated openapi doc.
Resolves #2701

fix: validation accepts names of length 2

---

ui/pages/login/index.js

The current login page without provider looks like this
which the OR should be hidden when there is no provider

fix: login page ui bug

---

internal/cmd/kubernetes.go
internal/cmd/kubernetes_test.go

You may have noticed warnings about kube config file permissions. This fixes the permissions to be only user read/write.
os.Create sets the file to world and group readable, this causes kubectl to warn the user, revert to ioutil.TempFile which sets the kube config to 0o600. This is still Windows compatible because it explicitly closes the file, so it won't cause a regression of #2586.
Resolves #2699

fix: kube config permissions user read/write

---

go.mod
internal/server/data/access_key.go
internal/server/data/credential.go
internal/server/data/data.go
internal/server/data/destination.go
internal/server/data/grant.go
internal/server/data/provider.go
internal/server/data/provideruser.go
internal/server/models/access_key.go
internal/server/models/credential.go
internal/server/models/destination.go
internal/server/models/grant.go
internal/server/models/provider.go
internal/server/models/provideruser.go

These validations are not of user input, but are safeguards for developers. They don't really benefit from the additional logic and indirection of internal/validate, so we can validate that fields are set by checking they are non-zero before a save or update.
Resolves #2583

Remove last use of go-playground/validator in models

---

internal/access/access.go
internal/access/grant.go
internal/access/group.go
internal/access/identity_test.go
internal/server/config_test.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/destination.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/data/group.go
internal/server/data/group_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/data/provideruser_test.go
internal/server/data/token.go
internal/server/grants.go
internal/server/grants_test.go
internal/server/groups_test.go
internal/server/middleware.go
internal/server/models/pagination.go
internal/server/providers_test.go
internal/server/users_test.go

List requests in the API will be paginated by default (Page 1 and Limit 100 if not specified). If users are writing against the API directly, then they must switch through pages themselves to get all results.
Internal ListRequests can pass in `nil` to avoid pagination. Pre-existing calls now pass in `nil` instead of `&models.Pagination{}`.

maintain: paginate in api by default

---

internal/server/middleware.go
internal/server/middleware_test.go
internal/server/routes.go

I've been trying to tackle a few large problems at the same time, but keep ending up with a change that is too big. This is my third attempt at this. The change in this PR is not really that interesting, it's just a refactor, but I believe it should help me make progress on some other problems (separate txn for middleware, passing DB into access functions, removing state from the API struct, etc).
This PR refactors the two middleware that were used for authenticated endpoints. It converts both to regular functions that return errors. Those two functions are then combined in a single smaller middleware.
Best viewed with [Hide Whitespace](https://github.com/infrahq/infra/pull/2700/files?w=1).
Related to https://github.com/infrahq/internal/issues/19, …

api: combine the two authenticated middleware

---

go.mod
go.sum
internal/server/data/migrations.go
internal/server/data/migrator/LICENSE
internal/server/data/migrator/migrator.go
internal/server/data/migrator/migrator_test.go

Today we use `gormigrate` to manage our database migrations. It works well, but we have a couple problems:
1. it requires `gorm.DB`, so if we ever want to replace `gorm` we'll have to replace `gormigrate` as well. The core logic for running migrations is pretty trivial, barely 50 lines. So we don't need a big complex framework for migrations. The logic in `gormigrate` is quite reasonable, so by forking this library we can keep the small bit we need, while changing the interface used to implement a migration.
2. we have a somewhat unique requirement for loading the data key out of the database. On a fresh install this has to happen after initializing the schema, but on an upgrade it must happen before running migrations (in case we need the key as part of one of the migrations).  To handle …

Replace gormigrate with a local forked and reduced copy

---

helm/charts/infra/Chart.yaml
helm/charts/infra/values.yaml

- Update helm chart to 0.14.2
- change default podSecurityContext to set fsGroup
- set securityContext runAsUser & runAsGroup by default to match dockerfile.
Resolves [#2740]

fix(helm): Change default podSecurityContext & securityContext

---

internal/cmd/login.go

Before:
```
$ infra login
? Select a server: [Use arrows to move, type to filter]
> localhost
$ infra login
? Select a server: localhost
? Select a login method: [Use arrows to move, type to filter]
> Login with username and password
```
After:
```
$ infra login
? Select a server: [Use arrows to move, type to filter]
> localhost
$ infra login
? Select a server: localhost
? Username: 
```
Resolves #2636

feat: do not prompt list of login methods if no providers are connected

---

helm/charts/infra/templates/connector/configmap.yaml
helm/charts/infra/templates/connector/deployment.yaml
helm/charts/infra/templates/server/configmap.yaml
helm/charts/infra/templates/server/deployment.yaml
helm/charts/infra/values.yaml
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/connector/connector.go

Allow the bind addresses for server and connector to be configured through Helm.
Set a default bind address such that the pod can be run without additional privileges for binding to sub-1024 ports.
Resolves #2737

feat(helm): bind services to non-privileged port ranges

---

api/group.go
internal/server/data/group.go
internal/server/groups_test.go
internal/server/models/group.go
internal/server/testdata/openapi3.json

Adds totalUsers (a count of users in a group) by counting from the identities_groups join table for use in the API/CLI.
Resolves #2672

feat(api): add totalUsers to groups endpoint

---

Makefile

I've been using something like this to start postgres in a container for running tests. I thought it might be useful for others.
You can use it by first running `make postgres`, then copying the `export ...` line it prints and running that command. If you use some kind of `.env` loader then you can add a file that sets it always. If you use an IDE to run tests you'll have to set that env var in the IDE.
The container is named `postgres-dev`, so it will fail to start multiple containers. You'd have to `docker rm -f postgres-dev` to remove the old container before starting a new one. You shouldn't need to start a new container very often. The tests cleanup the namespace after reach test run, so the same postgres instance can be re-used for as long as you want.
The container runs with the …

makefile: add command to start postgres for testing

---

internal/logging/logger.go
internal/server/providers/oidc.go

I just had a hard time debugging a problem with this error message in the debug logs. Moving the log to trace level with some extra context because an error here is expected and means things are working correctly.

maintain: move expected error to trace level

---

internal/access/grant.go
internal/access/organization.go
internal/access/signup.go
internal/server/grants_test.go
internal/server/handlers_test.go
internal/server/models/grant.go
internal/server/organizations_test.go

Add a support admin role which is separate from the admin role. This role is specifically for:
* performing CRUD operations on organizations (a normal admin shouldn't be able to do this)
* granting support admin access
This change additionally assigns the org permission on signup, although that will change when the signup endpoint morphs to allow users to create new organizations. It does not add the role for existing admins, since it's difficult to know who to assign the permission to.
Also in this change is a cleanup of the CreateGrant unit test to make it more straight forward, and the Organizations unit tests to remove some unnecessary code.

feat: add infra support admin user

---

internal/access/access_key.go
internal/access/credential.go
internal/access/identity.go
internal/access/request.go
internal/access/signup_test.go
internal/access/token.go
internal/server/cookie.go
internal/server/handlers.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/routes.go

This PR also introduces a new `RequestContext` struct. I'd like to use this new type to limit our exposure to `gin.Context` (https://github.com/infrahq/internal/issues/19). We should be able to store other things on this context that we currently get from the API struct (Telemetry, server.Options, the ID of the infra provider, Org, etc). The `RequestContext` is used in one endpoint.
This PR replaces the `currentAccessKey` function with data from the `RequestContext`, and starts to replace `AuthenticatedIdentity` as well.
At the same time I noticed that our `SetCookie` operations were using a `gin.Context` helper. This helper provides no additional functionality over the stdlib function, and actually makes the call site harder to read because of the lack of struct keys.  So I removed the …

api: Introduce RequestContext, and reduce use of gin.Context

---

internal/server/data/data.go
internal/server/data/migrations.go
internal/server/data/migrator/migrator.go

Branched from #2722
Pass `loadKey` to migrator so that we don't have to duplicate some of the "has schema been intialized" logic.
Resolves #2066

Integrate loadKey with init schema

---

helm/charts/infra/templates/server/configmap.yaml

Server configmap uses the wrong value to template proxyURL

fix(helm): server.config.ui.proxyURL

---

internal/server/data/data.go
internal/server/data/data_test.go

- postgres db transaction needs to be rolled back on failure or it can't be re-used to make other database requests
Postgres was failing with an internal server error on duplicate grant creation. The reason for this is that Postgres closes the DB transaction on error, but we would then attempt to read the existing grant on the same transaction.
Fix (as suggested by Steven) is to rollback the failed query in the case of a postgres database. 
This replaces the previous PR for the same issue: #2658 
Resolves #2652

fix: rollback postgres db transaction on fail

---

docs/reference/cli-reference.md
internal/cmd/cmd.go
internal/cmd/completion.go

Adds shell completion using the [default code provided by cobra](https://github.com/spf13/cobra/blob/main/shell_completions.md) which adds static completion of commands. Dynamic completion could be added if wanted.
Note, the command couldn't be auto-generated in order to add it to the `Other commands` group.
Resolves #252

feat: `infra` shell completion

---

docs/identity-providers/google.md

in the google identity provider docs
Signed-off-by: Matthew Williams <m@technovangelist.com>
Resolves #

fix: google instructions missing a step towards the end

---

docs/reference/cli-reference.md
internal/cmd/groups.go

In order to prevent clutter when running infra groups list, this change limits the number of users displayed for each group (by default 8). For this reason, I also added a `COUNT` column so users can easily see how many users are in a group.
The change also adds two flags: `--no-truncate`, which keeps the old behavior and `--num-users` which changes the limit.
https://github.com/infrahq/infra/pull/2767 should be merged in the same release in order to fix the `COUNT` field. We also should consider adding an easy way to list all users in a group (i.e. `infra users list --group Engineering`)
Resolves #2762

feat: truncate users in `infra groups list`

---

internal/server/middleware.go

I'm not sure how this middleware is working without this. I guess maybe none of the unauthenticated routes use the new `RequestContext`, so it's silently doing nothing?
This started failing tests when I added more things to this middleware, and adding the `c.Next` fixed it. 
Not sure how to reproduce with a test with the current code.

fix: add missing middleware next

---

internal/server/authn/oidc_test.go

Noticed this a few times while reading over the code. Using a struct removes the need to cast to the function type.

maintain: update a test to use a struct instead of map

---

api/organization.go
internal/server/testdata/openapi3.json

To be consistent with (most) other names in our API.

api: Validate org name using ValidateName

---

helm/charts/infra/templates/NOTES.txt

Instructions for ClusterIP infra-server port-forward does not reference the ports configured by the server.

fix(helm): use config http(s) addrs

---

internal/access/identity.go
internal/access/identity_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go

Deleted users were still showing up in the `identities_groups` table, as though they still had group membership. This caused `group.UserCount` to be off.
This change removes users from all groups on user deletion and adds a migration to remove previously deleted users from groups.
Resolves #2766

fix: remove deleted identities from identities_groups

---

internal/server/data/migrations.go
internal/server/data/migrations_test.go

I extracted this fix from #2804 so it can be reviewed directly.
This was a bug in one of our existing migrations. I guess we never noticed because we ignored the error. The test that was added in #2804 noticed the problem. The thing being removed is an index, not a constraint.
I fixed this in place, but changed the name of the migration. This will act like a new migration and run for everyone. But it should check if the index exists first, so it will be a no-op for anyone who doesn't have this index.
I'll cherry-pick this fix back into #2804 which has test coverage for it.

fix: data migration of group index name

---

internal/server/models/types.go
internal/server/models/types_test.go

This PR removes an unused and untested type from `models`, and adds a safeguard to `CommaSeparatedStrings` to prevent saving a value to the database that we won't be able to retrieve later.
The other options presented in #2068 would be nice, but will require database migrations for a bunch of fields, so is a lot more work. This safeguard is sufficient to prevent problems until we invest in one of the more involved solutions.
Related to #2068, but we might want to keep that open in case we do want to support commas in values at some point.

data: add safeguard for comma separated strings

---

internal/access/settings.go
internal/server/authn_test.go
internal/server/handlers.go
internal/server/handlers_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/passwordreset_test.go
internal/server/routes.go
internal/server/server_test.go
internal/server/users_test.go

This PR consolidates `DatabaseMiddleware` into the existing `authenticatedMiddleware` and `unauthenticatedMiddleware`. This removes the need for these middleware to fetch the txn from `gin.Context`, they can use the txn directly.
This is the first step to fixing #2697. We'll need to do one of the following next, both of which require this change. Either we
1. use one txn for middleware, and a separate one for handlers. The txn for handlers would be managed from `wrappedHandler`.  This is my preference because it allows us to use different read modes, and isolation modes for the middleware and the handler.
2. use a single txn for both middleware and handlers, which would require moving the `(un)authenticatedMiddleware` into `wrappedHandler`. I think integrating those two is nice either …

api: consolidate DatabaseMiddleware into other middleware

---

.github/workflows/fuzz.yaml

Looks like I missed this in #2631. I've been trying to figure out why the fuzz cache isn't working. I think it's two problems:
1. The `setup-go` action does restore a cache, but it only re-saves the cache when we update dependencies. So most of the time the fuzzer will redo work it's already done.
2. The `actions/cache` I added was not working. I just noticed that in the "Post Run" it says 
> Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
This PR should fix that problem by using the correct path.
With this change it looks to be working
> Cache saved with key: go-fuzz-corpus-FuzzID_MarshalText_RoundTrip_FromInt64-374

ci: fix path for go fuzz cache

---

internal/access/access_test.go
internal/access/signup.go
internal/server/authn/authn_method_test.go
internal/server/authn/oidc.go
internal/server/config.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/organization.go
internal/server/groups_test.go
internal/server/middleware.go
internal/server/organizations_test.go

- appease the lint gods
Should use a unique context key for the org db context rather than a string to ensure uniqueness.

fix: use unique org db context key

---

internal/server/data/data_test.go

`db.Create()` doesn't add the org ID, which was getting by-passed in a pagination test. This change switches it out to use `add()` instead.

maintain: fix data test

---

go.mod
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/testdata/migrations/202204281130-postgres.sql
internal/server/models/access_key.go
internal/server/models/destination.go
internal/server/models/organization.go
internal/server/models/provider.go
internal/server/models/provideruser.go

This PR removes the second call to gorm.AutoMigrate, and adds a test to show that the initial schema matches the migrated schema.
From now on all migrations must be explicit, no more auto-creating of columns or constraints using AutoMigrate.
The migration test is updated to dump both the initial schema and the migrated schema, to ensure that they match.
Removing this extra call to AutoMigrate required making a few changes:
* Add migrations that were previously done implicitly by the calls to AutoMigrate.
* For some reason the schema file we use for migrations has composite primary keys and columns in a different order from the initial schema. I guess gorm.AutoMigrate changes the order based on something in the code. I attempted to re-order the list of tables in `initializeSchema` many …

Add a test case to show that initial schema matches a migrated schema

---

internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/migrator/helpers.go
internal/server/data/migrator/migrator.go
internal/server/data/migrator/migrator_test.go

`gorm.Migrator` (not to be confused with `gormigrate` which we already replaced) provides helper functions for inspecting and changing the schema.
This PR replaces calls to those helpers with regular SQL. In a couple cases (`HasTable`, `HasColumn`) I added a helper function to the `data/migrator` package, because these two require inspecting the informational schema and are a bit more involved.
This PR keeps sqlite support by writing the equivalent sqlite queries (which are not much different), but it is important to note that the sqlite versions of a couple of these are not idempotent.
The only remaining use of `gorm.Migrator` is `AutoMigrate`, which will be replaced next.
Related to #2768

Replace gorm.Migrator calls with sql

---

internal/access/access_test.go
internal/cmd/list_test.go
internal/cmd/login_test.go
internal/server/access_keys_test.go
internal/server/authn/authn_method_test.go
internal/server/authn/key_exchange_test.go
internal/server/authn/oidc_test.go
internal/server/authn/password_credentials_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/destination_test.go
internal/server/data/migrations_test.go
internal/server/middleware_test.go
internal/server/server.go
internal/testing/database/postgres.go

Each test package needs to use a different schema name because `go test` will run tests for different packages in parallel. Since all packages can use the same PostgreSQL DB server they have to target different schemas. 
For some reason the `cmd` tests also seem to overlap, and I'm not sure why. It's possible the server processes keep running after the test ends, but logging suggests this isn't the case. For now I've worked around that by using a different schema name for each test function in `cmd`.
Best viewed by individual commit
Test failures included:

Support running all tests against postgres

---

api/pagination.go
internal/server/users_test.go
ui/pages/destinations/index.js
ui/pages/groups/index.js
ui/pages/providers/index.js
ui/pages/users/index.js

While pagination wasn't default/mandatory, all fields in the PaginationResponse used `omitempty`. 
However, this is no longer necessary and can cause bugs/unexpected behavior when the `totalPage` field is undefined instead of 0. This 'bug' was still present when writing pagination for the UI, but the defaults are no longer necessary.
Resolves #

maintain: remove PaginationResponse omitemptys

---

internal/access/access_test.go
internal/access/credential_test.go
internal/server/data/data_test.go

Instead of updating the already existing settings, a couple of the access tests were trying to create a new set of settings which caused issues.

Org collab fixaccesstests

---

ui/components/grant-form.js
ui/lib/admin.js
ui/pages/destinations/index.js
ui/pages/groups/add.js
ui/pages/groups/index.js
ui/pages/login/index.js
ui/pages/settings/index.js
ui/pages/users/index.js

While new designs/pagination implementations are being made for https://github.com/infrahq/infra/issues/2826 the item count is currently capped at 100 by default. This changes the limit to the first 1000, which is a less likely cap to run into.

maintain(ui): increase limits to max temporarily

---

.github/workflows/cd-core.yaml
.github/workflows/cd-helm.yaml
.github/workflows/cd-ui.yaml

The workflow previously consisted of two jobs. During refactoring this was consolidated into a single job but there were side effects. The main side effect is the build artifacts are no longer in the root directory. Instead of continuing with a single job, use two jobs.

fix(build): helm build/release is not able to publish artifacts

---

.github/workflows/cd-core.yaml
.github/workflows/cd-helm.yaml

helm package is creating artifacts in `helm/`, not `helm/charts/` so upload that path instead

fix(cd): helm artifact path

---

api/client.go
api/user.go
internal/access/identity.go
internal/access/identity_test.go
internal/server/testdata/openapi3.json
internal/server/users.go
internal/server/users_test.go
ui/components/grant-form.js
ui/pages/destinations/add.js
ui/pages/groups/add.js
ui/pages/groups/index.js
ui/pages/users/index.js

Currently the connector shows up in the user list. Although the connector is technically a user, it's not really useful for users to see it as it's mostly internal and we've considered changing the architecture altogether (see https://github.com/infrahq/infra/issues/2238). 
This also prevents pagination issues with the UI (as it was hiding the connector and displaying the wrong item count) and makes the UI and CLI consistent.
I checked for cases where we'd need to enable `showSystem`, but if I missed any use cases where the connector needs to be shown, please let me know.
Resolves #2733

feat(api): hide connector by default through showSystem query parameter

---

internal/access/access_test.go
internal/access/credential_test.go
internal/access/passwordreset_test.go
internal/access/signup.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/migrator/migrator.go
internal/server/data/migrator/migrator_test.go
internal/server/data/organization.go
internal/server/data/passwordresettoken.go
internal/server/data/schema.sql
internal/server/data/selectors.go
internal/server/metrics.go
internal/server/models/access_key.go
internal/server/models/credential.go
internal/server/models/destination.go
internal/server/models/grant.go
internal/server/models/group.go
internal/server/models/identity.go
internal/server/models/organization.go
internal/server/models/passwordresettoken.go
internal/server/models/provider.go
internal/server/models/settings.go
internal/server/telemetry.go

This PR cherry-picks 501cd0dd1e0b574c5aa1c8fa2ad9146b88543946,  the data parts of 02cd02c941d9cd016575cb05057285e958cdf9c3, and a bit of 0d1faf9fc40c5c0911fed950b80d18d1cd062178 for merging into main. Best viewed by individual commit.
I made a few changes as well:
* use interfaces instead of reflection for working with models
* use easier to read migration IDs, we started using these recently for new migraiotns
* use single statements for migrations
* remove double quotes from queries, and use caps consistently for sql keywords
* make the selector `ByOrgID` instead of `ByOrg`
* move the OrganizationID to an `OrganizationMember` so that tables that don't use it don't receive an org_id
* continue to require not-null for primary keys
* cascade the deletes of sequences to remove the other …

Add organization ID, and remove FKs and sequences

---

internal/access/access_test.go
internal/access/signup_test.go
internal/server/authn/authn_method_test.go
internal/server/authn/oidc_test.go
internal/server/authn_test.go
internal/server/config_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/organization.go
internal/server/data/settings.go
internal/server/data/settings_test.go
internal/server/groups_test.go
internal/server/handlers_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/models/organization.go
internal/server/organizations_test.go
internal/server/passwordreset_test.go
internal/server/server.go
internal/server/server_test.go
internal/server/users_test.go
pki/certificates_ext_test.go
pki/native_test.go

Branched from #2896
Adds the default org as a migration, and migrates existing data to the org.
For new installs and in tests the default org, settings, and infra provider are created by `NewDB`.

Add default organization

---

internal/server/server.go

Avoids these annoying things by only binding to the local network device by default (tests use the default), not internet-facing ones.

fix: avoid annoying mac port warning running tests

---

internal/server/handlers.go
internal/server/providers_test.go
internal/server/tokens_test.go

Moving this check for the provider sync fixes a bug where issuing an access key directly to a user from an identity provider did not work. Also added test coverage to the `/tokens` endpoint. 
Resolves #2895

fix: allow direct access key for idp user

---

api/client.go
api/grant.go
api/user.go
internal/access/grant.go
internal/server/data/selectors.go
internal/server/grants.go
internal/server/grants_test.go
internal/server/testdata/openapi3.json

This is a natural continuation of this issue https://github.com/infrahq/infra/pull/2892, which was also causing a bug with the `infra grants list` command.
Resolves #2909

fix: hide connector grants

---

.github/workflows/cd-helm.yaml
.github/workflows/deploy.yaml

Minor change to the deploy workflow to add concurrency controls for individual components. A deploy for `core` should not override/block deploys for `ui`

improve: add component concurrency controls

---

internal/cmd/agent.go
internal/cmd/cmd.go
internal/cmd/list.go

As part of #2875, this pr gets the resources that the user has access to as dynamic completion nouns. I've tested this myself, and it's a little slow because it has to make an api call, but it's convenient and it works.
I also update the list command to use `listAll()`

feat: completions for `infra use`

---

docker-compose.dev.yaml
internal/connector/connector.go
internal/server/data/data.go

- under load of more than one parallel connection, gorm is not reusing db connections and closing them immediately after each query, The `SetMaxIdleConns` value defaults to 2, so after 2 connections it starts closing idle connections immediately. This creates a lot of overhead. 
- also increases the connector poll time to 30s instead of 5s
tested manually and resolves the issue.

fix: reuse connections with a properly-sized connection pool

---

docs/reference/cli-reference.md
internal/cmd/completion.go

**CLI**
```% deb completion --help
To load completions:
Bash:
$ source <(infra completion bash)
$ infra completion bash > /etc/bash_completion.d/infra
$ infra completion bash > /usr/local/etc/bash_completion.d/infra
Zsh:
$ echo "autoload -U compinit; compinit" >> ~/.zshrc
$ infra completion zsh > "${fpath[1]}/_infra"
fish:
$ infra completion fish | source
$ infra completion fish > ~/.config/fish/completions/infra.fish
PowerShell:
PS> infra completion powershell | Out-String | Invoke-Expression
PS> infra completion powershell > infra.ps1
Usage:
infra completion
Global Flags:
--help               Display help
--log-level string   Show logs when running the command [error, warn, info, debug] (default "info")
```
Docs:
Resolves #2927

improve: fixes docs for cli completion cmd

---

helm/charts/infra/templates/server/configmap.yaml
helm/charts/infra/templates/server/deployment.yaml
helm/charts/infra/templates/server/secret.yaml

When creating a server deployment, if a DB encryption key isn't supplied, create one as a kubernetes secret and mount it into the server pod. This is nicer than the existing default which is to create an encryption key in the pod itself which is only persisted if the key is in the path of a PVC.
It removes a dependency on PVCs. Once this is merged, the only remaining dependency is the database.
Note: This is a _breaking change_ since it discards the previous encryption. Manual steps are required to ensure the continued viability of the data.
Before attempting an upgrade from <=0.14.x, follow the steps below to migrate the encryption key if using Helm release name `infra` and namespaces `infrahq`:
```
$ ENCRYPTION_KEY=$(mktemp)
$ kubectl -n infrahq exec -i deployment/infra-server -- cat …
```

feat: create and mount db encryption key

---

docs/reference/cli-reference.md
internal/cmd/login.go

Users have requested being able to run `infra login` and get logged in without the survey prompts. One could already set the `INFRA_SERVER` env var to skip server selection. This PR adds the `INFRA_PROVIDER` and cli docs to make it more clear. It also uses local login if the provider is `"infra"`
Resolves #2758

improve: skip server selection and update docs for auto-login

---

main.go

Adds a formal error message (along with the actual error) for cert mismatching the server.  
Resolves #2898

improve: better error message for cert mismatch

---

.github/workflows/cd-helm.yaml

`inputs.override-chart` is empty if the workflow is invoked by something other than a `workflow_dispatch` which will erroneously override the previous chart

fix(helm): default false to overriding old chart

---

docs/dev/organization-request-flow.md
internal/access/signup.go
internal/access/signup_test.go
internal/cmd/login.go
internal/cmd/server.go
internal/server/config_test.go
internal/server/data/access_key.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/organization.go
internal/server/data/settings.go
internal/server/debug.go
internal/server/debug_test.go
internal/server/handlers.go
internal/server/handlers_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/migrations.go
internal/server/models/organization.go
internal/server/organizations.go
internal/server/organizations_test.go
internal/server/routes.go
internal/server/server.go
internal/server/tls.go
internal/server/tokens_test.go

fix: checking hosts properly

---

internal/access/access_test.go
internal/cmd/login_test.go
internal/server/authn/authn_method_test.go
internal/server/data/data_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/server_test.go
internal/testing/database/postgres.go

Best viewed by individual commit. I can remove any of these commits if there are concerns. I noticed a few other problems while working on this fix.
Fixes:
* permission required for the debug endpoint
* reading host header from the request, apparently some proxies remove the host header, so we have to use `req.Host`. The consequence of this change is that we no longer have a case where this is no host header. We plan on changing this later, and it is tracked in #2903 (second last item in the list currently).
* the postgres test helper so that `TestServerRun` uses postgres
* the wrong database connection was being used in the middleware
Closes #2925

Fix reading the domain from the request

---

internal/server/access_keys_test.go
internal/server/config_test.go
internal/server/debug_test.go
internal/server/grants_test.go
internal/server/groups_test.go
internal/server/login_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/organizations_test.go
internal/server/passwordreset_test.go
internal/server/providers_test.go
internal/server/server.go
internal/server/server_test.go
internal/server/tokens_test.go
internal/server/users_test.go

`dataDB` was added temporarily to expose more data from NewDB. This commit replaces most access of Server.db with a call to `Server.DB()`. A function should make it easier to migrate code away from gorm without having to change all of these call sites again.
Resolves [this TODO](https://github.com/infrahq/infra/pull/2911#discussion_r943752984) from #2911

Remove the second DB field from server

---

internal/access/credential_test.go
internal/access/passwordreset_test.go
internal/server/access_keys_test.go
internal/server/data/data.go
internal/server/data/settings.go

Cleanup a couple things from #2902
* We don't need these calls to `SaveSettings` anymore, it's always done by `NewDB`
* It's risky to set an org in the context in `NewDB` because of how gorm clones the context. So add a new function that lets us pass the org explicitly in this case.
Related to #2903

Make NewDB safer by not setting an org in the context

---

internal/server/data/migrations.go
internal/server/data/migrator/helpers.go
internal/server/data/migrator/helpers_test.go
internal/server/data/migrator/migrator_test.go
internal/server/data/schema.sql
internal/server/models/encryption_test.go

Branched from #2845
This PR replaces the last of the calls to `gorm.AutoMigrate` and `gorm.Migrator`. The only remaining calls to `gorm.AutoMigrate` are in a function we are using for sqlite compatibility, and to catch any new implicit migrations that might be added from other PRs.  I'm thinking of leaving those in until this merges (to catch problems during merge and rebase), and removing it immediately in a follow up.
Resolves #2768

Replace the last of AutoMigrate

---

internal/server/authn/authn_method.go
internal/server/authn/key_exchange.go
internal/server/authn/key_exchange_test.go
internal/server/authn/oidc.go
internal/server/authn/oidc_test.go
internal/server/authn/password_credentials.go
internal/server/authn/password_credentials_test.go
internal/server/handlers.go

- set key expiry to match exchanged key if exchanged key is valid for less than default session
- return AuthenticatedIdentity struct from authn rather than many separate values
Fixing this now because our ArgoCD automation is using this flow.
This change fixes the key exchange login flow to work as long as your access key is valid. When the expiry time of the access key being passed in is less than the server's default session duration, set the new key to match the expiry of the one being exchanged rather than failing.
Resolves #2640

fix: set key expiry during exchance

---

.github/workflows/cd-core.yaml
.github/workflows/ci-core.yaml
.github/workflows/fuzz.yaml
.golangci.yml
CONTRIBUTING.md
Dockerfile
Dockerfile.dev
internal/cmd/cliopts/config.go
internal/server/data/migrator/migrator.go
internal/server/middleware_test.go
internal/server/models/grant.go
internal/server/openapi_test.go
internal/testing/patch/patch.go
metrics/metrics.go

Required running `gofmt` again because it changed in go1.19.
Everyone will need to upgrade `golangci-lint` to 1.48.0

Try go1.19

---

internal/server/config_test.go
internal/server/data/migrations_test.go
internal/server/data/provider_test.go

- Remove domains that may be called externally in the case of a bad test configuration
- Remove migration test that makes external call
Resolves #2949

fix: do not make external API calls in tests

---

internal/access/access_test.go
internal/cmd/users.go
internal/server/data/data_test.go
internal/server/data/identity_test.go
internal/server/data/organization.go
internal/server/testdata/TestMetrics/infra_users

When an org signs up they need a connector identity to start adding destinations. Create it by default.
Tests dependent on #2952 
Resolves #2946

fix: create connector identity for org

---

internal/server/data/migrations.go
internal/server/data/migrations_test.go

Test that existing rows get properly migrated to point at the default org ID.
Change an unreleased migration ID to use the new more readable format.

More test coverage for org ID migration

---

docker-compose.dev.yaml
internal/access/credential.go
internal/cmd/cliopts/config.go
internal/server/config.go
internal/server/data/data.go
internal/server/data/migrations.go
internal/server/data/migrator/migrator.go
internal/server/email/sendgrid.go
internal/server/models/grant.go
internal/server/models/organization.go
internal/server/models/passwordresettoken.go
internal/server/openapi_test.go
internal/server/passwordreset.go
internal/server/passwordreset_test.go
internal/server/routes.go
internal/server/users.go
internal/testing/patch/patch.go
metrics/metrics.go
ui/components/password-reset-form.js
ui/pages/accept-invite/index.js
ui/pages/password-reset/index.js
ui/pages/users/add.js

Invite email

---

helm/charts/infra/templates/server/deployment.yaml

There's little reason to check if the postgres connection is ready when using an external postgres instance. Checking significantly complicates the configuration since the database can be configured through both config values or environment variables

fix: only check postgres pod if deploy it as part of the chart

---

internal/server/data/organization.go
internal/server/testdata/TestMetrics/infra_grants

When creating a connector for a new org that connector identity also needs to be given a connector grant to be able to add destinations.
I'll add a test for this in #2952 
Resolves #2946

fix: grant the org connector role

---

internal/access/organization.go
internal/access/signup.go
internal/server/data/data.go
internal/server/data/organization.go
internal/server/data/organization_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/organizations_test.go

- rename CreateOrganization to reflect its functionality
- remove unneeded db statement context setting
- do not set db context in middleware test
- remove the "set default org" from setupDB in server (and other) packages
Cleaning up some org creation and context setting. 
Part of #2903

maintain: clean up org db context setting

---

helm/charts/infra/templates/server/deployment.yaml

Fixing an issue with the Helm chart when server.persistence is enabled where the env value is not a string

fix(helm): quote integer value

---

helm/charts/infra/templates/server/prometheusrule.yaml

Increase the threshold where alerts fire to 5s instead of 300ms.

maintain: tune prometheus latency rule

---

internal/access/passwordreset.go
internal/access/passwordreset_test.go
internal/errors.go
internal/server/data/passwordresettoken.go
internal/server/errors.go
internal/server/passwordreset.go
internal/server/users.go

- extend invite expiry time
- better error message on expired invite token
- retry on generated token existing already (super unlikely)

improve: extend invite expiry time

---

.github/workflows/deploy.yaml

Add a notice after computing the component name to inform users which component the workflow run will deploy. Update annotations to `ci.infrahq.com`

improve: output component for workflow run

---

api/organization.go
api/signup.go
internal/access/organization.go
internal/access/signup.go
internal/server/errors.go
internal/server/handlers.go
internal/server/models/organization.go
internal/server/organizations.go
internal/server/organizations_test.go
internal/server/server_test.go
internal/server/signup_test.go
internal/server/testdata/openapi3.json
ui/__test__/signup.test.js
ui/pages/signup/index.js

When a new organization signs up or is created by a support admin it should be possible to specify the org's subdomain or domain directly.
- Allow specifying your organization's sub-domain on sign-up.
- Allow support admins to directly specify an organization's full domain through the API. This may be useful as an admin workaround if we need a special domain. This is not a normal action.
- Update the UI for specified organization domains.
- Parse root errors from conflict error message trace for better error display.
Resolves #2956

feat: allow specified org domain on sign up

---

internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/metrics.go
internal/server/testdata/TestMetrics/infra_providers
internal/server/testdata/TestMetrics/infra_users

Exclude internal resources like the connector identity and privilege from metrics

fix: exclude builtin users and providers from metrics

---

docs/dev/organization-request-flow.md
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/routes.go
internal/server/server.go
internal/server/server_test.go

Implemented the linked proposal by allowing access key to specify the org ID for unauthenticated endpoints.
Also:
* removes the unused `Infra-Organization` header, which is no longer safe now that org name is not unique
* fixes a TODO about using a transaction for a db query
* adds some godoc for the `SignupEnabled` server option
Making this a draft until I have written tests to cover all the cases.
Resolves https://github.com/infrahq/internal/issues/23

Accept Org ID from access key for unauthenticated endpoints

---

internal/access/access_test.go
internal/cmd/login_test.go
internal/openapigen/main.go
internal/server/access_keys_test.go
internal/server/authn/authn_method_test.go
internal/server/authn_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/debug_test.go
internal/server/destination_test.go
internal/server/grants_test.go
internal/server/groups_test.go
internal/server/handlers_test.go
internal/server/login_test.go
internal/server/middleware_test.go
internal/server/openapi_test.go
internal/server/organizations_test.go
internal/server/passwordreset_test.go
internal/server/providers_test.go
internal/server/routes.go
internal/server/routes_test.go
internal/server/server.go
internal/server/server_test.go
internal/server/signup_test.go
internal/server/tokens_test.go
internal/server/users_test.go

This PR:
* refactors the `TestRequireAccessKey` test case to use a `testCase` struct, removing the need to cast the `interface{}` to a function
* removes the `prometheus.Registry` arg from `Server.GenerateRoutes`. We call this in many tests, and it can receive the registry from a field on the server
* remove `data.InvalidateCache`, which was used in tests, but we removed the caches in a previous commit, so we no longer need to invalidate them. In the future if we want to cache these references we can use the `data.DB` struct which is different for each test, so we shouldn't need to invalidate the cache.

Refactor a test function and remove a test helper

---

internal/server/data/data.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/migrator/helpers.go
internal/server/data/migrator/helpers_test.go
internal/server/data/migrator/migrator.go
internal/server/data/migrator/migrator_test.go
internal/server/models/encryption_test.go

Previously the `data/migrator` used `gorm.DB` to perform queries. This PR changes it to accept an interface that closely resembles the interface provided by the stdlib. The only difference from the stdlib is a `DriverName` method. That extra method should be easy to implement by checking the type of the driver, or we may decide to remove sqlite support and remove the need for that method.
This change is done first before converting the query functions because `migrator` is a separate package which `data` depends on. So it has to be converted first.
This PR also removes the `UseTransaction` option from the migrator. We were not using this option, and it made it more difficult to accept an interface. In the future if we want to use a transaction for applying migrations we can manage the …

Remove gorm from the migrator

---

internal/openapigen/main.go
internal/server/openapi.go

The metricsReigstry field is not exported, so we can't set it on the
server.
Instead expose a method that returns just the document, so that we can
call it from the command.

fix: openapi doc generation command

---

.github/workflows/cd-containers.yaml

The output references an unknown step which means the output is an empty string. TIt's a problem for the UI build because the context is not the root directory

fix(build): bad step name in ui build

---

internal/access/access.go
internal/access/access_test.go
internal/access/signup_test.go
internal/server/handlers_test.go
internal/server/middleware.go
internal/server/middleware_test.go

Related to #3008, although merging this may cause some small conflicts with that PR.
This PR removes the `gorm.DB` reference from `gin.Context`, and ensures we always get the DB from our `RequestContext`. This will make it possible for us to add metadata to a Transaction struct directly, without having to use the gorm.DB context.

Remove db from gin context

---

internal/server/config_test.go
internal/server/data/organization.go
internal/server/data/organization_test.go
internal/server/grants_test.go
internal/server/testdata/TestMetrics/infra_grants

- specify default org in config tests to verify that expected results are returned
- connector was issued the wrong grant on org creation
Update config test queries to query specifically for the default org ID we expect. This revealed a bug where the default org connector was getting the wrong grant, which I have also corrected in this PR.
Resolves #2917

maintain: update config tests for orgs

---

helm/charts/infra/templates/postgres/_helpers.tpl

This fixes the case where postgres is enabled when only connector is enabled

fix(helm): use helper to check if server enabled

---

Makefile

individually set image checksums otherwise a server change will trigger a new ui pod or vice versa. global.podAnnotations also applies to the postgres pod which incorrectly causes it to restart

maintain(dev): individual image checksums

---

internal/logging/middleware.go

When the server is behind a load balancer or ingress, the remote addr is
often an intermediate address instead of the real address. It can be
tedious to get the real address since there's multiple values to
check. Fortunately, gin has `c.ClientIP()` which does the work for us.

maintain: log real client IP

---

helm/charts/infra/templates/postgres/statefulset.yaml

Also only apply credentials changes if the credentials table is created. This prevents a pod restart when postgres comes up where there is no migration from SQLite

fix: only migrate sqlite db if it exists

---

Makefile

It's possible some values in `make dev` are interpreted by Helm as numbers rather than string which will break Helm since fields such as annotations require a string value. Use `--set-string` instead of just `--set` so the value passed to Helm will always be interpreted as a string.
Resolves #3061

fix(dev): force set Helm string value

---

internal/server/middleware.go
internal/server/middleware_test.go

If a user has an `auth` cookie for the base Infra domain or an old org that had the same domain it will get sent to the server along with the `signup` cookie. The `signup` cookie should take priority over this `auth` cookie since it shows that the user is clearly being redirected after creating a new org and no previous auth should exist.

fix: new signup session priority

---

internal/server/handlers.go
internal/server/organizations.go
internal/server/telemetry.go
internal/server/users.go

Add analytics around org membership and signup
Resolves #

improve: better analytics

---

helm/charts/infra/templates/postgres/statefulset.yaml

Typo in SQLite file path prevents migration to Postgres from happening.

fix: typo in db file path

---

internal/server/cookie.go
internal/server/cookie_test.go
internal/server/middleware.go

#3059 had an issue that it wouldn't set the new auth cookie after sign-up because moving around the cookie logic meant that the key wasn't set where I expected it to be previously.

fix: do not use request for signup cookie exchange

---

internal/server/config.go
internal/server/config_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/organization.go
internal/server/models/organization.go

This PR makes the following changes:
* adds a migration to update the default org to use ID=1000. This gives us a reliable way of looking up the default config, without depending on a configuration setting.
* adds a new server option `DefaultOrganizationDomain` that allows someone to set the domain name of the default org as part of the infrastructure-as-code `loadConfig` function.
Fixes #3025

Add option to set the default organization domain from server config

---

api/passwordreset.go
api/signup.go
internal/server/server_test.go
internal/server/signup_test.go
internal/server/testdata/openapi3.json
internal/validate/string.go
internal/validate/string_test.go
internal/validate/validate_test.go

This PR adds validation to the org subdomain, including min/max length, character restrictions, and a list of reserved words that we should not allow to be subdomains.
Best viewed by individual commit, more details in commit messages.

Add validation to org subdomain during signup, and add a list of reserved subdomains.

---

internal/access/organization.go
internal/server/organizations_test.go
internal/server/server.go
internal/server/signup_test.go

With the changes in #3066, all we need to do here is lowercase the string. So we can remove the regex replacement.

Remove regex replacement from org domain generation

---

ui/__test__/login.test.js
ui/components/auth-required.js
ui/components/layouts/dashboard.js
ui/components/layouts/login.js
ui/pages/login/callback.js
ui/pages/login/finish.js
ui/pages/login/index.js

Logged out users who are trying to access authenticated pages will now get redirected to the right destination page after logging in
EG)
original:
- `https://test.infrahq.com/users` -> user logs in -> `https://test.infrahq.com/destinations`
now:
- `https://test.infrahq.com/users` -> redirects to `https://test.infrahq.com/login?next=/users`
-> users login -> `https://test.infrahq.com/users`
Resolves #1670

feat: login redirect

---

api/client.go
internal/cmd/cmd.go
internal/cmd/errors.go
internal/cmd/logout.go
internal/cmd/logout_test.go
internal/connector/connector.go
internal/server/tokens_test.go

Clients (incl connectors) should respect the 401 Unauthorized received from an access token; it's not a transient error and requesting with it in the future will never work.
If the client knows the token is expired it shouldn't bother requesting.

fix: clients should stop requesting when told their token is invalid

---

.github/workflows/cd-containers.yaml

`edge` contains changes from main while `latest` contains changes from the latest tag. `edge` is more applicable in this case. this should speed up the docker image build

improve: cache docker build from edge instead of latest

---

.golangci.yml
go.mod
go.sum
internal/generate/generate.go
internal/server/email/passwordreset.go
internal/server/email/sendgrid.go
internal/server/email/signup.go
internal/server/email/smtp.go
internal/server/email/smtp_test.go
internal/server/email/templates.go
internal/server/email/templates/password-reset.text.html
internal/server/email/templates/password-reset.text.plain
internal/server/email/templates/signup.text.html
internal/server/email/templates/signup.text.plain
internal/server/email/templates/user-invite.text.html
internal/server/email/templates/user-invite.text.plain
internal/server/email/userinvite.go
internal/server/handlers.go
internal/server/passwordreset_test.go
internal/server/server.go

- switches to SMTP for email delivery instead of sendgrid api
- renders email templates locally instead of depending on remote service
- switches existing emails over to new templates
- adds welcome/signup email
also..
Resolves #2971

feat: add welcome signup email

---

helm/charts/infra/templates/postgres/_helpers.tpl
helm/charts/infra/templates/server/secret.yaml

The DB host may also be set with environment variables so try to detect that as well. 
Keep `infra-server-encryption-key` through helm delete. When using an external database, the data does not get deleted when uninstalling the chart. If the encryption key changes, the database cannot be reused. 
https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource

fix(helm): also no postgres if db host set in env

---

.github/workflows/cd-binaries.yaml
.github/workflows/cd-containers.yaml

fix container build to build both `infrahq/infra` and `infrahq/ui` components when not explicitly set. this can happen when triggered by a tag
checkout in binary publish job so `gh` is aware of the repo

fix(build): fix workflows for release

---

.github/workflows/cd-containers.yaml
.github/workflows/cd-helm.yaml

Tag triggers shouldn't try to deploy since 1) it's not allowed to deploy to environments and 2) deployments do not use any tags produced by a tag build.

fix(build): ignore synchronize job if triggered by tag

---

internal/connector/authn.go
internal/connector/connector_test.go

This allows the connector to use any server URL instead of having to use the org specific url.
The test is a bit artificial, but I don't think we have a better way of testing the connector and server interaction at this time.

Send auth header from connector when requesting the jwk

---

api/signup.go
internal/access/signup.go
internal/server/signup_test.go
internal/server/testdata/openapi3.json
internal/validate/string.go
internal/validate/string_test.go
internal/validate/validate_test.go

- update string length api error to be more ui friendly
- validate signup password between 8 and 253 characters
Due to #3076 it was possible it sign-up and fail the password check after your org was created. Leaving the org in a bad state. Move the password requirement check to the API to prevent this.
Also updating the string error message to be more UI friendly.

fix: check signup password requirements in api

---

.github/workflows/cd-containers.yaml
.goreleaser.yml

Add back docker build args. These got lost in refactoring.
Also zero out the `Prerelease` and `Metadata` version parts when building the infra CLI using goreleaser
Resolves #3116

fix: add build-args back to docker image build

---

.github/workflows/cd-containers.yaml

`actions/checkout` defaults to a depth 1 checkout which doesn't have enough information for `git describe --tags` so change to infinite depth (0)

fix(build): need fetch-depth:0 for git tags

---

internal/cmd/destinations.go
internal/cmd/keys.go
internal/cmd/login.go
internal/cmd/users.go
internal/format/format.go
internal/format/format_test.go

This change moves out the human formatter code into its own package so that we can use it in other places, such as when we send emails.

maintain: move the human formatter out to its own package

---

internal/access/access.go
internal/access/access_test.go
internal/access/provideruser.go
internal/access/request.go
internal/access/signup.go
internal/server/config.go
internal/server/cookie_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/handlers_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/tokens_test.go
internal/server/users_test.go

The `data.NewTransaction` constructor is a bit misleading because it does not actually start a transaction. Instead it wraps a `gorm.DB` with our wrapper that implements the stdlib interface.
This PR removes the `NewTransaction` constructor and replaces it with two things:
* a `Transaction.WithOrgID` method for setting the OrgID metadata in the transaction
* a `DB.Begin` method for creating a new transaction.
This changes brings us much closer to the interface provided by the stdlib.
Also remove a couple places we were creating a `RequestContext` unnecessarily in tests.

Replace NewTransaction with a real db transaction

---

internal/server/apimigrator.go
internal/server/apimigrator_test.go
internal/server/debug.go
internal/server/logging_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/migrations.go
internal/server/routes.go
internal/server/routes_test.go

Branched from #3028 this PR cleans up the commits from #3032 to fix both #2697 and #3076  
We had two problems with our request scoped transactions:
1. the transaction was never rolled back on error, it was always comitted
2. we never reported a failure to commit a transaction to the user
This PR addresses the problems by:
* moving the transaction to `wrapRoute`, which has access to the error from both the middleware and the handlers
* in `wrapRoute` add a defer which will rollback if commit has not happened
* and respond with a 500 response code if the transaction fails to commit
Resolves #2697
Resolves #3076

Fix request scoped transactions

---

internal/server/apimigrator.go
internal/server/config.go
internal/server/data/data.go
internal/server/middleware.go
internal/server/routes.go
internal/server/routes_test.go

Branched from #3103
This PR does some cleanup around transactions. Best viewed by individual commit.
1. make `data.Transaction.Rollback` a noop if the transaction was already committed. This makes it possible to defer the rollback, and simplifies the logic where we use transactions.
2. remove `withDBTxn` since it is no longer necessary with the above change.
3. extracts a few small things from `wrapRoute`. This function has grown a lot, moving a few small things out of it helps keep it focused and easy to read.

Make data.Transaction.Rollback a noop if the transaction was already committed

---

go.mod
go.sum
internal/access/access_test.go
internal/cmd/login_test.go
internal/cmd/server.go
internal/cmd/server_test.go
internal/server/authn/authn_method_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrations_test.go
internal/server/data/migrator/migrator_test.go
internal/server/data/sqlfunc_test.go
internal/server/middleware_test.go
internal/server/models/encryption_test.go
internal/server/server.go
internal/server/server_test.go
internal/testing/database/postgres.go

This PR removes sqlite support from both the server and tests.  The server `--dbFile` flag, and config file options will no longer do anything. From now on a postgreSQL database is required to run the server.
In tests, if the `POSTGRESQL_CONNECTION` environment variable is set, the tests will run using that postgres instance. If it's not set in CI the tests will fail. If it's not set outside of CI (local development) any tests that require the database will be skipped.

Remove sqlite support

---

internal/server/server.go
internal/server/server_test.go

Previously the db connection string could either be entirely set by the
`dbConnectionString` option, or the user had to set `dbHost` if they wanted
to use the other options.
With this change the user can set `dbConnectionString` for most options,
and use only `dbPassword` to pull the secret value from a safe place.
This should allow us to deprecate most of the other db options at some point.
It also makes `dbParameters` effectively a duplicate of `dbConnectionString`, so
it would probably make sense to deprecate and remove at least one of those.
Branched from #3084, that will need to merge first.

improve server db connection string options

---

internal/access/access_key.go
internal/access/identity.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/data_test.go
internal/server/data/organization_test.go
internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/data/query.go
internal/server/data/query_test.go
internal/server/data/settings_test.go
internal/server/models/access_key.go
internal/server/models/model.go

Related to #2415, this PR adds the building blocks for creating regular sql queries, and replaces insert and delete access keys with regular sql queries.

Replace delete and insert access key functions with sql

---

internal/access/access_key.go
internal/access/credential.go
internal/access/identity_test.go
internal/access/signup.go
internal/server/authn/authn_method.go
internal/server/config.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/data.go
internal/server/data/pagination.go
internal/server/data/provider_test.go
internal/server/data/query.go
internal/server/data/query_test.go
internal/server/data/selectors.go
internal/server/handlers.go
internal/server/models/access_key.go
internal/server/pagination.go

Branched from #3029, and including the commit from #3093
This PR replaces gorm with sql in the query functions for get, list, and update access keys, and also adds more test coverage for those functions.
The biggest difference is in the pagination, which I'll comment on inline.
Related to https://github.com/infrahq/infra/issues/2415

Replace get, list, and update access key queries with sql

---

internal/server/authn/oidc_test.go
internal/server/data/data.go
internal/server/data/destination.go
internal/server/data/group.go
internal/server/data/identity.go
internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/metrics.go
internal/server/metrics_test.go
internal/server/server.go

Branched from #3094 
This PR removes `GormTxn` from a few functions that were already using regular SQL through the gorm interface. 
Related to https://github.com/infrahq/infra/issues/2415

Remove GormDB from query functions that already used SQL

---

internal/server/data/access_key.go
internal/server/data/access_key_test.go

Set OrganizationID and order by in the query. Update the tests to catch the bug.

fix: list access keys query

---

internal/server/data/settings.go
internal/server/data/token.go
internal/server/models/encryption.go
internal/server/models/encryption_test.go
internal/server/models/settings.go

We had two copies of this type that were almost identical. One for []byte and one for string. Since `string` and `[]byte` are compatible, we can use the same type for both `bytea` and `text` database columns.
I added a test to show this type working with a `bytea` type column. The test was written first, so it also showed that a value serialzied using `EncryptedAtRestBytes` could be later read using `EncryptedAtRest`. This works because the `Value()` method uses the same function to encode the data going into the database.

maintain: use the same encrypted at rest type for both strings and bytes

---

ui/__test__/login.test.js
ui/pages/login/index.js
ui/pages/password-reset/index.js

Set `submitted` state as soon as the submit button is pressed rather than after the request returns.
Also some minor UI issues like
* punctuation
* divider on password reset
* margin between forgot password and login button
Resolves #3114

fix: password reset sending multiple requests

---

helm/charts/infra/Chart.yaml
helm/charts/infra/templates/server/configmap.yaml

- Providing explicit `config.tls` settings will not be rendered in the `infra-server` configmap because "tls" is ommited: https://github.com/infrahq/infra/blob/d87cc531bfa8b3ff3e9bd09a4be54a432a7dd35c/helm/charts/infra/templates/server/configmap.yaml#L10
- I think "ui" should be skipped from generic rendering, as it is already handled some lines below
- To avoid duplicate sections and potentially invalid yaml, added a test for non empty value for any key in `config`

helm chart: fix configmap generation with config.tls not empty

---

api/forgotdomain.go
internal/access/forgotdomain.go
internal/server/data/forgotdomain.go
internal/server/data/forgotdomain_test.go
internal/server/email/forgotdomain.go
internal/server/email/sendgrid.go
internal/server/email/smtp_test.go
internal/server/email/templates/forgot-domain.text.html
internal/server/email/templates/forgot-domain.text.plain
internal/server/forgotdomain.go
internal/server/models/forgotdomain.go
internal/server/routes.go
internal/server/testdata/openapi3.json
ui/pages/forgot-domain/index.js

Provide a UI screen + API endpoint to allow users to recover any domain/org sign-ins that they have previously created. 
It's possible that users may forget how to sign-in to a given org given that we don't support 'at-large' users. In order for a user to sign in, they *must* know the correct domain name. This change allows the user to specify an email address which we will send an email which contains each of the URLs which they can use to sign-in.

Forgot Domains

---

internal/cmd/server.go
internal/cmd/server_test.go
internal/server/middleware_test.go
internal/server/server.go
internal/server/server_test.go
ui/package-lock.json
ui/package.json
ui/pages/destinations/add.js

- Use `api.{baseDomain}` when templating destination add command
- Use values file instead of `--set`
- Use `upgrade --install` instead of `install`
- Make `baseDomain` required when signup is enabled

feat: update destination add to use api endpoint

---

internal/access/access_key.go
internal/access/identity.go
internal/access/provider.go
internal/server/handlers.go

Branched from #3141, this PR makes a similar change.
These functions `InfraProvider`, and `InfraConnectorIdentity` are not providing access. They exist because of the rules we have established for how the data package can be accessed. We can refactor the code slightly to remove the need for these functions by calling the functions in the `data` package directly from `access`.

maintain: remove two access helper functions

---

.golangci.yml
internal/server/data/access_key.go
internal/server/data/data.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/data/pagination.go
internal/server/data/query.go
internal/server/data/querybuilder/builder.go
internal/server/data/selectors.go

Primarily this PR converts `data.CreateGrant` from using gorm to using sql. It includes a few other small changes to reduce conflicts, so best viewed by individual commit.
This PR also:
* moves the query builder into its own package. This was cherry-picked out of #3060 to prevent conflicts. As part of that change the constructor and type name for the query builder have changed.
* adds a transaction around the `NewDB` initialize operations. Not strictly necessary, but a nice to have to ensure that any problems setting up the db are rolled back. 
* adds an exclude rule for `tx.Rollback` so that we can ignore the rollback error. I think generally that error is not going to be relevant.
* adds `handleErr` in `insert` and `update` helpers, which I missed when I added those functions.
Related …

Use SQL for CreateGrant

---

internal/cmd/server.go
internal/cmd/server_test.go
internal/server/logging.go
internal/server/logging_test.go
internal/server/routes.go
internal/server/server.go

Add config value to enable or disable log sampling. It's currently possible to disable log sampling by increasing log verbosity but that may not always be a good idea

feat: toggle log sampling

---

internal/access/grant.go
internal/access/identity.go
internal/server/config.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/data/group.go
internal/server/data/identity.go
internal/server/data/organization_test.go

Converts `GetGrant` and `DeleteGrants` to use sql.
Also changes `columnsForSelect` to accept only the table type. This makes linting easier (no string arg to check), and will make our queries more consistent by always using the table name instead of an alias to qualify field names.
Adds a bunch of tests for both functions.

Use SQL for GetGrant and DeleteGrants

---

helm/charts/infra/Chart.yaml
helm/charts/infra/templates/server/configmap.yaml

https://github.com/infrahq/infra/pull/3153 introduced a change that templates out server config values only if they're truthy but there are cases where a falsy value is valid and should be templated.
Update configmap templates removing some duplication and simplifying some of the templates. The server config contains values that need specially handling. This was previously done by omitting them from the generic templating but this requires coordination between the `omit` and the special handling. Now, the template is structured such that the special handling will remove the key from the map. Due to limitations of Helm templates, this is automatic and still requires some coordination but at least they're closer together.

fix(helm): server configmap incorrectly omits falsy values

---

api/grant.go
internal/access/access.go
internal/access/access_key.go
internal/access/access_test.go
internal/access/grant.go
internal/access/identity_test.go
internal/server/data/access_key.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/data/group.go
internal/server/data/pagination.go
internal/server/data/selectors.go
internal/server/grants_test.go
internal/server/routes_test.go

Branched from #3155
This PR converts list grants to SQL, and adds a bunch of tests.
It also changes `access.RequireInfraRole` to use `IncludeInheritedFromGroups`, instead of iterating over all the groups a user belongs to.

Use SQL for list grants

---

internal/server/apimigrator.go
internal/server/debug.go
internal/server/handlers.go
internal/server/openapi.go
internal/server/routes.go
internal/server/routes_test.go

Most routes in `GenerateRoutes` are added with a single. We have a few special cases that have to set fields on the `route` definition, which makes them more verbose.  
This PR changes `add` to accept the `method` and `path` separate from the `route` struct. This allows us to move the route definition to a package-level variable, and keep `GenerateRoutes` to a single line per route.

Reduce verbosity in GenerateRoutes

---

internal/access/access.go
internal/access/access_test.go
internal/access/credential_test.go
internal/access/grant.go
internal/access/group.go
internal/access/identity.go
internal/server/groups.go
internal/server/handlers_test.go
internal/server/middleware.go
internal/server/organizations.go
internal/server/telemetry.go
internal/server/users.go

We introduced `RequestContext` a little while ago to replace the untyped and mutable `gin.Context`. At the time we left a few things in `gin.Context` to keep the change small. This PR removes the last value (`identity`) from `gin.Context`.
Also updates the authorization check in `GetGroup` to match the style we use in `ListGroups` and `ListGrants`.

Remove deprecated identity value from gin.Context

---

api/grant.go
internal/access/access.go
internal/access/access_test.go
internal/access/grant.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/grants_test.go
internal/validate/validate.go

Branched from #3162, this PR resolves a couple TODOs added in that PR. Best viewed by individual commit.
1. validate that `showInherited` is only used when there is a userID. Previously we allowed this, but it did nothing. It's better to be strict about what is allowed, rather than accepting a query parameter that does nothing for the query. This will be even more important with long polling because we won't necessarily support long-polling with every query parameter.
2. remove the need to loop over the roles and perform multiple authorization queries by accepting a slice of privileges and returning all the grants at once.

Support querying for multiple privileges

---

internal/tools/querylinter/go.mod
internal/tools/querylinter/go.sum
internal/tools/querylinter/sync/sync-mod.go

Our custom linter is run by `golangci-lint` as a Go plugin. Go plugins must be built with the exact same version of Go, and the exact same version of all shared Go modules.
`make lint` will fail if someone updates `golangci-lint` on their local machine. This PR addresses the problem by adding a command to update the `go.mod` of the `querylinter` module based on the modules used by their local `golangci-lint`.
Usage:
From the `internal/tools/querylinter` directory, run
```
go run ./sync/sync-mod.go
```

Add a scipt to sync linter deps before running lint

---

api/restricted_subdomains.yaml
api/signup.go
api/signup_test.go
go.mod
internal/server/server_test.go
internal/server/signup_test.go
internal/server/testdata/openapi3.json

- extend list of reserved domains
- don't allow domains of 5 char or less (would have to be created manually by us if we want it)
- add test
- one change we might want to make after this (or in this pr) is to have different error messages for the reserved list vs the reject list. the reserve list should say to sign up with a different domain and/or contact us or something along those lines.

fix: extend list of reserved domains in signup

---

internal/connector/authn.go
internal/connector/connector_test.go
internal/server/handlers_test.go

Show the endpoint working with org lookup from access key.
Also include the response status code in connector logs, if the request failed.

Add more tests for well known jwks

---

internal/connector/connector.go

The access key being used for the getJWK call to the server was being used directly from the command line options. If a user specified a value of `env:...` or `file:...` then the connector would have sent the wrong value for the access key.
This PR fixes the problem by first resolve the access key to the value stored in secrets, and using that as the value for the auth header.
Not entirely sure how to write a test for this since we can't easily run the connector in isolation until  #2613 is merged.

fix: resolve the access key to the secret value

---

internal/cmd/list.go
internal/cmd/list_test.go
internal/cmd/testdata/TestListCmd/with_many_grants

This bug was causing `infra list` to hide access to destinations named with `infra...` prefix.  Also fixes a similar bug related to filtering of destination names that may have displayed some grants for a destination that did not exist , if there was another destination where the name was a prefix of the other.
Also refactor the logic a bit to remove one of the iterations. We can build the list of resource names when we find a resource that is not yet in the map.

Fix `infra list` with destinations named with a prefix of infra

---

internal/cmd/about.go

Adds ctrl-C and the 'q' key as ways to get out of `infra about`

maintain: add other ways to abort the about command

---

helm/charts/infra/templates/connector/clusterrole.yaml
internal/kubernetes/kubernetes.go

If connector is using service.type=NodePort, get the node list and find the first external address. If no external address is available, fallback to using the internal IP but warn the user. The internal IP is usable iff the client has a route to that network.
May be worth adding an option to prefer the internal IP which will also disable the warning.
Tested with public node port in EKS.

feat: connector service.type NodePort

---

internal/cmd/login.go

Trims whitespace from the server that user inputted on the cli:
```
$ infra login
Server:      localhost    
```
User entered '    localhost   ' --> trimmed to 'localhost' 
Resolves #3150

improve: trim whitespace when entering server from cli

---

api/client.go
internal/connector/connector.go

Observe the requests the connector makes to the server and report them as Prometheus metrics.
Resolves #2664

feat: add prom metrics for connector->server requests

---

internal/server/authn/key_exchange.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/credential.go
internal/server/data/organization.go
internal/server/grants_test.go
internal/server/middleware.go

This validation is only to catch programming errors. A user should never see these errors, they are exclusively safeguards to try and make bugs more obvious in tests.
We already have this same validation on a bunch of types (Grants and ProviderUser both have many checks). This PR adds a few more to other types.

Add a bit more validation on create and update

---

helm/charts/infra/templates/connector/clusterrole.yaml
helm/charts/infra/values.yaml

Using lookup is not stable since the outcome is dependent on the state of the system. It becomes essentially a toggle as the user installs/upgrades the connector.
Example:
1. No `logs` cluster role so Helm includes and install it
1. Lookup finds `logs` so Helm omits and removes it
1. Go to 1.
The original intent with the look up is to prevent overriding any existing roles with the same name.
Instead of using lookup, the chart now contains values to include or omit specific roles. If a role already exists, Helm will refuse to overwrite it and the user can disable the role with `connector.defaultRoles.roles.<role>=false`.
If the user instead wants to disable creating default roles entirely, they can set `connector.defaultRoles.create=false`.
Resolves #3262

fix(helm): create clusterroles based on values not lookup

---

internal/cmd/version.go
internal/cmd/version_test.go

This change removes displaying "Server: x.y.z" with the `infra version` command if the user is using an `infrahq.com` organization. It also adds CLI tests for the various different states (disconnected, saas, and local)
Fixes #3272

maintain: add version cli test + remove server version w/ saas

---

api/login.go
internal/server/authn/authn_method.go
internal/server/handlers.go
internal/server/login_test.go
internal/server/testdata/openapi3.json
ui/pages/login/callback.js
ui/pages/login/index.js
ui/pages/login/organizations.js
ui/pages/signup/index.js

Display organization names on the list of previously visited organization login pages.

feat: display organization names in previously logged in list

---

internal/server/data/encryption_key.go
internal/server/data/encryption_key_test.go
internal/server/models/encryption_key.go
internal/server/server.go

This PR updates the implementation of `CreateEncryptionKey` and `GetEncryptionKey` to use SQL instead of gorm.

Use SQL for encryption keys table

---

.github/workflows/ci-core.yaml

If any of the github workflow files change, or if the linter config changes we should run the core CI workflow.

ci: run core ci workflow on more paths

---

ui/components/grant-form.js
ui/components/layouts/dashboard.js
ui/pages/providers/add.js
ui/pages/providers/index.js
ui/pages/signup/index.js

- fixed signup domain error message display
- fixed nav sidebar ui look and feel
- fixed autocomplete behaviour
- fixed provider table formatting
- removed breadcrumbs on providers add section
- hide account on the menu when the user is not login as infra local user

fix: few more bugs on new ui

---

internal/access/access_test.go
internal/server/authn/authn_method_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/encryption_key.go
internal/server/middleware_test.go
internal/server/models/encryption_test.go
internal/server/server.go

Branched from #3167
This PR introduces `NewDBOptions` as a struct that lets us pass options to `NewDB`. We'll be able to use this to set connection pool settings, and we'll very likely have other settings to pass along as well.
The PR also moves the `loadDBKey` function to the data package. This encryption key is only used by models as part of `Scan` and `Value` methods when reading and writing to the database, so it's primarily a concern on the data package.  
Moving it to the data package should make it easier to support separate keys per organization (if that's something we want to do), and should make it easier to handle key rotation. It may also give us a way to remove the package-level symmetric key, which will be necessary if we make either of those changes.
Also resolves a TODO …

Move db encryption key loading to data package

---

internal/access/group.go
internal/server/data/group.go
internal/server/data/group_test.go
internal/server/models/group.go

Updates the data query functions for `CreateGroup`, `AddUserstoGroup`, `RemoveUsersFromGroup`, and `DeleteGroup` to use SQL.

Use SQL for Create, Update, and Delete groups

---

website/components/tabs.js
website/lib/markdoc/config.js

This commit synchronizes tab selection for tabs on the same page. It stores this selection in the browser query parameter so they persist between refreshes. Note: tabs use a default "group" and are automatically synchronized. To avoid this use the group="example" attribute in the tab tag in markdoc.

improve: add tab sync to website

---

internal/access/access_key.go
internal/access/access_key_test.go
internal/access/access_test.go
internal/access/identity_test.go
internal/cmd/keys.go
internal/server/access_keys.go
internal/server/authn/authn_method.go
internal/server/config.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/provider_test.go
internal/server/handlers.go
internal/server/models/access_key.go

fix: allow users to issue access keys to themselves

fix: allow users to issue access keys to themselves

---

internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go

When looking up group names on IDP login we should scope the look-up by org.

fix: scope group names

---

ui/pages/users/index.js

Adds a copy button for the password that is generated after adding a user.

improve: copy button for password after adding a user

---

internal/server/data/data.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/migrator/helpers.go
internal/server/data/sqlfunc.go

Also run each migration twice in the migration test to check for idempotence. Includes a couple fixes to migrations to make them idempotent.

Use a transaction to run data migrations

---

internal/cmd/server.go
internal/cmd/server_test.go
internal/server/data/data.go
internal/server/data/migrations_test.go
internal/server/server.go

Move default server options from `cmd/server.go` to `server/server.go`. This seems like a more reasonable place to set defaults. Specifically, it can set defaults for nested options without exposing internal structures like `data.Options`
Resolves #

improve: add configurable db connection options

---

internal/server/data/migrations.go
internal/server/data/migrations_test.go

#3009 added a transaction for migrations, but I missed adding it to the test function.
This PR adds a transaction for each test case. I used a separate transaction for `migrate` and `expected` because using the same transaction seem to produce a different error than the one we saw in production.  This transaction setup should match production, because we commit the transaction used for migrations before performing any other query.
Includes some fixes that will likely be merged before this, so I'll rebase once those are in.

Use a transaction in the migration test

---

api/provider.go
internal/generate/generate.go
internal/server/providers.go
internal/server/providers_test.go
internal/server/testdata/openapi3.json
ui/components/grant-form.js
ui/pages/providers/add.js

- UI form 
- Provider name will default to the kind (eg. 'okta'), and append a randomly generated string if it is taken
- Reword grey box text from "User or group" to "Enter user or group"
- Introduces a alphanumeric without vowels, for generated strings that will be user-facing to prevent accidental profanity
https://user-images.githubusercontent.com/20054646/192228163-3d62b23f-8103-4ce4-bc32-c5ece0a3cbd7.mov
- _**Previous:**_ 
- _**After:**_

feat: make name optional for provider

---

internal/server/config.go
internal/server/middleware.go
internal/server/routes.go

PostgreSQL row and table locks are held until the end of the transaction.
Previously we were using a single transaction for the entire lifetime of the request. One of the first things we did with that transaction was update the access key and user record associated with the request.
That update would block any other requests from that user until the first request finished. For short lived requests that was fine, but longer requests (anything making HTTP requests to an IDP, or blocking and waiting for updates) would prevent the user from making concurrent requests.
This commit fixes the problem by committing the "middleware" transaction first, then starting a new transaction for the request handler. The middleware transaction should be short lived, because it only does a few database …

fix: reduce request transaction lifetime

---

internal/access/access_test.go
internal/server/config.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrations_test.go
internal/server/handlers_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/routes.go

This will allow us to start read only transactions, or transactions with different isolation levels.
We're not using that yet, but after #3302 merges we'll be able to use it for handlers. An example of that can be seen here #3328.
We will also need this for long-polling. We need to use an isolation level that ensures that multiple queries in the same transaction all read the same snapshot (repeatable read).

Add TxOptions to txn.Begin

---

internal/access/access_test.go
internal/server/authn/authn_method_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrations_test.go
internal/server/data/sqlfunc_test.go
internal/server/middleware_test.go
internal/server/models/encryption_test.go
internal/server/server.go

Move the database connection and configuration parsing to the data package. This allows the data package to more fully abstract the database. In particular, the database password value is resolved before passing it to `NewDB()` so it doesn't need the server secret storage nor import secrets 
Resolves #

improve: move database dialector to data package

---

ui/pages/providers/add.js

improve: make learn more help link consistent

---

internal/server/data/migrations_test.go
internal/server/data/schema/parse.go

This will ensure that we don't leave stale test data in the database, which could cause subsequent test cases to fail.
Also adds a missing `DELETE` to cleanup some stale entries from an existing test case.

Add a check to the data migration test

---

api/client.go
api/provider.go
internal/server/providers.go
internal/server/providers_test.go
internal/server/routes.go
internal/server/testdata/openapi3.json
ui/components/role-select.js
ui/pages/providers/[id].js
ui/pages/providers/add.js
ui/pages/providers/index.js
ui/pages/users/index.js

https://user-images.githubusercontent.com/20054646/192602353-20db233a-7222-43eb-987b-7f53d967926b.mov
- Added a patch endpoint to allow partial update to provider, so the front end does not have to populate all the fields
- Created an edit provider page, where user can set a new provider name or provider secret 
- Changed text 'remove' into a '...' icon with a dropdown for edit and remove

feat: patch provider endpoint (api), edit provider (ui)

---

internal/server/data/forgotdomain.go
internal/server/data/forgotdomain_test.go

The forgot domain email was not using the correct capitalization inside the last seen field.

fix: use correct case when sending forgot domain email

---

internal/access/identity.go
internal/server/data/provider.go
internal/server/data/provideruser.go
internal/server/data/provideruser_test.go
internal/server/users_test.go

No functional changes here. As a part of SCIM user management I need to be able to apply custom SCIM queries to the provider user look-up. This is much easier using direct SQL so updating the provider user to use the direct SQL now.

maintain: migrate provider user data to direct sql

---

internal/server/debug.go
internal/server/handlers.go
internal/server/migrations.go
internal/server/routes.go

Branched from #3302, including the changes from #3327
This PR adds TxOptions to `routeSettings`, and uses it to create read-only transactions for some routes. This would also allow us to use different isolation levels if necessary.

Allow routes to specify transaction options

---

internal/server/data/passwordresettoken.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/handlers.go
internal/server/signup_test.go

Use the field name `org.subDomain` so that the UI, and other clients, can correctly associate the error with an input field.
Changing the `UniqueConstraintError.Column` to `org.subDomain` works to fix the field, but then the error becomes "an organization with that org.subDomain already exists", which is unfortunate. We could have added another field to `data.UniqueConstraintError` that would only be used by the API, but that seems like it's fixing the problem in the wrong place.
This PR takes the approach of changing `sendAPIError` to handle an already constructed `api.Error`. This allows API handlers to deal with special cases themselves. This approach also avoids a problem with unwrapping the error to make that modification directly, which would cause us to lose any fmt.Errorf context …

fix: use the correct field name in org conflict error

---

internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/schema.sql

`gorm` created the index as `PRIMARY KEY (identity_id, provider_id)`
Looking at the queries in #3345 we can see that while some queries use a `WHERE` clause with both of these, two of the queries can use only the `provider_id`. The order of the columns in the index matters. 
https://www.postgresql.org/docs/current/indexes-multicolumn.html has this to say about it (the default index type should be b-tree, even though it's not in the statement, [ref](https://www.postgresql.org/docs/current/indexes-unique.html)).
>A multicolumn B-tree index can be used with query conditions that involve any subset of the index's columns, but the index is most efficient when there are constraints on the leading (leftmost) columns. The exact rule is that equality constraints on leading columns, plus any …

Fix order of provider_user index

---

helm/charts/infra/templates/connector/configmap.yaml
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/types/file.go
internal/connector/authn.go
internal/connector/connector.go

This PR removes `infrahq/secrets` from the connector. The connector only ever used secrets from `env`, `file`, and `plaintext`, all of which we can read directly without needing to add an `env:`, `file:`, or `plaintext:` prefix to the value. 
This PR preserves backwards compatibility by removing any `env:` or `file:` prefixes from values before looking for the file or env var.
Also:
* changes the helm chart to create a configmap without the `file:` prefix on the access key value.
* adds support for reading the access key from `INFRA_ACCESS_KEY` env var in the connector. This matches the CLI. Unlikely anyone will use this yet though, since everyone is using the helm chart, not running the connector directly.
* adds support for reading the connector proxy CA and key from literals, in …

Remove secret storage from connector

---

internal/cmd/agent.go
internal/logging/logger.go

Add a counter to the infra agent. When a request fails, it increments the counter and halt the loop. If the counter exceeds the threshold, the agent will exit. This allows the agent to tolerate some interruption from the upstream service. 
The previous agent will exit immediately after getting an error. This can be frustrating if there's any minor interruptions, maybe due to network instability or long request times.

feat(agent): add retries to tolerate minor interruptions

---

internal/connector/connector.go
internal/kubernetes/kubernetes.go

Branched from #3220. Best viewed by individual commit, and the third commit benefits from the  "Hide Whitespace" view.
This PR adds support for reading the kube API hostname and CA cert from kubectl config when reading the in-cluster files fails. This is the first step to allow us to run the connector outside of kube (primarily for testing).
Also extracts a new `type connector struct` for the many args being passed to `syncWithServer`, and extracts a new `syncDestination` from that function as well. This is the first step to split up the `syncWithServer` goroutine into its two responsibilities: updating the destination, and updating role bindings.
In the next follow up PR I'll be addressing the remaining in-cluster calls, to allow the connector to run outside of a kube pod.
Related to …

Allow the connector to run outside of a kube pod

---

api/destination.go
internal/cmd/types/url.go
internal/cmd/types/url_test.go
internal/connector/connector.go
internal/kubernetes/kubernetes.go

Branched from #2613
This PR completes the work to allow the connector to run outside of a kube pod (primarily for testing).
Two options are added to the connector config (both can be omitted when run from inside the cluster, and are documented as being optional).
* `endpointAddr` - is the address of the connector proxy that is sent to the Infra API, to tell clients where to connect. Sometimes this will be the same value as `addrs.https`, but it may be different if there are load balancers or other proxies in-between. When set this allows us to skip the "lookup service host and port" steps, which require the service to exist in kuberenetes.
* `kubernetes.authToken` - gives us a way to specify a token (likely for a service account) that will be used to communicate with the kube API. I set …

Allow the connector to run outside of a kube pod (part 2)

---

internal/access/destination.go
internal/server/data/data.go
internal/server/data/destination.go
internal/server/data/destination_test.go

This PR converts the three destination write queries to use SQL.
`DestinationUpdate` is a bit of a special case. We don't receive the created_at time, so we have to exclude it from the query. I did that by creating a second set of methods for `Columns` and `Values`. We could also select the row first, but it seems like we should be able to do an update and omit the rows that we don't care to update. If this becomes a more common pattern then maybe we can support that difference in the Table interface somehow.
Also updated `CountDestinationsByConnectedVersion` to remove a sub-select.

Use SQL for Destination{Create,Update,Delete}

---

api/scim.go
internal/access/scim.go
internal/server/data/identity.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/provider.go
internal/server/data/provideruser.go
internal/server/data/provideruser_test.go
internal/server/data/schema.sql
internal/server/models/grant.go
internal/server/models/provideruser.go
internal/server/routes.go
internal/server/scim.go
internal/server/scim_test.go

- add SCIM list users endpoint
- add SCIM role
This change adds the necessary logic for a SCIM identity provider to list the users it has associated with it. 
It does not include the changes necessary to create an access key for an identity provider (which this functionality will rely on) so the code path can't be accessed yet.
Part of #3378

feat: SCIM list provider users

---

api/destination.go
internal/cmd/cmd_test.go
internal/cmd/destinations.go
internal/cmd/kubernetes.go
internal/cmd/kubernetes_test.go
internal/cmd/list.go
internal/cmd/list_test.go
internal/connector/connector.go
internal/server/destination_test.go
internal/server/testdata/openapi3.json
ui/pages/destinations/index.js

Update the connector to create itself as quickly as possible instead of waiting for a valid connection. This is mainly due to LoadBalancer potentially taking a significant amount of time to initialize. Creating the destination quickly allows the user to continue without waiting.
Update UI and CLI to output status == "Pending" when the destination is disconnected and does not have a connection URL. Omit pending and disconnected destinations when syncing kubeconfig

feat(connector): create destination as soon as possible

---

ui/components/delete-modal.js
ui/components/table.js
ui/pages/account/index.js
ui/pages/destinations/[id]/index.js
ui/pages/destinations/add.js
ui/pages/groups/[id].js
ui/pages/groups/index.js
ui/pages/providers/[id].js
ui/pages/providers/add.js
ui/pages/users/index.js

- fix delete message to show all the group / user name instead of truncate the string
- add metadata on the destination page
- remove the tabs on the destination detail page
- fix off styling for the add provider page 
- modify the flow when add group - after click add on create group, user will be redirected to the detail page of the group that the user just created

fix: minor ui bugs and improvements

---

api/organization.go
internal/access/organization.go
internal/server/handlers_test.go
internal/server/models/organization.go
internal/server/organizations.go
internal/server/organizations_test.go
internal/server/testdata/openapi3.json

This change modifies the `GET /api/organizations/:id` endpoint to now support `GET /api/organizations/self` similar to how `GET /api/identities/self` works. The user does not need to be an infra support admin to retrieve their own organization details.
Additionally, the `created` and `updated` fields inside of the JSON response are now being properly updated (instead of returning `null` values), and a unit test for the endpoint has been added.

feat: add endpoint to get a user's own organization

---

internal/connector/connector.go
internal/kubernetes/kubernetes.go

Remove the server lookup when server config value is `localhost`. The original use case for this was to provide a simple way to configure a in-cluster connector. This is no longer useful. Users should provide the server URL explicitly
Resolves #3380

fix: remove server lookup

---

api/destination.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/testdata/openapi3.json

A dot in a destination name makes all grants for that destination ambiguous. They could refer to multiple destinations.
For example a grant with `resource=kubernetes.dev` could mean the default namespace for a destination named `kubernetes.dev`, or it could mean the `dev` namespace for a destination named `kubernetes`.
We could decide to separate destination from the resource on the grant, which would allow us to support dots in destination names. That's a much larger change, so until we decide we need that, we have to exclude dots from destination names.
We don't have any telemetry for destination names. I think we need to make this change regardless, but we should be careful to call this out in the release notes as a potentially breaking change.  We may want to combine this with the …

fix: do not allow dots in destination names

---

internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/schema.sql

Branched from #3276 
This PR adds a unique constraint to destination name. The destination name must be unique because it is referred to be both grants in the `resource` field, and by users when running `infra use`. A non-unique name makes both the grants and the `use` ambiguous and will likely cause problems.

Add unique constraint to destination name

---

ui/pages/providers/[id].js

The client secret field has an initial value which gets passed to the API request even if it's unchanged. This can lead to unexpected changes to the client secret if only the name is updated.

fix: edit provider only update changed fields

---

internal/connector/connector.go
internal/server/destinations.go
internal/server/middleware.go

This should allow us to have different life-cycles for each of these operations.

connector: Use a separate goroutine for update destination

---

api/client.go
api/grant.go
internal/access/grant.go
internal/cmd/grants.go
internal/connector/connector.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/grants.go
internal/server/grants_test.go
internal/server/testdata/openapi3.json

Both the UI and the connector would like to list grants by destination. 
This PR adds a new `destination` query parameter to `ListGrants`, and updates the connector to use this new parameter. In #3351 the connector will change once again to wait on updates to that query.
For now this query uses an `OR` clause. In the future we will likely want to save the destination name as a column, so that we can remove the `OR`.

api: add support to list grants by destination

---

internal/access/identity.go
internal/access/identity_test.go
internal/cmd/users.go
internal/server/config.go
internal/server/config_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/provider.go
internal/server/data/provider_test.go
ui/pages/users/index.js

- infra users command adds/removes from the infra identity provider specifically
- consolidate identity deletion logic
- delete identity when it no longer exists in any identity provider
When a user is deleted using `infra users add` or `infra users rm` only delete the resources associated with the identity through the Infra provider. Users from other identity providers can be removed by removing the associated provider, or through SCIM (soon).
Resolves #3397
Resolves #2838

fix: delete users from specific identity provider

---

internal/server/data/migrations.go
internal/server/data/migrations_test.go

This should be merged after #3398
When an identity was deleted through the CLI the associated provider user was not deleted. This migration cleans up provider_user records that reference a deleted identity.
Resolves #3397

fix: remove provider users for deleted identities

---

.github/workflows/ci-core.yaml
Makefile
docker-compose.dev.yaml

The default for docker port mapping is `0.0.0.0` (all interfaces), which can be a security risk. If a developer laptop is ever connected to an untrusted network, someone on that network could connect to the database and use `COPY` and other postgres operations to read files or even run processes on the laptop.
By mapping the host port to 127.0.0.1 we ensure that no one can connect to the dev database except for the processes on the local host.
If you are using Docker for Mac I could use your help to confirm this works with that setup.

fix postgres-dev to only listen on localhost

---

internal/server/data/access_key.go
internal/server/data/destination.go
internal/server/data/grant.go
internal/server/data/identity.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/provideruser.go
internal/server/data/query.go

I've noticed we end up having a lot of boilerplate for reading the rows from `tx.Query` into a slice. Using generics , this new `scanRows` removes the need to repeat the common parts.
I converted a bunch of queries in this PR to show how it works, but there are a few more places that have not been converted yet. I might look to do that in a follow up, or leave it until we make some other change to the code.

data: add helper for scanning rows into a slice

---

internal/access/credential.go
internal/access/credential_test.go

When a credential is update the access key needs to have the "password reset required" scope removed, but keep the ability to create access keys. This change ensures that the key has the only the "password reset required scope" removed so any scopes we add in the future will also continue to work.
Resolves #3348

fix: only remove password reset scope on cred update

---

Makefile

Fixes a problem introduced in #3403 (just merged)
While [the postgres default for `listen_addresses` is localhost](https://www.postgresql.org/docs/current/runtime-config-connection.html#RUNTIME-CONFIG-CONNECTION-SETTINGS), the docker container apparently sets a default of `0.0.0.0`. I must have changed this at the last minute without testing, assuming the default was still localhost.
Setting `listen_address` to localhost does not work. The docker port mapping isn't able to map to the localhost port. This PR reverts setting `-c listen_addresses`, so that the default is used. This fixes the docker port mapping.

fix: postgres-dev container listen address

---

docs/reference/cli.md
internal/docgen/cli.go
internal/docgen/main.go

The docgen process was generating cli-reference.md, but all the docs point to cli.md after renaming a month or so back. So this update generates the right doc, and cleans up the generated doc a bit.
Resolves #

maintain: cli docgen fixes to clean up the resulting file

---

website/next.config.js

A month or so back, we simplified a lot of the docs. One of the changes was moving reference/cli-reference to reference/cli. I added most of the redirects, but managed to miss this one. 
Resolves #

maintain: add redirect for cli-reference to docs

---

api/user.go
internal/access/credential.go
internal/access/credential_test.go
internal/access/passwordreset.go
internal/server/authn_test.go
internal/server/testdata/openapi3.json
internal/server/users.go
internal/server/users_test.go
ui/pages/account/index.js

When a user changes their password, they need to specify their old password in addition to their new password. This doesn't modify the forgot password screen which validates a user's identity by sending them a password reset link email.

Require oldpassword

---

internal/server/data/data.go
internal/server/data/destination.go
internal/server/data/query.go
internal/server/data/query_test.go

If someone is able to guess the ID of a row or the ID is accidentally shared it's possible a non-authorized user could update the row using the ID.
This PR fixes the bug by setting `WHERE organization_id = ?` so that only a user authorized for that org can perform updates.
Also adds a bunch more godoc for `query.go`.

fix: include organization_id in where clause of update queries

---

ui/lib/serverconfig.js
ui/pages/login/callback.js
ui/pages/login/index.js

When no server URL is set in server configuration set the default server URL to the current host on response. This allows the login response to continue when the optional `baseURL` server configuration is not set, but it also ensures that we wait until we have checked the server to see if there is one set.
Resolves #3374

fix: dont require server config base url on login

---

internal/access/access.go
internal/access/credential.go
internal/access/forgotdomain.go
internal/access/identity.go
internal/access/organization.go
internal/access/passwordreset.go
internal/access/provider.go
internal/access/settings.go

`getDB` was deprecated a while ago, when we added `RequestContext`. We left it for a bit to make sure we had the right interface for `RequestContext`. It seems to be working well, so now we can remove it.
We had 3 different ways to authorize a request (`hasAuthorization`, `RequireInfraRole`, and `Can` which was recently renamed to `IsAuthorized`).  We've been replacing the use of `hasAuthorization` with a check in the caller to compare the requested ID to the authorized user. This PR replaces the last few callers to use the pattern we have in other place. It also changes `isIdentitySelf` to accept a `RequestContext` and remove the error return (since it always returned `nil`).  This reduces the number of ways to authorize a request to 2. We should be able …

Remove getDB and hasAuthorization

---

.github/workflows/fuzz.yaml
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/organization_test.go
internal/server/data/schema.sql
internal/server/data/schema/parse.go
internal/server/models/grant.go

Branched from #3396 , extracted from #3351 
This PR adds `data` package and DB support for listen/notify to be used for long-polling `ListGrants` requests.
* adds a `seq_update_index` sequence for tracking updates
* adds an `update_index` column to the `grants` table, and sets the value to the next value in the index on every insert and soft-delete
* adds a trigger and trigger function for calling `pg_notify` on queries that insert or update (soft-delete does update) grants.
* adds a function to listen and wait on notifications
* adds a `GrantsMaxUpdateIndex` for getting the max update index for a query (which must include soft-deleted rows
TODO:
API support will come in a follow up PR, but most of it can be seen in #3351

Listen and notify for grants

---

internal/cmd/kubernetes.go
internal/cmd/kubernetes_test.go
internal/cmd/logout_test.go

kubeconfig.AuthInfo no longer follows the name of the contexts so when kubeconfig entries are removed, the authinfo remains. Instead of removing entries based on the name of the contexts, use the name of the individual references, e.g. context.Cluster and context.AuthInfo

fix: remove authinfo for context

---

.golangci.yml
api/grant.go
api/types.go
internal/access/grant.go
internal/cmd/server.go
internal/cmd/server_test.go
internal/server/data/data_test.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/schema.sql
internal/server/grants.go
internal/server/grants_test.go
internal/server/middleware_test.go
internal/server/pagination.go
internal/server/routes.go
internal/server/routes_test.go
internal/server/server.go
internal/server/server_test.go

Branched from #3436 
Best viewed by individual commit. This PR makes the following changes:
* disables pagination when the request includes `lastUpdateIndex`, so that all the results are returned on an update
* extends the request timeout from 1 minute to 5 minutes for request with `lastUpdateIndex > 0`, and makes both timeouts configurable from server options
* adds a test for concurrent requests
* adds tests for blocking requests, to show they unblock on unpdate
* fixes a bug when a query for grants returned no results

Improve blocking requests and add more test coverage

---

internal/server/grants_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/routes.go
internal/server/routes_test.go

I noticed this problem while testing blocking requests in dev.
PR #3443 tried one approach for using a longer timeout in blocking requests using `extendedContext`. That worked to extend the deadline, but breaks regular cancellation (ex: when a client disconnects).
This PR takes a different approach. By removing the `TimeoutMiddleware` and moving that timeout into `wrapWroute` we can capture the original context set on the request by `http.Server`.  This allows us to create a new context without losing cancellation on the original context.
With this approach we get both a longer deadline, and proper cancellation when a client disconnects.

Fix context cancellation in blocking requests

---

internal/server/authn/authn_method.go
internal/server/authn/authn_method_test.go
internal/server/authn/key_exchange.go
internal/server/authn/oidc.go
internal/server/authn/password_credentials.go
internal/server/authn/password_credentials_test.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/grants_test.go
internal/server/handlers_test.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/users_test.go

This approach was first used by @mxyng for the `Destination.LastSeenAt`. This PR adopts the approach for `Identity.LastSeenAt`, and `AccessKey.ExtensionDeadline`.  All 3 of these values may be updated on every authenticated request.
If a user makes many requests in a short period of time, each of the requests ends up blocking while the middleware transaction runs. While testing in development with 100 concurrent requests I noticed database queries blocking for over a minute.
This PR throttles the updates, so that we only update each of these values once every 2 seconds. Previously we used 1 second, but I'd like to increase that a bit to throttle more. It means that a `LastSeenAt` value could be stale by up to 2 seconds.
Also fixes updates of access key extension deadline, which broke in …

Throttle database updates for LastSeenAt and ExtensionDeadline

---

docs/reference/cli.md
internal/access/access_key.go
internal/cmd/providers.go
internal/cmd/providers_test.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/provider.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/models/access_key.go

Allow creating access keys for identity providers to make SCIM requests. This change only adds CLI support, waiting for full user SCIM support to add to the UI.
Example CLI interaction.
```
$ infra providers add okta --url dev-123.okta.com --client-id xyz --client-secret xxx --kind okta --scim
Connected provider "okta" (dev-123.okta.com) to infra
Access key for SCIM provisioning: aaaaaaaa.bbbbbbbbb
$ infra providers edit okta --scim
New access key for SCIM provisioning: aaaaaa.bbbbbbbb
```
Part of #3378

feat: create access keys for idp scim

---

api/scim.go
go.mod
go.sum
internal/server/data/provideruser.go
internal/server/data/provideruser_test.go
internal/server/data/scim.go
internal/server/data/scim_test.go
internal/server/scim.go

Parse SCIM query filters into SQL. 
Branched from #3405
Part of #3378

feat: parse scim query filters

---

ui/components/scim-key.js
ui/pages/providers/[id].js
ui/pages/providers/add.js
ui/pages/providers/index.js

Create an access key that a provider can use for SCIM in the UI.
Resolves #3378

feat: ui generate scim access key for provider

---

internal/server/models/destination.go

Long polling timeout is 5 minutes, so we need a bit more time to keep the destination showing as connected between long polling requests.

Extend the threshold for Destination.LastSeenAt connected

---

docs/api/openapi3.json
internal/server/openapi.go
internal/server/testdata/openapi3.json

Today when you import the openapijson doc into a tool like Paw or Postman, you have to add Authorization: Bearer <key> to every header. This fixes the generator to add authorization to each api endpoint
Resolves #

feat: Add Authentication to OpenAPI Gen for all the endpoints

---

internal/server/authn_test.go
internal/server/debug_test.go
internal/server/groups_test.go
internal/server/handlers_test.go
internal/server/helpers_test.go
internal/server/organizations_test.go
internal/server/users_test.go

@pdevine mentioned that they can be hard to find sometime, so this PR moves the test helpers I know of to `helpers_test.go`.
I think the risk with this approach is that contributors can start to overload these helpers and tests become very difficult to work with because there are huge layers of abstraction that you have to understand before you can understand the test.
I think the helpers we have now are ok. We should strive to keep this file small, and keep less-generic helpers next to the specific tests that warrant them. In this PR I moved a few helpers or vars into tests, because those were very specific to a test, and should not be re-used.

Move test helpers to helpers_test.go

---

docs/api/openapi3.json
internal/server/openapi.go
internal/server/routes.go
internal/server/testdata/openapi3.json

Auth header in openapi docs was a manual list that needed to be edited. this updates it so that it's detected and generated automatically, so impossible to screw up.
also fixed:
- regex for auth tokens
- this resolved a bug with one endpoint saying it needed auth which it did not.
Resolves #

fixes auth header around open api docs

---

api/client.go
api/client_test.go
api/types.go
internal/cmd/destinations.go
internal/cmd/grants.go
internal/cmd/groups.go
internal/cmd/info.go
internal/cmd/keys.go
internal/cmd/kubernetes.go
internal/cmd/list.go
internal/cmd/list_test.go
internal/cmd/login.go
internal/cmd/pagination.go
internal/cmd/pagination_test.go
internal/cmd/providers.go
internal/cmd/users.go
internal/connector/connector.go

To test blocking requests we need to be able to cancel the blocking operation, which requires that the `api.Client` method accepts a `context.Context`. I need this for the connector tests in #3444
This PR starts the work of adding a `context.Context` argument to all `api.Client` methods.
The first commits prepares for the new argument by splitting up `api.request`. This function already had more than enough arguments. Splitting up into `buildRequest`, `encodeRequestBody`, and `request` allows us to reduce the number of arguments to each, and make `buildRequest` a method on `Client`.
The second commit adds the `context.Context` argument to `buildRequest` and the http method helper functions, using `context.TODO` as a placeholder.
The last commit adds the `context.Context` argument to all …

Start adding context.Context to api.Client methods

---

internal/access/grant.go
internal/access/group.go
internal/access/identity_test.go
internal/server/authn/oidc_test.go
internal/server/config.go
internal/server/data/grant.go
internal/server/data/group.go
internal/server/data/group_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/provideruser_test.go
internal/server/data/token.go
internal/server/groups_test.go

Branched from #3199 
Convert `ListGroups` and `GetGroup` to use SQL and add a few more test cases for them.
Resolves #2415

Use SQL for ListGroups and GetGroup

---

api/client.go
api/grant.go
internal/access/grant.go
internal/cmd/grants.go
internal/cmd/grants_test.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/grants.go
internal/server/grants_test.go
internal/server/routes.go
internal/server/routes_test.go
internal/server/testdata/openapi3.json

This PR adds a new `PATCH` method for the `/api/grants` endpoint. It allows API callers to simultaneously add and remove multiple grants instead of having to make multiple calls.
* some additional unit tests should be added for "un-happy" path in the server, however there are some tests in the data package.

Add bulk grant update

---

api/client.go
api/client_test.go
internal/connector/connector.go
internal/connector/connector_test.go

This PR updates the connector to use blocking requests for `ListGrants`. The connector will block until there is an update or timeout. Also adds log messages for the sync operation.

Update the connector to use blocking requests for ListGrants

---

api/client.go
api/client_test.go
internal/cmd/destinations.go
internal/cmd/grants.go
internal/cmd/groups.go
internal/cmd/info.go
internal/cmd/keys.go
internal/cmd/kubernetes.go
internal/cmd/list.go
internal/cmd/list_test.go
internal/cmd/login.go
internal/cmd/logout.go
internal/cmd/providers.go
internal/cmd/tokens.go
internal/cmd/users.go
internal/cmd/version.go
internal/connector/connector.go
internal/connector/connector_test.go

Branched from #3492
This PR adds the `ctx context.Context` argument to the remaining `get` methods, and all the `put`, `patch`, `post`, and `delete` methods.
This PR also removes the generic `Req any` type parameter to `put`, `post`, and `patch`. We're passing that value to json marshal, which accepts `any`, so we don't need the type parameter.

Add context.Context argument to api.Client methods - part 2

---

internal/server/deviceflow.go
internal/server/deviceflow_test.go

`Request.URL.Host` may be empty. Instead use `Request.Host` which should the required string
From https://pkg.go.dev/net/http#Request:
// For server requests, the URL is parsed from the URI
// supplied on the Request-Line as stored in RequestURI.  For
// most requests, fields other than Path and RawQuery will be
// empty. (See [RFC 7230, Section 5.3](https://rfc-editor.org/rfc/rfc7230.html#section-5.3))

fix: set default device flow url

---

internal/access/credential.go
internal/access/credential_test.go
internal/access/identity_test.go
internal/access/passwordreset.go
internal/access/passwordreset_test.go
internal/server/authn/password_credentials.go
internal/server/config.go
internal/server/data/credential.go
internal/server/data/credential_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/selectors.go
internal/server/data/tables_test.go
internal/server/users_test.go

This PR converts the `data` query functions for credentials to use SQL, and adds some test coverage for the functions.

Use SQL for credential queries

---

api/client_test.go
api/types.go
internal/access/grant.go
internal/connector/connector.go
internal/connector/connector_test.go
internal/errors.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/grants_test.go
metrics/metrics.go

This PR addresses two problems with monitoring of blocking API requests:
1. changes the http response status code from 504 gateway timeout, to 304 not modified, when a blocking request times out
2. add a `blocking` label to both HTTP metrics, so that we can filter out `blocking=true` in the monitors for API request latency

Return 304 on blocking request timeout, and add label for blocking request

---

internal/access/organization.go
internal/server/authn/authn_method.go
internal/server/config_test.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/organization.go
internal/server/data/organization_test.go
internal/server/data/tables_test.go
internal/server/middleware.go
internal/server/organizations_test.go
internal/server/signup_test.go

This PR converts the `data` query functions for organizations to SQL, and adds test coverage for the functions.

Use SQL for organizations queries

---

internal/access/access_key_test.go
internal/access/credential_test.go
internal/access/settings.go
internal/server/data/migrations_test.go
internal/server/data/organization.go
internal/server/data/selectors.go
internal/server/data/settings.go
internal/server/data/settings_test.go
internal/server/data/tables_test.go
internal/server/models/settings.go

Branched from #3540 
Convert `data` queries for settings to SQL, and add  test cases.

Use SQL for settings queries

---

helm/charts/infra/templates/connector/deployment.yaml
helm/charts/infra/templates/connector/service.yaml
helm/charts/infra/values.yaml
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/connector_test.go
internal/connector/connector.go

The connector has a single HTTPS service which is problematic for most health checkers as they tend to default to TCP. This causes an incomplete TLS handshake which shows up in logs as `http: TLS handshake error from <addr>:<port>: EOF`. Adding a HTTP service mitigates this since the health checker does not attempt an TLS handshake

fix: add http connector service to serve health check

---

helm/charts/infra/templates/connector/deployment.yaml
helm/charts/infra/templates/connector/service.yaml
helm/charts/infra/values.yaml
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/connector_test.go
internal/connector/connector.go

This reverts commit f55e99bfc817ada7ad27c56bd8cc6de5d571c6e1, reversing changes made to 50a9ffc68024d4426b04b444289bdd66044b41d5.
The HTTP service is interfering with the connector's endpoint discovery among other things. Reverting for now

Revert "Merge pull request #3543 from infrahq/mxyng/http-connector"

---

helm/charts/infra/Chart.yaml
helm/charts/infra/templates/postgres/_helpers.tpl
helm/charts/infra/templates/postgres/statefulset.yaml

Using the data mountpoint directly causes problems for postgres in certain scenario where the directly may not initialize empty. Instead, use a subdirectory under the mountpoint to store the actual data.
* Add migration to move data previously stored in the mountpoint to the subdirectory (`/var/lib/postgresql/data -> /var/lib/postgresql/data/pgdata`)
* Fix postgres health checks to use the right user and database name
* Bump appVersion to 0.16.1, chart version to 0.20.5
- Install Infra locally with chart 0.20.4
- Load some data (users, groups)
- Upgrade chart
- Verify data still exists
- Install Infra with chart 0.20.4.
- Postgres pod goes into crash loop
- Install updated chart
- No crash loop
Resolves #3124
Resolves #3555

fix: postgres data mountpoint

---

internal/server/data/data.go
internal/server/data/destination.go
internal/server/data/destination_test.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/data/group.go
internal/server/data/group_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/organization.go
internal/server/data/organization_test.go
internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/data/query.go
internal/server/data/selectors.go
internal/server/metrics.go
internal/server/server.go
internal/server/telemetry.go
internal/server/testdata/TestMetrics/infra_grants
internal/server/testdata/TestMetrics/infra_users

This PR converts queries that used `GlobalCount` to use SQL. Instead of a single shared function for everything I created a `countRows` that works for the common case (tables with a `deleted_at` row), and called `countRows` from a type-specific function. In the future if we customize the counts for a type we can add an options struct to these functions.
Also adds test coverage of the count functions.
This PR makes one small changes to the counts. Previously we would exclude the connector user and connector grant from the metrics counts (but not from the telemetry counts, and we didn't exclude the infra provider from the list of providers in either case). 
I can add these excludes back if we think they are important, but I think we should consider omitting them because they make the query …

Convert count queries to SQL

---

internal/server/errors.go
internal/server/errors_test.go

So that these errors don't show up as 500 errors in our metrics and logs.
There's no standard response code for this, but Nginx uses 499 so let's do the same.

Use 499 status code for context cancelled.

---

internal/cmd/connector_test.go

`TestConnector_Run` can flake occasionally in CI ([example](https://github.com/infrahq/infra/actions/runs/3396067574/jobs/5646711979)), but I've never been able to reproduce it locally.
From what I can tell, the connector is attempting to list destinations, but that API request never completes. The test ends up failing because the destination is not registered before the timeout.
I'm hoping it's just that CI can be very slow sometimes. The `poll.WaitOn` defaults to 10 second timeout, so I've created both the context deadline and this timeout to 30 seconds.
Also enable debug logging so that when it flakes maybe it gives us a bit more information about what is happening.
More links to flakes:
* https://github.com/infrahq/infra/actions/runs/3397238044/jobs/5649186761

Enable debug log to track down test flakes in TestConnector_Run

---

internal/server/access_keys_test.go
internal/server/authn_test.go
internal/server/debug_test.go
internal/server/deviceflow_test.go
internal/server/grants_test.go
internal/server/groups_test.go
internal/server/handlers_test.go
internal/server/helpers_test.go
internal/server/organizations_test.go
internal/server/passwordreset_test.go
internal/server/providers_test.go
internal/server/redirect_test.go
internal/server/routes_test.go
internal/server/scim_test.go
internal/server/signup_test.go
internal/server/tokens_test.go
internal/server/users_test.go

`httptest.NewRequest` is more appropriate use with `ServeHTTP` as its intended to simulate an incoming request rather than a client request (`http.NewRequest`). This is critical as one of the differences between server and client requests has caused problems on [two](https://github.com/infrahq/infra/pull/2945) [separate](https://github.com/infrahq/infra/pull/3548) occasions.
Instances where the request is used with a `http.Client` are left unchanged.

fix: use httptest.NewRequest where appropriate

---

ui/pages/destinations/add.js

- when an admin adds a cluster to infra through the UI automatically grant them cluster-admin access on finish
It is confusing that someone must grant themselves access to a cluster they just added to Infra. This automatically gives a user "cluster-admin" access upon adding a cluster.
Resolves #3258

maintain: automatically add grant when cluster added

---

docs/api/openapi3.json
internal/access/deviceflow.go
internal/server/backgroundjobs.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/deviceflowauthrequest.go
internal/server/data/deviceflowauthrequest_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/passwordresettoken.go
internal/server/data/passwordresettoken_test.go
internal/server/data/schema.sql
internal/server/deviceflow.go
internal/server/jobs/jobs.go
internal/server/models/deviceflowauthrequest.go
internal/server/server.go

- remove expired records
- encrypt device flow access key
- add background jobs

device flow cleanup

---

api/client.go

`api.GetGrant` is missing which makes retrieving a single grant by ID unnecessarily difficult

improve: add GetGrant api

---

internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/connector_test.go
internal/connector/connector.go
internal/kubernetes/kubernetes.go

Iteration on https://github.com/infrahq/infra/pull/3543. Separate out the Helm changes as it will cause problems if image and chart are deploy out of sync. Filter service port to pick out the `https` service port instead of using the first, which will be `http`. `http` will not work as the destination port since it does not serve the proxy

fix: add http connector service

---

internal/server/config_test.go
internal/server/data/access_key.go
internal/server/data/data.go
internal/server/data/data_test.go
internal/server/data/migrator/helpers.go
internal/server/data/migrator/migrator.go
internal/server/data/migrator/migrator_test.go
internal/server/data/provider_test.go
internal/server/data/sqlfunc_test.go
internal/server/passwordreset_test.go

This PR updates a bunch of tests that were using the gorm interface for queries to use the stdlib interface for queries.

Update tests that use gorm to use the stdlib interface

---

internal/access/request.go
internal/server/data/data.go
internal/server/grants.go
internal/server/logging.go
internal/server/logging_test.go
internal/server/routes.go

This PR introduces a hook for adding fields to the API request log. It also uses the new hook in list grants to add a `lastUpdatedIndex` and `numGrants` fields. I think we may also want to use this with SCIM endpoints, so that we can track which provider is using which fields. I'm sure we'll find other use cases for adding fields to the request log as we add new endpoints.
I think maybe we can find a better way to include these fields, but this seemed to work for now. If anyone has a suggestion for a better interface, I'd be happy to incorporate it.

Add endpoint-specific fields to API request log

---

api/access_key.go
api/client.go
docs/api/openapi3.json
internal/cmd/keys_test.go
internal/server/access_keys_test.go
internal/server/migrations.go
internal/server/routes_test.go

Change `user_id` to `userID` in `GET /api/access-keys?userID=` to make it consistent with the rest of the API.
Note that this will break the old API if something is using it, however, it's unlikely that a lot of callers (or any, really) are actually using it right now.

maintain: make userid field for access keys consistent

---

api/client.go
api/destination.go
docs/api/openapi3.json
internal/access/destination.go
internal/cmd/agent.go
internal/cmd/cmd.go
internal/cmd/connector_test.go
internal/cmd/destinations.go
internal/cmd/destinations_test.go
internal/cmd/list.go
internal/cmd/testdata/TestDestinationsListCmd/list_default_table_format
internal/cmd/testdata/TestDestinationsListCmd/list_with_json
internal/cmd/testdata/TestDestinationsListCmd/list_with_yaml
internal/connector/connector.go
internal/server/data/destination.go
internal/server/data/destination_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/schema.sql
internal/server/destination_test.go
internal/server/destinations.go
internal/server/metrics_test.go
internal/server/middleware_test.go
internal/server/models/destination.go

So that we can support more than one kind of destination.
This PR adds api, data, and CLI support for `destination.kind`. I'm not sure what (if anything) needs to change for the UI.
I made this a non-breaking change by making the API field optional and defaulting to kubernetes (since that's the only destination that exists right now). In the future we can make it required in the API as well.

Add kind field to destinations

---

api/grant.go
docs/api/openapi3.json
internal/access/credential.go
internal/access/group.go
internal/access/identity.go
internal/server/grants.go
internal/server/grants_test.go
internal/server/groups.go
internal/server/users.go

Allow `PATCH /api/grants` to use user names as well as user/group IDs

feature: grants by name

---

Makefile

Don't run unit tests w/ `make test` and `make test-all` if the POSTGRES_CONNECTION env variable is not set.
If the string is not set, `go test ./...` gets run, and it will silently skip a number of unit tests which rely on the postgres db. These tests _will_ be run in our CI system, but will leave you scratching your head why they're not running locally.

maintain: exit tests if the postgres_connection string isn't specified

---

.github/workflows/ci-core.yaml

GitHub's required status check need exact job name matches. In case of `strategy.matrix`, the job name gets modified by the matrix such that it no longer matches the configured required status check. Instead, rename the job to `test-matrix` and create a new job matching the required status check name dependent on `text-matrix` results.

fix: go test ci

---

ui/pages/providers/[id].js

under specific conditions, the provider details page will throw an uncaught exception caused by `useEffect` setting `name` to undefined when provider is undefined.
use a placeholder instead of setting the field value directly. this also fixes the issue where an empty value is seens as a change, enabling save.

fix(ui): undefined reference in providers

---

internal/server/access_keys_test.go
internal/server/apimigrator.go

This change fixes an issue with the api migrations which would hide any nested structs which are part of the request struct. This includes all of the pagination structs. If you add a migration, any version which is _before_ the version you specify will be impacted, which means pagination will no longer work unless the client making the request specifies a _newer_ API version.

maintain: fix the apimigrator for nested structs

---

ui/pages/groups/index.js

leading whitespaces are particularly problematic because it makes it possible to create group names that look empty, e.g. " ". a side effect is group names with " " (one whitespace) and "  " (multple consecutive whitespaces) will cause a 409 Conflict on creation since the server trims inputs.
non-leading or non-trailing whitespaces are left as is so it's possible to have repeats in t between other characters

fix(ui): trim leading and trailing whitespace in group names

---

go.mod
go.sum
internal/cmd/about.go
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/completion.go
internal/cmd/destinations.go
internal/cmd/grants.go
internal/cmd/groups.go
internal/cmd/info.go
internal/cmd/keys.go
internal/cmd/list.go
internal/cmd/login.go
internal/cmd/logout.go
internal/cmd/providers.go
internal/cmd/testdata/expected-usage
internal/cmd/users.go
internal/cmd/version.go

We were using a fork for group support. That feature is now in an official release so we can stop using our fork. This will allow dependabot to notify us of updates.
Once this is merged we can archive https://github.com/infrahq/cobra
I tested this with the following
```
$ go build .
$ ./infra --help > before
$ go build .
$ ./infra help > after
$ go diff -u before after
```
Added a test using `golden` to show that it still looks the same.

Update cobra to official version

---

internal/access/deviceflow.go
internal/server/access_keys_test.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/deviceflow.go
internal/server/deviceflow_test.go
internal/server/models/deviceflowauthrequest.go

This PR adds the user name and organization name to the device flow login response, so that all the fields in the response are correctly populated.
Previously the `GetAccessKey` operation did not populate the `IssusedForName`. This PR fixes the function to populate that field.
Also adds a lookup of the organization from the `AccessKey.OrganizationID`, so that we can include the name in the response.

Populate names in device flow status API response

---

internal/cmd/login.go

Without this there is an error:
> Error: validation failed: oldPassword: is required
I tested this manually. An automated test would be nice, but kind of a pain since it requires interactive prompts.

Fix login with a temporary password

---

docs/api/openapi3.json
internal/server/handlers.go
internal/server/openapi.go
internal/server/routes.go

- move all api endpoints into specific categories
- hide the sign-up endpoint from the api docs
A lot of new functionality was getting grouped under the `Misc` category in our API docs. This is my attempt at cleaning things up.
Resolves #3597

maintain: api doc categories

---

api/destination.go
docs/api/openapi3.json
internal/server/data/destination.go
internal/server/data/destination_test.go
internal/server/destination_test.go
internal/server/destinations.go
internal/server/middleware.go
internal/server/middleware_test.go

Related to #3595, #3620
This PR makes `destination.UniqueID` an optional field. We need to keep it for existing connectors, but after some time we can look to remove it.  
This PR also allows connectors to send either the uniqueID or name for updating the LastSeenAt status of the destination. A new `Infra-Destination-Name` header is added for accepting the name instead of uniqueID.
See https://github.com/infrahq/internal/issues/27 for more details

Do not require uniqueID for a destination

---

internal/server/openapi.go

If you set an example in a struct but an example has already been set for that type more globally, the local example won't ever be seen. this just swaps the order of setting those so that the docs can be more descriptive.
related to #3664

fix: allow for local example to override global

---

api/types.go
docs/api/openapi3.json
uid/polymorphic.go
uid/snowid.go

When I created pr #3668 @ssoroka pointed out that my ID had the wrong format (zero's aren't allowed). But the format for that field says they are. This fixes that format in three locations to remove 0 and the lowercase L.
#3664 
#3668 
Resolves #

fix: the schema pattern for uid for api docs

---

api/access_key.go
docs/api/openapi3.json
docs/manage/connectors/kubernetes.md
docs/reference/cli.md
helm/charts/infra/templates/NOTES.txt
internal/access/access_key.go
internal/cmd/keys.go
internal/cmd/keys_test.go
internal/cmd/testdata/TestKeysListCmd/filter_by_user_name
internal/cmd/testdata/TestKeysListCmd/list_all
internal/server/access_keys.go
internal/server/access_keys_test.go
internal/server/config_test.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/schema.sql
internal/server/models/access_key.go

This change makes a number of quality of life changes to both the access keys API and CLI.
* Change access keys to make their names unique to a specific user, instead of for an entire org
* Make `infra keys list` default to the current user
* Add an `--all` flag to `infra keys list` for admins which can list all access keys in the org
* Make `infra keys add` not require a user name
* Add a `--user=` argument to `infra keys add` to be consistent with `infra keys list`
* Add a `--connector` flag to `infra keys add` to create the key for a connector
* Make `infra keys remove` to be specific to the current user
* Add a `--user=` argument similar to `infra keys list` and `infra keys add`
* Changed the API to call `DELETE /api/access-keys/:id` instead of `DELETE /api/access-keys`
* Added …

Change Access Keys API + CLI

---

Makefile

The `make docs` command was setting the version to the `99...` placeholder value from the code. Updating the command to use the correctly generated output.

maintain: update make docs to output correct version

---

internal/server/config.go
internal/server/data/migrations.go
internal/server/providers.go
internal/server/providers/azure_test.go
internal/server/providers/google_test.go
internal/server/providers/oidc_test.go

- localhost redirect not needed in provider validation
- remove example localhost redirections from tests
Clean up these references to the localhost redirect where it isn't needed on our OIDC client anymore.

maintain: remove references to local redirect

---

ui/pages/settings/access-key/add.js
ui/pages/settings/index.js

API added the new field `last used` for the access keys and it is also available on CLI. So we updated the access keys table on UI as well to expose the value of last used of access key

feat: add last used column

---

api/client.go
docs/api/openapi3.json
internal/server/grants.go
internal/server/routes.go

This reverts commit d4259e4e7657337d11c817516c2948809d7672a4.
While `GetGrant` and `GET /api/grants/:id` is not used by code in this repo, it'll be used by the Terraform provider. Removing it break that use case.

Revert "maintain: remove unused get grant endpoint (#3650)"

---

internal/access/access_key.go
internal/access/access_key_test.go
internal/access/access_test.go
internal/server/access_keys.go
internal/server/access_keys_test.go

Related to part of #3661
This PR changes the `DELETE /api/access-keys/:id` API to refuse to delete the key, if it's the key that was used to authenticate the current request. We do something similar for users (we don't allow users to delete themselves).We ran into this problem earlier in the week, and I suspect we don't want to allow this operation generally.
I did a bit of cleanup in the tests to split the `ListAccessKeys` tests from the `DeleteAccessKey` tests. That's done in a second commit, so you can look at just the first commit to see the new test case that was added.
I'll comment on some of the other cleanup inline.

Refuse to delete the access key being used by the API request

---

internal/cmd/kubernetes.go
internal/cmd/kubernetes_test.go
internal/cmd/use_test.go

create only one kubeconfig context per destination regardless if there may be multiple namespaces granted to the user.
update `use` to set the `Namespace` field of the target context.
Resolves #3611

fix: create one kubeconfig context per destination

---

.github/workflows/cd-binaries.yaml
.goreleaser.yml

Reverts infrahq/infra#3674 as it is blocking v0.18.0

Revert "improve: generate and publish openapi spec in release"

---

ui/pages/signup/index.js

After sign-up `saveToVisitedOrgs` was being called with too many parameters, which resulted in the base domain getting saved as the org name. This change fixes that problem by calling the function with the correct number of parameters.
Resolves #3702

fix: save name of org to visited orgs cookie on signup

---

ui/pages/destinations/[id]/index.js

Deduplicate role labels in access cluster drop down.
Resolves #3703

fix: unique roles in access pop up

---

internal/cmd/cmd_test.go
internal/cmd/login.go
internal/cmd/login_test.go
internal/cmd/server_test.go
internal/generate/generate.go
internal/server/middleware_test.go
internal/server/models/encryption.go
internal/testing/database/postgres.go

This PR includes 3 small changes that I made while debugging [this flaky test](https://github.com/infrahq/infra/actions/runs/3501714088/jobs/5865598897). Full details in the commit messages.
1. Use a random schema name in most tests. This is possibly the main fix for the flake (at least the ones I was seeing locally), but I don't think I can explain how this would fix CI because there should not have been duplicate schema names in any CI run.
2. Disable the `infra agent` in tests. It would have been started by login tests. This should prevent the background process from running, and prevent request goroutines from outliving the test and keeping the old schema around, with old data in it. Now that we're using random schemas this should be less of a problem, but could still cause strange …

Probably fix some test flakes

---

docs/reference/cli.md
internal/cmd/keys.go
ui/pages/settings/access-key/add.js

Change the default access key lifetime to be 1 year, with an inactivity timeout of 30 days. This means tokens that are actively in use will not unexpectedly fail in a short window.
```
infra keys add
Issued access key "test@example.com-gWf2fJwD39"
This key will expire in 1 year, and must be used every 30 days to remain valid
Key: aaa.bbb
```

maintain: default access key lifetime 1 year

---

README.md

Infra will by default give view permission to the user who made the install via UI, and not via CLI. Keeping the readme to use the CLI

update readme to give user permission

---

ui/pages/login/callback.js

If OIDC login failed for some reason, this spinner would just run forever. Update the UI to display an error if the login fails.
📸

maintain: display login error

---

internal/server/access_keys_test.go
internal/server/helpers_test.go
internal/server/migrations.go

Fixing a few bugs related to the access key migration.
* The JSON tag for `ExtensionDeadline` is `inactivityTimeout` so the migration isn't actually doing anything
* The response for `MethodPost` should be `CreateAccessKeyResponse` and not `AccessKey`
* The response for `MethodGet` is missing which should return a list of `AccessKey`s
This bug highlights a limitation of the API migrator: the type of the new response (the input into the migrator) cannot be statically checked. It's possible the data being migrated is completely off

fix: access key api migration

---

helm/charts/infra/values.yaml

match default connector https port which is 8443

maintain: update default connector http port to 8080

---

api/client.go
api/user.go
docs/api/openapi3.json
internal/access/identity.go
internal/access/identity_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/schema.sql
internal/server/data/tables_test.go
internal/server/data/user_public_keys.go
internal/server/data/user_public_keys_test.go
internal/server/models/identity.go
internal/server/routes.go
internal/server/users.go
internal/server/users_test.go

Adds a new `user_public_keys` table, support for listing users by public key fingerprint, and returning a users public keys from `GetUser` and `ListUsers`.
I think the main thing to review here are the API changes. The API changes are:
1. A new `PUT /api/users/public-key` endpoint for uploading public keys. Should we make this `/api/users/:id/public-key` and initially only accept `self` for the `:id`? I'm not sure there is ever going to be a use case for an admin uploading a public key for a different user. The admin could always create an access key for that user, and use that access key to upload the public key. This endpoint accepts two fields: a `Name` for the key (the CLI populates this with `os.Hostname()`, and the `PublicKey` which is in the form `ssh-rsa <public key>` (this is the …

Add API and data support for user public keys

---

.github/labels.yaml

We manage github labels with this yaml file.
I also added a couple of the missing kind labels, and removed the `from_name` for labels that were already renamed.

Add area/destinations/ssh label to github

---

internal/server/providers/azure.go
internal/server/providers/azure_test.go

This would result in an empty log if for some reason there was no nested error.

fix: only log nested azure error if present

---

api/client.go
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/config.go
internal/cmd/login.go
internal/cmd/ssh.go
internal/cmd/ssh_test.go
internal/server/server.go
main.go

Branched from #3620
This PR adds 2 things:
1. `infra login` now checks that `~/.ssh/config` exists and includes `Match exec "infra ssh hosts"`. If it doesn't, the file is created and these two lines are appended:
```
Match exec "infra ssh hosts %h %p"
Include ~/.ssh/infra/config
```
2. Adds the `infra ssh hosts` command does a few things:
1. tries to match the hostname and port from the `ssh [-p port] <hostname>` command run by the user to the list of destinations the user has access to. If any of them match, proceeds with the following steps. If none match then it returns immediately (which indicates to `ssh` that it should not include the `~/.ssh/infra/config` file).
2. checks if a key pair exists in `~/.ssh/infra/key`, and if it doesn't generates the key pair and uploads the public key …

Add SSH commands and integrate with login

---

api/client.go
api/client_test.go
internal/cmd/agent.go
internal/cmd/cli.go
internal/cmd/cmd.go
internal/cmd/cmd_test.go
internal/cmd/destinations.go
internal/cmd/grants.go
internal/cmd/groups.go
internal/cmd/info.go
internal/cmd/keys.go
internal/cmd/list.go
internal/cmd/list_test.go
internal/cmd/login.go
internal/cmd/logout.go
internal/cmd/providers.go
internal/cmd/testdata/expected-usage
internal/cmd/tokens.go
internal/cmd/use.go
internal/cmd/users.go
internal/cmd/version.go

When the CLI version is ahead of the server version fail fast.
```
$ infra groups list
Error: client version (0.18.1) is ahead of server version (0.18.0), download the CLI version that matches your server, reference https://infrahq.com/docs/reference/self-hosting#cli-versions
```

feat: fail when client is ahead of server version

---

.github/labels.yaml
.github/workflows/ci-core.yaml

The `-race` flag to `go test` enables the go race detector. The race detector is great for finding bugs, but also adds a lot of runtime to our test run (about 2x). This PR changes our CI so that we only run `-race` on `main` (or when the `actions/race` label is set on the PR). This should speed up test runs in most PRs, and still gives us a reliable way to catch data races.
I'll be testing the config a bit to get the condition right.

ci: only run -race on main and when there is a label

---

go.mod
go.sum
internal/cmd/connector.go
internal/cmd/connector_test.go
internal/connector/connector.go
internal/kubernetes/kubernetes.go

This PR changes the connector to load Kubernetes cluster info via standard Kubernetes loading.
The benefits of this are:
1. Less options for `infra connector`
2. Familiar: it's how most tools that connect to a Kubernetes cluster load config info and credentials
3. Support for running the connector out-of-cluster using a local kubeconfig (e.g. via `infra connector ...`)
4. Support for non-token authentication to Kubernetes clusters (probably rare, but good for local development against tools such as Docker Desktop which uses a keypair)
This PR also cleans up some unused code for now that directly require the aws sdk (a big dependency), and adds a few missing CLI arguments to make running the connector (locally and elsewhere) without needing to write out a config file.

Use standard kubernetes loading instead of custom options in the connector

---

api/grant.go
docs/api/openapi3.json
internal/server/grants_test.go
internal/server/migrations.go

The `created_by` field when creating/listing grants should be  in lower camel case (i.e. `createdBy`) similar to each of the other fields.

maintain: change grants api change_by to use lower camel case

---

internal/server/data/destination.go
internal/server/data/destination_test.go
internal/server/data/migrations_test.go
internal/server/data/types.go

@mxyng noticed this problem while trying out SSH destinations.
We previously made destination.UniqueID an optional string in the API, but because we have a unique constraint on this field, only a single destination was able to omit the uniqueID. Currently we are saving an empty string for the value.
This fixes the issue by saving a null in the field. A null omits the row from the index, which prevents the conflict on uniqueID.
We currently have a destination with an empty uniqueID in dev. That destination will either get updated on the next deploy with this change, or we can delete it.
Both of the test cases added here failed before the change.

Make destination.UniqueID an optional string in the DB

---

internal/cmd/ssh.go
internal/cmd/ssh_test.go

The match needs to be either `Match host` or `Host`. I got those mixed up in an earlier commit. I'm not sure how I missed this in manual testing, but apparently I did.
Once the experience has stabalized we'll get some end-to-end tests setup that will coverage the integration with `ssh` and `sshd`.

Fix infra ssh_config

---

internal/server/grants.go
internal/server/grants_test.go

This change fixes the `POST /api/grants` endpoint to allow it to take a user name for the subject similar to how the `PATCH /api/grants` endpoint works. Currently the endpoint will fail incorrectly with a 500 error.

maintain: allow create grants to take usernames

---

api/destination.go
internal/cmd/list.go
internal/cmd/list_test.go
internal/server/destination_test.go

Fixes #3780
Also fixes a small bug in `infra list`, so that it shows destinations of all kinds (not just kubernetes).

Prevent the creation of destinations with name infra

---

internal/cmd/connector.go
internal/cmd/connector_test.go
internal/cmd/ssh.go
internal/connector/connector.go
internal/connector/ssh.go
internal/connector/ssh_test.go
internal/linux/users.go

Branched from #3622
Note: this PR sets the default `server.url` for both connectors to `https://api.infrahq.com`
This PR makes three improvements to the ssh connector:
1. Add all the users we create to an `infra-users` group (the name is configurable in the `connector.yaml`). This will allow us to use the following sshd config:
```
Match group infra-users
AuthorizedKeysFile none
PasswordAuthentication no
AuthorizedKeysCommand /usr/sbin/infra sshd auth-keys %u %f
AuthorizedKeysCommandUser nobody
```
2. Support reading the `HostKey` setting from `/etc/ssh/sshd_config` in case they are configured to a different path. This still doesn't support every option (ex: specifying public keys in this setting).
3. Add validation for config options, so that the user gets a better error message if one …

connector: improve ssh connector install

---

internal/connector/ssh.go
internal/connector/ssh_test.go
internal/connector/testdata/bin/pkill
internal/connector/testdata/bin/userdel
internal/connector/testdata/localusers-etcpasswd-remove-failed
internal/linux/users.go

1. Instead of exiting on the first error, attempt the rest of the operations and collect the error to be returned at the end. This ensures that one user in the wrong state doesn't block the creation and delete of all other users.
2. Ignore exit status 1 from pkill. The user being removed may not be running any processes, so pkill may exit with status 1 and that's ok. In the future we can look to implement this logic in Go, which might give us more granular information about why the operation failed.
3. Kill all processes before removing any users. This may give the processes time to exit before we try to remove the user. Removing the user will fail if they still have processes running. Also use SIGKILL instead of SIGTERM, which should also speed up process exit. With the fixes above it …

Fix a few problems with local user removal in ssh connector

---

internal/cmd/sshauthkeys.go
internal/cmd/sshauthkeys_unix.go
internal/cmd/sshauthkeys_windows.go

By putting syslog behind a build flag
Test with this:
```
GOOS=windows go build .
```
It was able to build a windows binary, so I guess this worked.

Fix build on windows

---

api/client.go

This was printing the apiVersion rather than the CLI version. Fix to output the client version.

fix: print the client version in forward error

---

internal/server/openapi.go

This PR adds some validation to our OpenAPI document generation to catch when we use the wrong form of a parameter name. All our of parameters should use `camelCase` for consistently.
The document generation always runs in CI, so we'll catch this panic as a test failure in dev before merging any PRs.
I added a temporary allow list for the two fields that don't conform to the convention, which we'll remove once they are fixed.
I believe the parameter name always comes from `getFieldName`, so it should be safe to validate it here for now.
Related to #3590, and #3768

Check that all API parameters use camel case

---

.github/workflows/cd-binaries.yaml
.goreleaser.yml

There will soon be a need to publish more artifact. Replace the custom publishing actions with goreleaser which will also handle the other ways of publishing (AUR, Chocolatey)

use goreleaser to publish artifacts

---

internal/connector/ssh_test.go
internal/linux/users.go

`*` applies to `-p` as in `--password`. The current format is invalid and causes useradd to not run correctly.

fix: useradd parameter order

---

internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/schema.sql

While testing Google social login I found this index can conflict now, due to the Google login not having a provider ID. Updating the index to include the identity ID to make sure it is unique.
This index is only used by SCIM filters.

fix: index provider user emails with identity ID

---

internal/server/redis/limit.go

It's not necessary to report sub-second in over limit error

fix: truncate over limit error to seconds

---

internal/cmd/login.go
internal/cmd/login_test.go

The password prompt should not be empty

fix: require non-empty password

---

internal/server/deviceflow.go
internal/server/deviceflow_test.go

Device flow should never redirect to the base domain because it's not guaranteed it's valid. Instead, it should default to use the domain from the received request

fix: device flow base domain

---

internal/cmd/cli.go
internal/cmd/cli_unix.go
internal/cmd/cli_windows.go
internal/cmd/login.go
internal/cmd/login_test.go
internal/cmd/testdata/TestLoginCmd_TLSVerify/login_with_wrong_fingerprint

With removal of login prompts, it's become confusing when using username and password login options, in particular when set with environment variables. This PR adds a few informational outputs to help the user trace which option is currently being used.

fix: print selected login option

---

internal/cmd/kubernetes.go
internal/cmd/logout.go
internal/cmd/use.go

`cli.Stderr` should be used to write additional information to the console. https://github.com/infrahq/infra/pull/3825 adds handling for windows such that it can support ANSI style so it should be used for consistency

improve: use cli.Stderr consistently

---

internal/access/identity.go
internal/access/identity_test.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go

Right now we revoke user access keys when the OIDC session expires. This is actually not quite right, and a bit heavy handed. It may make more sense to not revoke their access keys that were created via other forms of authentication.
#3739 needs to go in for this to cover device flow provider sessions.

fix: only delete provider session on provider sync fail

---

internal/server/cookie.go
internal/server/cookie_test.go
internal/server/handlers.go
internal/server/middleware.go

Related to #2796
I found this on a stale branch, so thought I'd PR it. We were only using `gin.Context` as a way to get at the stdlib `http.Request` and `http.ResponseWriter`.
We could add `http.ResponseWriter` to our `RequestContext`, but it's used in so few places it might be better to handle it like this as separate args.

Remove gin.Context from handling of cookies

---

api/client.go
internal/cmd/ssh.go
internal/cmd/ssh_keys.go
internal/cmd/ssh_test.go

Resolves #3811
Track key pairs in a local file so that when keys are deleted or expire from the API, we can remove the local keys as well. 
This will ensure that when someone runs `ssh` for an infra destination, the Infra CLI will generate a key when necessary, and skip generating a key when one exists.
The logic in `provisionSSHKey` changes so that it uploads to the API first, and then uses the ID in the response as the filename for the key.

Improve ssh local key management

---

internal/cmd/ssh_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/user_public_keys.go
internal/server/data/user_public_keys_test.go

Branched from #3826, this PR fixes two problems:
1. we were never removing a users public keys. Now they are removed when the user is deleted.
2. the test cases in `TestProvisionSSHKey` depended on the previous test cases having run for the count of expected keys. Now that we have a way to delete the keys, the test cases no longer depend on each other.
Also two other small cleanups, renamed a data function to include the word `list` (to match other similar functions), and add a check that a `UserPublicKey` has a non-zero value for the public key before saving it.

Remove public keys when the user is deleted

---

internal/server/data/identity.go
internal/server/data/provider_test.go

- get identity pre-loading providers now returns the google social login provider also
When deleting a custom provider if a user existed via a social login also the user was removed. This was because the social login does not exist in the database and was not returned from `GetIdentity`.

fix: return social login provider for direct identity

---

internal/server/models/settings.go
internal/server/models/settings_test.go

The update password requirements endpoint incorrectly sets minimum length

fix: update password requirements

---

internal/server/data/access_key.go
internal/server/data/access_key_test.go

Add the missing `WHERE deleted_at is null` clause to two access key queries, and add test coverage for this case.
I went through the other queries, and I believe all the rest are handled correctly by either querying for IDs using `List` (which already filters out deleted items), by including `WHERE deleted_at is null`, or by doing a true delete with `DELETE`.

Only delete access keys that are not already deleted

---

internal/server/authn_test.go
internal/server/data/migrations_test.go
internal/server/deviceflow.go
internal/server/deviceflow_test.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/handlers.go
internal/server/middleware.go
internal/server/middleware_test.go
internal/server/organizations.go
internal/server/users.go

Resolves #3837
This PR  adds `AuthenticationError` to send a bit more detail about authentication failures. In some cases we don't want to provide any information, but in a few cases we can safely provide a bit more information to tell the user why the request failed.
`internal.ErrUnauthorized` will continue to log the real error at `INFO` level and return no information in the response (other than the status code), where as `AuthenticationError` will log at `DEBUG` level (like other API errors), and provide some hard coded error message to the user. The few cases I found that were safe to return more information are:
1. no authentication was provided, we can say "authentication is required"
2. the access key expired, we can say that it was expired, because the key can not be used anymore …

Add AuthenticationError to provide an error message in some cases

---

.github/workflows/cd-binaries.yaml

The expression outputs the result of the `startsWith` when ref matches a tag which is an invalid input to goreleaser. Instead, set the `--skip-publish` flag explicitly

fix: explicitly output '' when ref is a tag

---

.github/workflows/cd-binaries.yaml

`--snapshot` enables `--skip-publish`. Without `--snapshot`, the version will be determined by the Git tag

fix: disable snapshot in tag builds

---

api/settings.go
docs/api/openapi3.json
internal/access/credential.go
internal/access/credential_test.go

Add basic validation to Settings requests to prevent setting bad password requirements
Resolves #3874

fix: add validation rules to password reqs

---

internal/cmd/cliopts/flat.go
internal/cmd/server_test.go

I ran into this problem while working on #3865
A slice of structs was causing the location of the configuration value to be incorrect. There were multiple "exits" which removes the `INFRA_SERVER` item from the location. This resulting in any configuration after a slice of structs to not be loaded.
This bug impacted loading of env variables and command line flags, but only when some values were previously loaded from a config file. Using only a config file, or only env vars would have previously worked.
The test added in this commit was failing before the fix.

Fix a bug in config loading

---

internal/server/data/identity.go
internal/server/data/identity_test.go
ui/pages/settings/index.js

Cleaning up two bugs I found while testing session syncing.
1. When updating the Google provider ID I missed omitting from the providers table in the UI.
2. When a user only existed in as a Google social login all providers were returned on their user.

fix: load only social provider if not present elsewhere

---

internal/cmd/sshauthkeys.go
internal/connector/connector.go

@pdevine noticed that when his laptop resumed from suspend, the connector running in a kube pod would often stay in a disconnected state.
I believe the reason for this is a missing request timeout on the HTTP client used by the connector. We have a 1 minute timeout in the CLI, but the connector did not set a timeout.
This PR adds request timeouts to the Infra API operations performed by the connector. `sshd auth-keys` only makes short lived requests, so we can set a 1 minute timeout on the `http.Client` (like we do for other CLI commands).
The connector makes  some blocking requests, so for those calls we have to set a timeout using context. For updating grants I set the timeout to 6 minutes, which gives us 5 minutes to block on updates, and another 2 minutes to update the destination. …

Add request timeout to connector API requests

---

internal/access/credential.go
internal/access/credential_test.go
internal/server/users_test.go
ui/components/update-password.js
ui/lib/login.js
ui/pages/settings/index.js

After an error, enable the "Reset Password" button once field values are updated. Otherwise, the user needs to refresh in order to submit again.
Improve the error returned by a bad password update. The errors were previously nested inside `errors.password` as a list of strings but only the first is being displayed. This is incredibly annoying as a user as the password requirements are displayed one at a time. e.g. if  the organization requires 1 lowercase letter, 1 uppercase letter, and 1 number, only first unmet requirement will be displayed.
The change to the error string first groups all errors into a single string so it can be displayed in the UI. It then populates the error string with all password requirements, not just the unmet requirements so the user knows exactly what is …

improve: password requirements

---

internal/access/signup.go

This got missed on rebasing the "non-zero" social login provider ID change. It will now display the correct provider for the admin that signs up an org using social login.
Resolves #3905

fix: set social provider id

---

.github/workflows/cd-binaries.yaml

semver's prerelease, the part after the first `-`, is inherently a lower than the released version. `git describe` outputs `<tag>-<commits since tag>-<checksum>` so any commit after the tag will have a lower version than the tag. 
Instead, modify the output so the string is `<tag>+<commits since tag>-<checksum>` which is also a better representation of this info.
```
$ infra login infra.infrahq.lvh.me
Logging in to infra.infrahq.lvh.me
Error: client version (0.20.0) is ahead of server version (0.20.0-30-gd394a245), download the CLI version that matches your server, reference https://infrahq.com/docs/messages/cli-versions
```

fix: update version to use semver metadata instead prerelease

---

internal/connector/connector.go

The old place was wrong for two reasons, it wasn't inside the for loop, and it was being applied to the Wait. We want neither of those things.

connector: move timeout to the right place

---

ui/components/providers.js
ui/pages/login/index.js

In order to extend get a refresh token from Google additional parameters must be specified on OIDC login. This was done in the CLI but the UI was out of sync here.
Add the required parameters for Google sign-up and login to get a refresh token from Google.
This change is made in 2 places. #3909 removes the duplicate code.
Resolves #3917

fix: get refresh token on google login

---

ui/components/password-reset-form.js
ui/components/providers.js
ui/pages/accept-invite/index.js
ui/pages/login/index.js
ui/pages/password-reset/index.js

UI changes to the "accept invite" flow. Users can now choose to login with Google rather than setting a password.
This change also cleans up some duplicate `oidcLogin` functions that were a result of a rebase of the main branch onto the sign-up branch which was merged previously. 
Clean up duplicate logic: ae2103fffb283d87c09cde8fefa6c4a600eb745d
Accept invite: 86a8a3dec5e379faafa1b9b9326af7f0c1ff7b18
📸 
Follow-up for the back-end of this change in #3908
Part of #3261

feat: accept user invite by logging in with google

---

internal/cmd/cmd.go
internal/cmd/login.go
internal/cmd/login_test.go

A bad login attempt should not invalid a valid active session. This was regression caused by the `OnUnauthorized` callback which forces a logout on all `Unauthorized` API requests. It's still a good idea in most cases, just not for a bad login.
Resolves #3832

fix: no logout on bad login

---

internal/cmd/users.go
internal/cmd/users_test.go

`infra user edit` was never updated to prompt for the user's old password. For security reasons, the server rejects any password update request without the old password. Initial login for a new user does this implicitly since the user has already entered the password in the login request but this won't be available for an explicit password update.
Resolves #3882

fix: edit user password

---

internal/cmd/kubernetes.go
internal/cmd/use_test.go

`infra use cluster` with a cluster unsets context namespace which isn't expected. Instead if the namespace isn't specified, only switch the context. If a namespace is specified, set the namespace accordingly.

fix: only set namespace if specified in use

---

internal/cmd/agent.go
internal/cmd/kubernetes.go
internal/cmd/kubernetes_test.go
internal/cmd/list.go
internal/cmd/login.go
internal/cmd/use.go

Only K8s destinations should get entries in kubeconfig.
Resolves #3920

fix: only template out kubeconfig for k8s destinations

---

ui/pages/destinations/[id]/index.js

Use PATCH /api/grants to bulk add grants. This is particularly useful when adding grants for a large number of resources such as namespaces.
Relates #3944

fix(ui): bulk add grants

---

ui/pages/destinations/[id]/index.js

Use PATCH `/api/grants` to bulk remove grants. In contrast to adding grants, only multi-select remove uses this API. Other removals, cluster-wide and remove from the dropdown menu continue to use existing DELETE `/api/grants`.
Relates #3952
Relates #3944

fix(ui): bulk remove grants

---

.github/workflows/ci-core.yaml

The e2e test suite was not running because its go.mod was not tidy. This workspace should inform Go to use the go.mod from the parent module.
Example failure on main: https://github.com/infrahq/infra/actions/runs/3839811288/jobs/6538079495

Fix CI failure in acceptance tests

---

ui/pages/destinations/[id]/index.js

default page is 100 which may not be enough to display grants for multiple namespaces, roles, users. the result can be extremely confusing since there's no way to see multiple pages
simply increasing the limit isn't ideal since it's just delaying the problem but there's no way to disable paging at the moment

fix(ui): display more grants

---

.goreleaser.yml
test/docker-compose.yaml
test/dockerfiles/Dockerfile.debian
test/dockerfiles/Dockerfile.redhat
test/dockerfiles/install-debian.sh
test/dockerfiles/install-redhat.sh
test/dockerfiles/server.yaml
test/setup.sh
test/ssh_test.go

Adds `debian:11-slim` and `redhat/ubi9:latest` destinations, and runs the same tests against them.
A few small changes were required, comments inline

Add debian and redhat destination to SSH acceptance tests

---

internal/cmd/ssh.go
internal/cmd/ssh_test.go

@pdevine realized that if someone has an SSH key called infra, it's possible that key exists at `~/.ssh/infra`, which would prevent us from using that path as a directory. The error message would be hidden from users, so they wouldn't understand why their SSH was prompting them for either a password or to verify the host key.
This PR fixes that problem by:
1. improving the error message in this case, making it explicit that there is a file in the way
2. actually printing this error message to stderr (instead of hiding it in debug logs)
I created #3927 for the remaining problems

Improve error output from infra ssh

---

internal/access/access_test.go
internal/access/identity.go
internal/access/identity_test.go
internal/server/authn/oidc.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/provideruser.go
internal/server/data/provideruser_test.go
internal/server/deviceflow_test.go
internal/server/handlers.go
internal/server/middleware.go
internal/server/providers.go
internal/server/routes.go
internal/server/server.go
internal/server/server_test.go
internal/server/signup.go
internal/server/signup_test.go
internal/server/tokens_test.go
internal/server/users.go
internal/server/users_test.go

- sync user session from external IDPs in middleware
- add sync cache for 120 minutes
- remove explicit IDP sync on token creation, this will slow the propagation of IDP changes
- attempt to make user sync logic easier to follow
If a user's session in a provider was expired on device login this wasnt checked until an `infra tokens add` command was run. Check the user's session in the IDP on device flow login via the middleware, and get them to log back in if its gone stale, then they can proceed with the device flow as normal.
1. `infra login`
2. Users session is validated with IDP
3. If session is no longer valid, user must login again (in the browser)
4. User is returned to device flow and continues as usual
Part of #3881

fix: check user idp session on device login

---

ui/next.config.js

This reverts commit f348d378cf079a65ad4c1c1604cbcaa89492b2f9, reversing changes made to 6ccc4937960eb784e4b2fae60e939d4e9a25bca8.
Reverting this as it introduces a breaking bug on Chrome

Revert "Merge pull request #3961 from infrahq/mxyng/csp-directives"

---

ui/pages/destinations/index.js
ui/pages/settings/index.js
ui/pages/settings/providers/add.js

- fix redirect path in the setting page
- add delete button on the destination page when the infrastructure type is `ssh`

fix: direct path fix and ssh improvement

---

internal/cmd/server.go
internal/cmd/server_test.go
internal/server/data/data.go
internal/server/data/encrypt/keys.go
internal/server/data/encrypt/seal.go
internal/server/data/encrypt/seal_test.go
internal/server/data/encryption_key.go
internal/server/models/encryption.go
internal/server/models/encryption_test.go
internal/server/server.go
internal/server/server_test.go
internal/testing/patch/patch.go

In #1653 secrets were extracted to a library. Part of the logic that moved to that library was sealing and unsealing of sensitive values that are stored in the database.
This PR moves just the bits used for database encryption at-rest  from `github.com/infrahq/secrets` to `./internal/server/data/encrypt`. We don't need this code in a library since it's only used in this one place, and moving it inline makes it easier to change.
At the same time the implementation is reduced a bit by removing "key providers". Instead, the "native key provider" implementation is used, which reads the root key from a file. I believe this is the only mechanism that we are using for the root key. We can support other mechanism in the future using the same mechanism we do for other secret values (load from env …

Inline and reduce database encryption at-rest logic

---

api/organization.go
internal/validate/string.go
internal/validate/string_test.go

To protect an org from being incorrectly configured block "gmail.com" and "googlemail.com" allowed domains.

fix: no gmail allowed domains

---

internal/access/access.go
internal/server/data/access_key.go
internal/server/data/destination.go
internal/server/data/destination_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/middleware.go
internal/server/middleware_test.go

Fixes #3944
This PR fixes the request latency by avoiding the database row lock that was causing the contention. The `UPDATE` queries for `LastSeenAt` are changed to use `WHERE id IN (SELECT ... FOR UPDATE SKIP LOCKED)`.  If two requests are received at roughly the same time, the first request to run `UPDATE` will perform the update. The second request will match no rows, so won't acquire a lock. These new queries also use `WHERE updated_at = ?` to prevent clobbering previous updates.
We use this same pattern in 3 places: access keys, users, and destinations. This PR updates all 3 to use the same approach.
There is one more small bug fix in here as well.  I'll add more comments inline to explain the changes. 
The first commit in this PR attempted to fix the problem by removing the …

Fix latency caused by high volumes of requests from the same user

---

api/user.go
docs/api/openapi3.json
internal/cmd/ssh.go
internal/server/data/identity_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/schema.sql
internal/server/data/user_public_keys.go
internal/server/data/user_public_keys_test.go
internal/server/models/identity.go
internal/server/server.go
internal/server/users.go
internal/server/users_test.go

Adds a 12 hour expiration time to all SSH keys that are uploaded to the API. We could make this longer, but 12 hours seems like long enough to avoid having to wait for multiple keys to be created in a single work day.
Expired keys are never returned by the API. A new background job soft-deletes the keys once they expire.
I also noticed that I had missed an index of `user_public_keys.user_id` which is used by `listUserPublicKeys`, so I added a migration for that as well.
Resolves #3812

Add a default expiration time to all user public keys

---

docs/dev/api-versioned-handlers.md
internal/server/backgroundjobs.go
internal/server/backgroundjobs_test.go
internal/server/handlers_test.go
internal/server/routes.go
internal/server/server.go

I missed these in earlier PRs. Best viewed by individual commit.
1. Make the test for versioned handlers more reliable by allowing it to get the map of handlers from `GenerateRoutes`. This should always match production and avoid the scenario where someone forgets to update the test.
2. Remove another function for background jobs, and pass the jobs directly to `group.Go`.

Two small improvements to api server

---

internal/cmd/connector_test.go
internal/cmd/helpers_test.go
internal/cmd/kubernetes_test.go
internal/cmd/list_test.go
internal/cmd/login_test.go
internal/cmd/server_test.go
internal/cmd/ssh_test.go
internal/cmd/sshauthkeys_test.go
internal/cmd/users_test.go
internal/server/config.go
internal/server/config_test.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/provider.go
internal/server/data/provider_test.go
internal/server/helpers_test.go
internal/server/options_migrations.go
internal/server/server.go
internal/server/server_test.go
test/dockerfiles/server.yaml
test/go.mod
test/go.sum

Implements most of what was proposed in #3915. 
Not done, still pending further discussion:
* `User.Password` has not been removed - it's used by helm
* `SupportAdminGroups` has not been added yet
* the access key expiration time is still set to 10 years
I'd like to address those in separate follow up PRs. 
If a self-hosted install of Infra includes `grants` or `providers`  the server will refuse to start and the error message will inform the user what needs to change.
Helm changes in https://github.com/infrahq/helm-charts/pull/17

Reduce server config to only bootstrapping of user and credentials

---

internal/server/data/destination.go
internal/server/data/destination_test.go
internal/server/data/grant.go
internal/server/data/grant_test.go
internal/server/destination_test.go

This change removes any grants for a destination when the destination is deleted.
Resolves #3800

delete grants for a destination when deleting the destination

---

internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/provider.go
internal/server/server.go

Add some checks to prevent deleting more access keys than were intended, also add some logging to track down a bug where access keys are removed unexpectedly.

maintain: additional protection around access key removal

---

internal/cmd/grants.go
internal/cmd/users.go
internal/cmd/users_test.go

- gotos make it harder to trace the code so replace them with loops
- remove most password validation since it will be done by the server

maintain(cmd): simplify user password prompt

---

internal/server/data/identity.go
internal/server/data/identity_test.go

If there are 2 groups with the same name returned for a user, then a duplicate group error would be returned on group creation. Prevent this by removing duplicate group names.

fix: remove duplicate group names

---

internal/server/cookie.go
internal/server/cookie_test.go
internal/server/handlers.go
internal/server/middleware.go

When logging out on an `http` connection the cookie is not cleared, check if the incoming request is secure to clear this cookie.
Resolves #4003

fix: remove non-secure cookies on logout

---

internal/cmd/cliopts/config.go
internal/cmd/cliopts/hooks.go
internal/cmd/kubernetes_test.go
internal/cmd/login_test.go
internal/cmd/server_test.go
internal/server/config.go
internal/server/config_test.go
internal/server/helpers_test.go

Branched from #3951, related to https://github.com/infrahq/infra/issues/2186
Fixes #3333
This PR restores support for loading passwords and accessKeys from `file:`,  `env:`, or `plaintex:` prefix. Unlike the previous implementation, this one only handles those prefixes, so someone using a password that contains a colon will not be encounter an error about an unknown secret provider.
This new implementation is also much smaller (just 20 lines). If we find another solution for the bootstrap user we may be able to remove these in the future as well.
Also removes a mapstructure decode hook that was no longer used after the changes in https://github.com/infrahq/infra/pull/3950

Restore backwards compatibility for bootstrap config passwords and accessKeys 

---

dev/server.yaml
test/docker-compose.yaml

The config used by `test_acceptance` and `dev/server.yaml` had `file:` prefix for the TLS CA private key, which need to be updated for the changes from #3951

Fix configs that used file: prefix

---

ui/pages/settings/index.js

- Add placeholder text before input
- Adding first domain does not change this size of the input box
- Adding many domains wraps to a new line rather than squishing the domain tag
- No flash of domain disappearing after hitting enter
📸 
Resolves #3968

fix: minor ui issues with allowed domains

---

api/client.go
api/user.go
docs/api/openapi3.json
internal/access/credential.go
internal/access/credential_test.go
internal/access/identity.go
internal/access/passwordreset.go
internal/server/email/sendgrid.go
internal/server/passwordreset.go
internal/server/passwordreset_test.go
internal/server/users.go
internal/server/users_test.go

`UpdateUser` is actually just `UpdateCredential` since no other user field is currently modifiable. There are two modes for `UpdateCredential`: 
1. Update the caller’s user credential. This does not require special authorization.
2. Update another user’s credential. This requires admin authorization.
To support these modes, there are 6 `isSelf` checks between `access.UpdateCredential` and its helper `access.updateCredential`. This makes it very difficult to trace the code. 
In total there are 3 use cases where update credential is needed:
1. A user wants to change their own password. The current password must be provided and verified against the database
1. A user wants to reset their password out-of-band through email verification. The current password is unknown so it cannot be verified …

refactor: update user/credential

---

ui/components/layouts/dashboard.js
ui/components/layouts/login.js
ui/lib/hooks.js

Fixes #3985 
While https://github.com/infrahq/infra/pull/4014 cleared some data, errors would still be cached causing flashes of content on logout and in some remaining cases, on login.
This PR simplifies the redirect logic as well: components can now choose where to redirect users, instead of it automatically happening in `useUser` hook.

Completely clear cache on login and logout

---

internal/access/passwordreset.go
internal/server/passwordreset_test.go
internal/server/users.go
internal/server/users_test.go
ui/pages/users/index.js

Right now when an admin creates a user by email invite, the provider user and credential are created immediately even though a user may not accept the invitation. With this change, only create the provider user and credential when the end user accepts the invite.
Note: this is only applicable when a SMTP server is configured.
Update the UI to allow removing a user that's been invited but hasn't accepted the invite. 
1. Current user - user cannot be deleted
2. Okta user - user cannot be deleted
3. Invited user, accepted - user can be delete
4. Invited user, not accepted - user can be deleted
Resolves #3908

fix: delay creating provider user

---

internal/access/identity.go
internal/server/data/access_key.go
internal/server/data/access_key_test.go
internal/server/data/identity.go
internal/server/data/identity_test.go
internal/server/data/provideruser.go
internal/server/users_test.go
ui/pages/users/index.js

- allow removing users from your org regardless of where they have logged in from
- remove some previously enforced key deletion requirements which are not needed
- simplify delete identity references
Allow removing users completely from Infra (right now you can only remove the Infra user). This is needed because if you invite someone and they sign in through Google, then you can’t actually remove the user from your Infra org without going and finding all their grants to remove.
Part of #4033

maintain: allow removing any users for an org

---

internal/cmd/ssh.go
internal/server/handlers.go
internal/server/providers.go
internal/server/routes.go
internal/server/signup.go

We are currently using a fork of `gin` to support decoding of types that implement `encoding.TextUnmarshaler`.
This PR takes a few small steps to reduce our use of `gin.Context`, and to replace our fork with upstream `gin`.
Full details in the commit messages, but in summary:
1. use `context.Context` directly from the `http.Request.Context()` instead of using `gin.Context` (which implements `context.Context`). `gin.Context`'s implementation of `context.Context` is error prone, and doesn't actually provide the correct context value in some cases (which I didn't bother to debug, because there's really no reason to be using `gin.Context` as a `context.Context`).
2. remove the unnecessary indirection in `readRequest`. `ShouldBind` is replaced with the methods that were called eventually after …

Reduce the use of gin.Context - part 1

---

internal/connector/connector.go
internal/connector/proxy.go
metrics/metrics.go

The connector doesn't require a full framework. The stdlib provides everything we need to implement these handlers.
Related to https://github.com/infrahq/infra/issues/2796, and https://github.com/infrahq/internal/issues/19

Remove use of `gin` in the connector

---

internal/connector/proxy.go

I missed a label in the metric, which caused a panic:
```
http2: panic serving 127.0.0.1:35828: inconsistent label cardinality: expected 5 label values but got 4 in prometheus.Labels
```
I would have liked to add test coverage for this change, but unfortunately we don't have any way of getting the dynamically allocated port from `:0` in the connector. The server is setup to do this, so we'll have to use that approach in the connector to support testing the proxy.
I tested this manually with a local setup. There is no longer a panic after this change.

Fix HTTP metric in connector proxy

---

.github/workflows/cd-containers.yaml

buildkit 0.11.0 generates provenance attestation by default. disable it for now.

fix: disable provenance for docker build

---

.github/workflows/cd-containers.yaml

argocd-image-updater exits 0 even if the image update fails. This is likely due to its intended role as a service. In order to determine if the service has had an error, consult the log output. 
Note: log format changes if it's being piped and errors are printed to `stderr`
```
$ argocd-image-updater run --once --match-application-label=ci.infrahq.com/component=core; echo $?
INFO[0000] argocd-image-updater v0.12.1+16cff2e starting [loglevel:INFO, interval:once, healthport:off]
WARN[0000] commit message template at /app/config/commit.template does not exist, using default
WARN[0000] Registry configuration at /app/config/registries.conf could not be read: stat /app/config/registries.conf: no such file or directory -- using default configuration
INFO[0000] ArgoCD configuration: …
```

fix: sanity check kubeconfig

---

internal/cmd/keys.go

Add a suggestion in the `infra keys remove ...` command to suggest using the username flag when no access key is found for a name.
Add a `--connector` flag to match the format of `infra keys add --connector`.
```
$ infra keys remove test 
No access key named 'test' for the current user, another user can be specified with the '--user' flag
$ infra keys remove test --user another@example.com
No access key named 'test' for the user 'another@example.com'
$ infra keys remove --help
Delete an access key
Usage:
infra keys remove KEY [flags]
Aliases:
remove, rm
Flags:
--connector     Remove a key for the connector
--force         Exit successfully even if access key does not exist
--user string   The name of the user who owns the key
Global Flags:
--help                 Display help
--log-level …
```

Keys remove command improved error message and connector flag

---

internal/access/access_test.go
internal/cmd/login_test.go
internal/cmd/server_test.go
internal/server/authn/authn_method_test.go
internal/server/data/data_test.go
internal/server/data/migrator/migrator_test.go
internal/server/middleware_test.go
internal/server/models/encryption_test.go
internal/server/server_test.go
internal/testing/database/postgres.go

To ensure that tests don't fail because of a schema name that is too long.
Remove a redundant underscore.
Reduce the length of the longest ones.
Add a check to prevent accidentally using one that is too long.

Improve schema names used for testing

---

internal/cmd/ssh.go
internal/cmd/ssh_keys.go
internal/cmd/ssh_test.go

Fixes #4048
There were two bugs in the same place that could cause the wrong files to be deleted, or in the worst case a panic.
The first bug was the `for` loop was iterating over the `existingKeys` slice, but deleting from a different slice using the loop index variable. This meant that in some cases the wrong local key file (one for a different server, or different org) would be deleted.
This bug is fixed by no longer creating a separate slice. Iterate over the main slice, and skip entries as necessary.
The second bug was that we kept deleting using that index variable, even after having deleted previous entries. If there were at least 2 deletes then our index would be out of range and cause the panic.
This bug is fixed by only incrementing the index variable when we skip entries. When …

Fix panic in infra ssh command

---

internal/access/request.go
internal/server/debug.go
internal/server/deviceflow.go
internal/server/errors.go
internal/server/errors_test.go
internal/server/handlers.go
internal/server/logging.go
internal/server/logging_test.go
internal/server/routes.go
internal/server/signup.go

Removes the use of `gin.Context` from a few places in the `server` package:
* accessing the `http.Request`
* using the `http.ResponseWriter` directly
* for log context
Related to https://github.com/infrahq/infra/issues/2796, and https://github.com/infrahq/internal/issues/19

Reduce the use of `gin.Context` in `server` package

---

internal/connector/connector.go
internal/logging/logger.go
internal/server/server.go

Previously they were output with a nil level, this change outputs the logs at warning level.
Warning seems appropriate because we get a lot of noise in these logs for bad TLS requests. 
In the future we could add some logic to inspect the messages and use `Error` for panics, but for now I'm hoping a warning level is better than no level.
https://github.com/rs/zerolog/issues/508 is an issue to add this support to `zerolog`, but it ended up being easy enough to do from our code.
I tested this manually by curling the HTTP server without trusting the CA certificate. I saw a log message with level=WARN.

Add level to HTTP error logs

---

ui/pages/signup/callback.js

In some rare cases (signing up across different environments) not removing the "redirectURL" cookie after sign-up would cause the redirect to take the user to whatever org they signed up with previously. Removing the "redirectURL" cookie after sign-up ensures that the user is always redirected to the org they just created.

fix: remove signup redirect cookie after sign-up finishes

---

api/signup.go
internal/access/credential.go
internal/access/credential_test.go
internal/access/passwordreset.go
internal/server/signup.go
internal/server/signup_test.go

Check password policy when signing up with username and password. The signup endpoint previously was not using the same password policy checker as every other similar endpoints. This means when the bad passwords checking was added in #3963, signup was missed.
Resolves #4076

fix: check password policy for username/password signup

---

docs/dev/api-versioned-handlers.md
internal/server/access_keys.go
internal/server/signup.go

@BruceMacD noticed that in cases where we create a versioned API request struct we were not applying validation rules, because the versioned structs did have any rules.
To ensure that we apply the right request validation this PR adds the missing calls to `validate.Validate`,  and updates the docs so that we don't forget in the future.
Resolves https://github.com/infrahq/internal/issues/41

Call validate in versioned handlers

---

internal/server/authn_test.go
internal/server/debug_test.go
internal/server/grants_test.go
internal/server/groups_test.go
internal/server/helpers_test.go
internal/server/login_test.go
internal/server/organizations_test.go
internal/server/routes_test.go

Use `apiVersionLatest` consistently in tests unless explicitly testing a previous version since using non-latest versions can produces unexpected failures when changing the API.

use latest api version unless testing a previous version

---

api/client.go
api/client_test.go

Infra API is tightly coupled with the API client since its structs are used in the API handlers and also used to generate API docs. This means any changes to the API requires changing the API client so it doesn't make sense to pin the JSON format to anything other than the version implemented by the server.
Note: this version gets set to git tag when building a release so released builds won't see any change.

use latest version in api/client.go

---

internal/server/passwordreset_test.go
internal/server/users.go
internal/server/users_test.go

Email invite can be sent to a user who already has a password setup. This regression introduced in #4012 which changed when a user credential was created. Previously creating a user unconditionally creates the user credential which would fix any duplicates when saving to the database. 
Since the linked changed, credentials are created for the invited user only when they accept the email invite. The missing piece is checking for duplicate credentials _before_ sending the invite.
This change does not affect re-sending an invite before the target user has accepted.
The behaviour for non-email user creation is unaffected.
Resolves #4079

fix: invite when user exists

---

api/grant.go
docs/api/openapi3.json
internal/server/grants_test.go

This value as a JSON field in the response is unnecessary since the HTTP status code can be used to determine if the request was effective or not. The only place where this may be useful is in the bulk request where each grant is tagged with `wasCreated`. Removing `wasCreated` from this response makes it harder to determine if a particular grant has been created but since nothing is checking that value right now, it doesn't seem very important.

remove unused wasCreated field value from grants response

---

internal/cmd/connector_test.go
internal/connector/connector.go

This PR adds a test that fails without the changes from #4050.
I think the approach we use in the server is better in general, but that would require some major changes to the connector. This PR takes an easier approach by requiring the caller to opt-in.

Add test coverage for connector proxy

---

api/types.go
go.mod
go.sum
internal/openapi3/openapi3.go
internal/openapigen/main.go
internal/server/handlers.go
internal/server/openapi.go
internal/server/openapi_test.go
internal/server/routes.go
internal/validate/date.go
internal/validate/email.go
internal/validate/email_test.go
internal/validate/numbers.go
internal/validate/numbers_test.go
internal/validate/slice.go
internal/validate/string.go
internal/validate/string_test.go
internal/validate/validate.go
uid/snowid.go

We only used this library for the struct definitions to mirror the openapi 3 specification. In #4061 dependabot failed to update this dependency because of new unexported fields on those structures.
The commit history here is a bit messy, just saving progress as I go. Probably best viewed as a single diff, and I may remove the intermediate history when I merge.
We don't need much of the complexity in the internal structure (custom json encoding, external references, etc), and we don't use any of the other code in this library.
This PR removes the dependency, and replaces it with a few struct definitions. I omitted a few of the fringe fields that we don't use and are unlikely to ever use. There are still plenty of fields we could trim, but we could also keep them since it's more likely we …

Remove kin-openapi

---

internal/server/access_keys.go
internal/server/configuration.go
internal/server/debug.go
internal/server/destinations.go
internal/server/deviceflow.go
internal/server/forgotdomain.go
internal/server/grants.go
internal/server/groups.go
internal/server/handlers.go
internal/server/logging.go
internal/server/organizations.go
internal/server/passwordreset.go
internal/server/providers.go
internal/server/redirect.go
internal/server/routes.go
internal/server/routes_test.go
internal/server/scim.go
internal/server/signup.go
internal/server/users.go
internal/server/users_test.go

Replace `gin.Context` with `RequestContxt` in API handlers. 
After this change, the only place we're using `gin.Context` is in the middleware for logging/metrics, the router, and binding.
Resolves #2796

Remove gin.Context from API handlers

---

api/grant.go
docs/api/openapi3.json
internal/server/grants_test.go

This reverts commit 62fd302adc6464554c2753240e05ef51830210c7, reversing changes made to 9a7346f604427676e1dd512c41431d343192ec7d.
It appears I was a bit hasty removing this field. It's being used to let the caller of `api.CreateGrant` know if the grant is actually created. This is in lieu of checking the status code directly, which the API client does not expose. It's still a good idea to remove this field but some refactoring needs to be done first to all an API client user to check the status code.

Revert "Merge pull request #4091 from infrahq/mxyng/rm-unused-grants-field"

---

internal/server/data/access_key.go
internal/server/middleware.go
internal/server/middleware_test.go

It's hard to debug when an access key becomes invalid due to not being used. Add some extra context to error messages to help with that.
Resolves #4100

maintain: specify when access key use fails due to timeout

---

internal/server/data/identity_test.go
internal/server/data/migrations.go
internal/server/data/migrations_test.go
internal/server/data/provideruser_test.go
internal/server/data/schema.sql
internal/server/models/provideruser.go
internal/server/models/types.go

Update group tracking to use a JSON binary in the database, rather than a text field separated by commas. This allows for storing group commas.
Resolves #3138

fix: allow group names with commas

---

ui/pages/groups/[id].js

Groups page was not paginating correctly, this was due to an incorrect query param.

FIX: paginate groups
