internal/cmd/login.go, internal/cmd/tokens.go
Remove `relogin()` since even tokens already exits with an error if the session is no longer valid.
Resolves #
=> maintain: remove relogin

docs/reference/cli-reference.md, go.mod, go.sum, internal/cmd/about.go, internal/cmd/cmd.go
Add "about" command for Easter.
=> feat: add about command

CODEOWNERS
Adding bare minimum `CODEOWNERS`. This will allow the repo to enable review assignment based on how owns each section. Specifics to be filled in
=> improve: add CODEOWNERS

.github/release-please.json
Path was updated but config was not
=> fix: version bump path

.github/workflows/release.yml
=> fix: docs build

.github/codeql-config.yaml, .github/workflows/human_pull_request.yml, .github/workflows/pull_request.yml, .github/workflows/release_pull_request.yml
Add codeql to pull requests so we get early feedback on code changes. Can be replaced at any time with other static analysis tools. Analysis will run in the release pull request and will need to pass in order to merge the PR and release. 
Refactored pull request actions into separate files: 
- `pull_request.yml` for common actions
- `release_pull_request.yml` for release-only actions
- `human_pull_request.yml` for human-created pull requests, i.e. not `dependabot`.
=> improve: add codeql code analysis

docs/connectors/kubernetes.md, docs/reference/helm-chart.md
=> maintain: update docs

internal/server/data/migrations.go, internal/server/server.go, pki/native.go
removing some TODOs where possible.
=> chore: remove a couple todos

internal/cmd/server_test.go
fixes test that fails periodically. Test was misconfigured.
Resolves https://github.com/infrahq/infra/issues/1632
=> fix: flakey test fix

docs/reference/cli-reference.md, internal/cmd/destinations.go, internal/cmd/grants.go, internal/cmd/identities.go, internal/cmd/identities_test.go, internal/cmd/keys.go, internal/cmd/providers.go
Updates help messages 
None, only cmd help messages were modified
=> improve: updates help for all commands

internal/server/middleware.go, internal/server/middleware_test.go, internal/server/routes.go
timeout both requests and db transactions.
Resolves #
=> feat: add request timeouts

api/access_key.go, api/client.go, api/identity.go, docs/api/openapi3.json, internal/access/access_key.go, internal/access/identity.go, internal/access/identity_test.go, internal/cmd/info.go, internal/cmd/keys.go, internal/server/data/selectors.go, internal/server/errors.go, internal/server/handlers.go, internal/server/handlers_test.go, internal/server/models/access_key.go
Format keys list output
```
$ ./infra keys list     
NAME        ISSUED FOR                 CREATED        EXPIRES            EXTENSION DEADLINE  
6pmZ7QVjoU  steven.soroka@infrahq.com  6 minutes ago  12 hours from now  never               
```
Resolves #1255
=> feat: format infra keys list with user name

.github/ISSUE_TEMPLATE/docs_issue.md
When a docs issue is found is it a bug report or feature request?? not really. And the page URL and browser is pretty important. So lets have a new template for docs issues
Resolves #
=> maintain: create issue template for documentation issues

internal/access/signup.go, internal/access/signup_test.go
Need a ProviderUser for the signup user
=> fix: create provider user for signup user

helm/charts/infra/templates/connector/configmap.yaml, helm/charts/infra/templates/connector/deployment.yaml, helm/charts/infra/templates/connector/secret.yaml, helm/charts/infra/templates/server/configmap.yaml, internal/certs/certs.go, internal/cmd/cmd.go, internal/cmd/kubernetes.go, internal/connector/connector.go
=> fix: cluster-specific ca for generating connector certificates

helm/charts/infra/templates/server/_helpers.tpl, helm/charts/infra/templates/server/configmap.yaml
Template returns value as string which is truthy. Instead compare string value against `true`
Resolves #1730
=> fix: connector access key not found when connector is disabled

ui/components/grant.js, ui/pages/destinations/index.js
- the cluster share user list is sorted by user id, so the list will not reorder when update the role
- change text grant to share
Resolves #1711
=> fix: user list is sorted on create and update

ui/lib/providers.js, ui/pages/login/index.js, ui/pages/providers/add/details.js
1. remove okta url validation - it should be done at the backend. 
2. add a fullback text `SSO` on login page if kind of provider is undefined
Resolves #1707
=> fix: non-okta providers show broken image

go.mod, go.sum, internal/cmd/cliopts/config.go, internal/cmd/cliopts/config_test.go, internal/cmd/cliopts/flat.go, internal/cmd/cliopts/hooks.go, internal/cmd/cmd.go, internal/cmd/server.go, internal/cmd/server_test.go, internal/server/config.go, internal/server/config_test.go
This is passing the tests we have, but our test coverage is not great in this area, especially for the connector. I'll write a few more before this is ready.
=> Replace viper with cliopts.Load

internal/server/handlers_test.go
@BruceMacD was exactly right about the cause! This test case relied on a previous one running first. It was easy to reproduce by running the one test case by itself.
The flaky test case was using the admin access key and relying on a previous test case running first to set the `LastSeenAt`. This commit fixes the problem by using an access key for the identity being queried. So the request in the test case sets `LastSeenAt`, and it will always be a recent time.
Resolves #1756
=> maintain: fix a flaky test

docs/api/guidelines.md
First draft of API Development Guidelines
=> improve(docs): First draft of the API development guidelines

ui/components/empty-table.js, ui/components/grant.js, ui/components/input.js, ui/components/layouts/dashboard.js, ui/components/modals/delete.js, ui/components/modals/fullscreen.js, ui/components/modals/info.js, ui/components/table.js, ui/pages/destinations/add.js, ui/pages/destinations/index.js, ui/pages/login/finish.js, ui/pages/login/index.js, ui/pages/providers/add/details.js, ui/pages/providers/add/index.js, ui/pages/providers/index.js, ui/pages/settings/admin.js, ui/pages/settings/index.js, ui/pages/signup/index.js, ui/styles/globals.css, ui/tailwind.config.js
**Typography**
1. Fonts feel massive and there are several weights being used differently throughout the application. All type should have font weight `normal` display as primary or secondary colors (page headers are the only exception).
- Primary = #FFFFFF
- Secondary = #B2B2B2
- 16px Page headers / modal headers / empty state headers
- 14px or 13px base height for every text input everywhere
- 12px for table headers
**Borders**
adjust borders to be 1px everywhere in ui
**Inputs**
add padding top and bottom to make them feel less massive
Resolves #1731
=> fix: general ui bugs

helm/charts/infra/values.yaml
Removing dead links from helm chart. Updating where possible. 
Resolves #1856
=> fix: remove and update helm links

README.md
update links for readme to use our docs site.
=> improve: update links for readme

api/client.go, api/client_test.go, internal/server/apimigrator.go, internal/server/apimigrator_test.go, internal/server/handlers.go, internal/server/handlers_test.go, internal/server/migrations.go, internal/server/routes.go, internal/server/version.go
=> feat: add api migration

uid/snowid.go, uid/snowid_test.go
Some minor cleanup and improvements to the tests in the `uid` package. Follow up to  #1867
=> improve: small improvements to uid tests

internal/server/data/destination_test.go, internal/server/models/model.go
=> fix: `created_at` no longer zeros on save

ui/components/grant.js, ui/components/header-icon.js, ui/components/input.js, ui/components/modals/delete.js, ui/jest.config.js, ui/pages/_app.js, ui/pages/destinations/add.js, ui/pages/login/index.js, ui/pages/settings/admin.js, ui/pages/settings/index.js, ui/pages/signup/index.js, ui/tailwind.config.js
update the login and signup layout 
Resolves #1915
=> feat: login layout updates

api/login.go, docs/api/openapi3.json, internal/cmd/login.go, internal/server/handlers.go, internal/server/handlers_test.go, internal/server/migrations.go
Mutate the APIs requesting/responding with polymorphic IDs for backwards compat
Resolves #1859
=> fix: polymorphic ID api migration

internal/server/apimigrator.go, internal/server/apimigrator_test.go
to avoid requiring devs to edit old rewrites, support redirects that update old rewrites themselves
=> fix: support redirecting previous path rewrites

api/destination.go, docs/api/openapi3.json, internal/cmd/grants.go, internal/cmd/grants_test.go, internal/connector/connector.go, internal/kubernetes/kubernetes.go, internal/server/handlers.go, internal/server/models/destination.go
Update the destinations API to allow the connector to report its capabilities (e.g. resources and roles)
Resolves #1818
=> feat: add resources/roles to destinations api

docs/api/openapi3.json, internal/server/openapi.go
=> fix: readme-compatible openapi spec

docs/api/openapi3.json, internal/server/openapi.go
=> improve: categorize openapi user endpoint properly

docs/getting-started/quickstart.md, docs/guides/granting-access.md, helm/charts/infra/templates/NOTES.txt
Fixes https://github.com/infrahq/infra/issues/1957
=> fix: documentation fixes

api/client.go, internal/cmd/cmd.go, internal/cmd/login.go
Resolves https://github.com/infrahq/infra/issues/1965
=> fix: client requests should time out

CODEOWNERS
=> maintain: new codeowners

internal/cmd/destinations.go, internal/cmd/keys.go
infra keys rm: Inform users of removal only after successful removal
infra dst rm: Add message to inform users destination was removed
=> maintain: only output actual removals

ui/pages/users/add.js
Fixes some minor style change issues missed at review in #2038
=> fix: ui users add fullscreen layout fixes

ui/components/admin.js, ui/components/modals/delete.js, ui/pages/destinations/index.js, ui/pages/providers/index.js, ui/pages/users/index.js
This removes the `onCancel` prop for `DeleteModal` and fixes a missing `setOpen` prop
=> fix: missing delete modal setOpen props

ui/components/grant.js, ui/components/input.js, ui/components/modals/delete.js, ui/components/resources-grant.js, ui/pages/users/add.js, ui/pages/users/index.js
- new deletion modal
- api migration
- filter groups on destination access
- filter `connector` on user management 
Resolves #2039
Resolves #2027
=> fix: a few bugs on grants and deletion

ui/pages/destinations/index.js, ui/pages/users/index.js
=> fix: ui showing NaN in relative time fields

helm/charts/infra/values.yaml, internal/cmd/server.go, ui/package.json
=> feat: enable server UI by default

internal/cmd/error.go, internal/cmd/error_test.go, main.go
This pull request reverts changes made in https://github.com/infrahq/infra/pull/1936 and https://github.com/infrahq/infra/pull/2101 as they are not ready to be released
=> fix: revert commits related to error handling

ui/components/admin.js, ui/components/grant.js, ui/components/modals/delete.js, ui/pages/destinations/index.js, ui/pages/login/index.js, ui/pages/users/index.js
ui bugs that occurred during bug bash on May 26
Resolves #2074
Resolves #2107
Resolves #2109
=> fix: ui bugs

ui/pages/users/index.js
infra default role is no role so it should be displayed as `-` in the UI
Resolves #2141
=> fix: infra default role is no role

ui/components/auth-required.js, ui/components/layouts/dashboard.js, ui/components/layouts/fullscreen.js, ui/components/layouts/login.js, ui/pages/_app.js, ui/pages/login/index.js, ui/pages/signup/index.js
Fixes https://github.com/infrahq/infra/issues/2082
Also refactors ui auth code to be easier to reason about
=> fix: fix auth ui redirects for new otp users

README.md
Adding community links for discussion
=> Adding community links for discussion

ui/components/profile-icon.js, ui/components/sidebar.js, ui/pages/users/index.js
small improvement for profile icon component
=> fix: profile-icon component refactor

internal/cmd/error.go, internal/cmd/error_test.go, main.go
re-committing Error struct into main
Resolves #2113
=> improve: introduce cli errors

api/destination.go, internal/cmd/cmd_test.go, internal/cmd/kubernetes.go, internal/connector/connector.go, internal/server/handlers.go, internal/server/handlers_test.go, internal/server/models/destination.go, internal/server/models/model.go, internal/server/openapi.go, internal/server/routes.go
a simple solution to closing #1763
Resolves #1763
=> improve: strip whitespace of off incoming request string fields

ui/components/layouts/dashboard.js, ui/components/layouts/fullscreen.js
Props weren't being passed to `<Dashboard>` and `<Fullscreen>`
=> fix: ui props being passed when using authrequired

ui/components/admin.js, ui/components/resources-grant.js, ui/pages/destinations/index.js, ui/pages/providers/index.js, ui/pages/users/index.js
add default sorting to all the lists in the ui
Resolves #2117
=> Add default sorting to lists

ui/components/auth-required.js, ui/components/layouts/dashboard.js, ui/components/layouts/fullscreen.js, ui/pages/_app.js
Fixes https://github.com/infrahq/infra/issues/2178
=> fix: auth and signup redirects

internal/connector/connector.go
for clarity, name the connector sync function. first step in cleaning it up.
=> improve: name the connector sync function

helm/charts/infra/templates/connector/_helpers.tpl, helm/charts/infra/templates/connector/clusterrole.yaml, internal/kubernetes/kubernetes.go
Filter ClusterRoles based on labels
- kubernetes.io/bootstrapping=rbac-defaults
- app.infrahq.com/include-role=true
Resolves #90
=> feat: add more default cluster roles

ui/components/empty-table.js, ui/components/layouts/dashboard.js, ui/components/page-header.js, ui/components/sidebar.js, ui/components/table.js, ui/pages/destinations/index.js, ui/pages/providers/index.js, ui/pages/users/index.js
=> fix: ui scrolling

api/client.go, api/user.go, docs/api/openapi3.json, internal/access/identity.go, internal/access/identity_test.go, internal/cmd/cmd.go, internal/cmd/groups.go, internal/server/data/group_test.go, internal/server/data/identity.go, internal/server/data/identity_test.go, internal/server/handlers.go
=> feat: add list users in group api + groups list cli

api/destination.go, api/types.go, internal/cmd/cmd_test.go, internal/cmd/kubernetes.go, internal/cmd/kubernetes_test.go, internal/connector/connector.go, internal/server/handlers_test.go, internal/server/models/destination.go, internal/server/openapi.go, internal/server/routes.go, internal/server/routes_test.go
This is an example of the proposal described here: https://github.com/infrahq/infra/pull/2209#pullrequestreview-998683828
Needs more tests
=> fix: destination CA field encoding

api/user.go, docs/api/openapi3.json, internal/access/identity.go, internal/server/handlers_test.go, internal/server/models/identity.go
=> feat: users api should return names of providers user belongs to

ui/components/input.js, ui/components/resources-grant.js, ui/pages/destinations/add.js, ui/pages/login/index.js, ui/pages/providers/add/details.js, ui/styles/globals.css
- specify the input field type as `search` should prevent the one password prompts. 
Resolves #2112
=> fix: one password input field bug

docs/connectors/kubernetes.md
=> improve: update docs for custom kubernetes roles

helm/charts/infra/templates/connector/deployment.yaml
Fix values reference to connector for connector log level
Resolves #2079
=> fix(helm): s/server/connector/

internal/cmd/login.go, internal/cmd/login_test.go
This message caused some confusion. Removing it again.
=> fix: remove agent message

uid/snowid.go, uid/snowid_test.go
=> fix: normalize uids

website/components/Nav.js, website/pages/index.js
On initial load of `/docs` the Navigation button size would be animated causing a strange effect
=> fix(website): remove button animation causing flash

website/vercel.json
This enables public logs view for PRs to debug any build failures.
=> maintain(website): public build logs

ui/components/grant.js, ui/components/resources-grant.js
=> fix(ui): dont scroll grants view

helm/charts/infra/templates/NOTES.txt, helm/charts/infra/templates/server/configmap.yaml, helm/charts/infra/values.yaml
Add deprecation warning to `server.additonal[Secrets|Users|Grants|Providers]` and inform users to use `server.config.[secrets|users|grants|providers]` instead
Resolves #1854
=> maintain: remove additional* helm server values

docs/identity-providers/azure-ad.md
fix: active directory docs for creating client secrets
=> fix(docs): active directory docs

docs/reference/cli-reference.md, internal/cmd/providers.go
This command help was out of date, add kind to keep it up to date.
=> fix: update providers add example

api/client.go, api/group.go, docs/api/openapi3.json, internal/access/group.go, internal/cmd/errors.go, internal/cmd/groups.go, internal/cmd/keys.go, internal/server/data/group.go, internal/server/data/group_test.go, internal/server/groups_test.go, internal/server/handlers.go, internal/server/middleware_test.go, internal/server/routes.go
The change includes a new PATCH API call which allows users to be added and removed from groups. It also includes CLI changes to call the API.
Resolves #1913
=> Add rm users and groups

ui/components/layouts/dashboard.js, ui/components/sidebar.js, ui/pages/destinations/index.js, ui/pages/users/index.js
=> fix(ui): layout on smaller window sizes

ui/pages/destinations/add.js
=> fix(ui): add client-side validation for destination names

internal/access/access_test.go, internal/access/provider.go, internal/access/signup.go, internal/access/signup_test.go, internal/server/authn/authn_method_test.go, internal/server/authn/oidc_test.go, internal/server/authn/password_credentials_test.go, internal/server/config.go, internal/server/config_test.go, internal/server/data/data.go, internal/server/data/data_test.go, internal/server/data/migrations.go, internal/server/data/migrations_test.go, internal/server/data/provider_test.go, internal/server/data/provideruser_test.go, internal/server/data/selectors.go, internal/server/handlers.go, internal/server/handlers_test.go, internal/server/middleware_test.go, internal/server/models/provider.go, internal/server/models/provider_test.go, internal/server/providers/azure_test.go, internal/server/providers/oidc.go, internal/server/providers/oidc_test.go, internal/server/providers_test.go
=> maintain: provider lookups by kind

ui/components/layouts/dashboard.js, ui/components/table.js, ui/pages/destinations/[[...slug]].js, ui/pages/providers/[[...slug]].js, ui/pages/users/[[...slug]].js
Add links to specific resources in the UI
Fixes #2140 
Examples:
* `/destinations/<id>` to link to a cluster
* `/destinations/<id>/<resource>` to link to a namespace
* `/users/<id>` to link to a user
=> improve(ui): urls now include specific resource IDs

ui/pages/destinations/[[...slug]].js
Fixes issue where changing a role to itself will cause the role to be deleted
=> fix(ui): fix issue where editing role would clear access

ui/.eslintrc.json, ui/lib/grants.js, ui/pages/destinations/[[...slug]].js
Infra will now show which roles you have for a given destination
Fixes #2378
=> feat(ui): show which roles user has access to for a given destination

ui/components/layouts/dashboard.js, ui/components/table.js, ui/pages/destinations/index.js, ui/pages/providers/index.js, ui/pages/users/index.js
=> Revert "improve(ui): urls now include specific resource IDs"

internal/cmd/destinations.go, internal/cmd/providers.go, internal/cmd/providers_test.go, internal/cmd/users.go
=> improve: change json output

docs/configuration/working-with-groups.md, docs/reference/cli-reference.md, internal/cmd/groups.go
Unhide the groups command in the CLI
=> feat: unhide the groups command in the cli

ui/components/grant-form.js, ui/components/layouts/dashboard.js, ui/components/page-header.js, ui/components/sidebar.js, ui/components/table.js, ui/package.json, ui/pages/destinations/index.js, ui/pages/login/index.js, ui/pages/providers/add/details.js, ui/pages/providers/index.js, ui/pages/users/index.js
Fixes #2235, #2407 
Also fixes an issue where the user & group dropdown wouldn't update options after re-focusing
=> fix(ui): minor display issues in UI

docs/api/making-requests.md, internal/server/apimigrator.go, internal/server/apimigrator_test.go, internal/server/handlers_test.go, internal/server/openapi.go, internal/server/openapi_test.go, internal/server/testdata/openapi3.json
Brings back the required infra version header. Has already been reviewed and approved.
=> feat: require Infra-Version header (#2041)

.github/workflows/publish.yml, .github/workflows/release.yml
- fix versions being prefixed with `v`
- fix RELEASE_BUCKET vars, fix RELEASE_NAME vars
- fix docker image `latest` tag
add artifacts to github release
=> fix: build

.github/workflows/publish.yml
For some reason the Gemfury upload is failing. Continue on failure for now
=> maintain: continue on deb/rpm upload failure

ui/pages/groups/index.js, ui/pages/users/index.js
couple UI bugs are fixed on groups page
#1 
#3
#4
Resolves #2572
=> fix: bugs on groups page

internal/cmd/kubernetes.go, internal/cmd/kubernetes_test.go
- close temp file before rename to avoid err on windows
In the case of Window overwriting the Kube config using a temp file was not possible, as the temp file was still considered to be open. This was not see on Unix-based system. This could be due to how Windows handles changing file names.
This change fixes this issue by manually creating the temp file to write kube config to, and closing it before using it to overwrite the current Kube config.
Resolves #2586
=> fix: kube config overwrite temp file

ui/components/identity-list.js, ui/pages/groups/index.js, ui/pages/users/index.js
=> fix: fix the flashes when adding user to a group on sidebar

ui/pages/groups/index.js
As the previous conversation with @jmorganca, we decided to remove the column for now since this might need some API changes - might need to have a way to query it in the API. Because it is not efficient to calculate it on the frontend. 
Resolves #2606
=> fix: loading groups table

ui/__test__/components/delete-modal.test.js, ui/__test__/components/empty-table.test.js, ui/__test__/components/error-message.test.js, ui/__test__/components/metadata.test.js, ui/__test__/components/page-header.test.js, ui/components/delete-modal.js, ui/components/empty-table.js, ui/components/metadata.js, ui/components/page-header.js
unit testing for - `<DeleteModal />`, `<EmptyTable />`, `<ErrorMessage />`, `<PageHeader />`, `<Metadata />`
=> feat: adding more unit testings for components

api/access_key.go, api/destination.go, api/group.go, internal/server/config.go, internal/server/options_migrations.go, internal/server/server.go, internal/validate/validate.go, internal/validate/validate_test.go
Branched from #2611
With internal/validate
Also required adding slice traversal to internal/validate
Related to #2583
=> improve: replace server config validation

ui/pages/groups/index.js, ui/pages/settings/index.js, ui/pages/users/index.js
=> fix: sidebar and setting page flashes bug

ui/pages/signup/index.js
api removed the `email` field (https://github.com/infrahq/infra/pull/2645/files) - this PR modify the UI accordingly
=> fix: change field name

ui/components/pagination.js, ui/pages/destinations/index.js, ui/pages/groups/index.js, ui/pages/providers/index.js, ui/pages/users/index.js
Adds interactive pagination links to the UI and adds pagination to API requests (for each of the main pages).
=> feat(ui): pagination

ui/__test__/components/badge.test.js, ui/__test__/components/combobox-item.test.js, ui/__test__/components/notification.test.js, ui/__test__/components/profile-icon.test.js, ui/__test__/components/remove-button.test.js, ui/components/badge.js, ui/components/combobox-item.js, ui/components/notification.js, ui/components/remove-button.js
This PR covers unit testings for `<Notification />, <RemoveButton /> , <ProfileIcon />`
=> feat: more unit testings

ui/pages/destinations/index.js
=> fix: deleting cluster

ui/components/metadata.js, ui/pages/providers/index.js
fix the text is too long on the sidebar
Resolves #2674
=> Provider sidebar bug

internal/cmd/cmd.go, internal/cmd/cmd_test.go, internal/cmd/config.go, internal/cmd/logout.go, internal/cmd/logout_test.go
=> fix: fixes isLoggedIn check to include expiry

docs/api/making-requests.md
Docs update to go along with https://github.com/infrahq/infra/pull/2662
=> maintain(docs): add pagination to making-requests

.github/workflows/build.yml, .github/workflows/publish.yml
Instead of generating the index.yaml from scratch every time, use the previous index.yaml as the base to which it merges the new release into. Alternatively can use the `--url` parameter to automatically update the remote index but this feels like more control.
Releases with the same version will still be overwritten because local charts take precedence
Resolves #2734
=> fix: amend helm index.yaml instead of overriding

api/client.go, api/organization.go, internal/access/organization.go, internal/server/data/migrations.go, internal/server/data/organization.go, internal/server/models/identity.go, internal/server/models/organization.go, internal/server/organizations.go, internal/server/organizations_test.go, internal/server/routes.go, internal/server/testdata/openapi3.json
=> Initial Orgs Checkin

ui/__test__/components/pagination.test.js, ui/components/pagination.js
Adds pagination unit tests and fixes small bug with item range calculation.
Resolves #2732
=> maintain(ui): add pagination tests

ui/pages/providers/add/details.js
=> fix: clear error onChange

helm/charts/infra/templates/connector/prometheusrule.yaml, helm/charts/infra/templates/connector/servicemonitor.yaml, helm/charts/infra/templates/server/prometheusrule.yaml, helm/charts/infra/templates/server/servicemonitor.yaml, helm/charts/infra/values.yaml
Add some basic Prometheus alerting rules to monitor the health of deployed services
=> feat: add basic prometheus alerting rules

ui/pages/users/index.js
Adds providerNames to user metadata
Resolves #2678
=> feat(ui): add providers to user data

ui/pages/destinations/index.js, ui/pages/providers/index.js
=> fix: deleting provider doesn't update the table until refresh

internal/server/data/migrations.go, internal/server/data/migrations_test.go, internal/server/models/model.go
This adds the Organization ID field to the base model, adds a migration, and adds a unit test for migrating everything.
=> Add the Org ID

ui/pages/groups/index.js
=> feat: add the total users to group table

ui/components/badge.js, ui/pages/groups/add.js, ui/pages/groups/index.js, ui/pages/users/add.js
Resolves #2831 
Resolves #2833 
Resolves #2839
=> fix(ui): add groups / users bugs and badge ui bug

ui/components/typeahead-combobox.js, ui/pages/groups/index.js
=> fix(ui): bug where modal dialog would not close when removing a user from a group

ui/lib/admin.js, ui/pages/destinations/index.js, ui/pages/settings/index.js, ui/pages/users/index.js
=> fix(ui): use inherited grants instead of fetching groups

internal/cmd/groups_test.go, internal/cmd/testdata/TestGroupsListCmd/list_groups_default, internal/cmd/testdata/TestGroupsListCmd/no_truncate, internal/cmd/testdata/TestGroupsListCmd/num_users
Adds full test coverage to the `infra groups` command.
Resolves #2799
=> maintain: add groups cli tests

internal/server/handlers_test.go, internal/server/routes.go
Fixes a regression from #2815
Resolves #2865
=> fix: make infra header optional for well-known jwks

ui/pages/settings/index.js
=> fix(ui): fix issue where settings page would sometimes throw an error

ui/lib/admin.js
=> fix: reloading redirect issue

.github/workflows/ci-commit.yaml, .github/workflows/ci-core.yaml, .github/workflows/ci-helm.yaml, .github/workflows/ci-ui.yaml, .github/workflows/ci-website.yaml, .github/workflows/ci.yaml
update CI to only build when necessary
=> improve: separate ci workflows

ui/components/role-select.js, ui/lib/grants.js
=> fix: sort custom role

internal/cmd/grants.go
=> improve: better error message when user tries to delete last admin grant

api/client.go, internal/access/signup.go, internal/access/signup_test.go, internal/server/cookie.go, internal/server/data/migrations.go, internal/server/data/migrations_test.go, internal/server/data/schema.sql, internal/server/handlers.go, internal/server/models/organization.go, ui/__test__/signup.test.js, ui/pages/_app.js, ui/pages/index.js, ui/pages/signup/index.js
No changes from #2841, just re-opening to fix the actions which were stuck.
Resolves #2822
=> feat: sign-up for orgs

internal/cmd/about.go
=> improve: super important update to contributor log

api/configuration.go, internal/server/configuration.go, internal/server/routes.go, internal/server/testdata/openapi3.json, ui/lib/serverconfig.js, ui/pages/login/index.js
expose server configuration to the frontend so it can make intelligent UI choices. 
Resolves #2818
=> feat: endpoint to check server configuration

docker-compose.dev.yaml, internal/access/signup.go, internal/cmd/server.go, internal/cmd/server_test.go, internal/server/handlers.go, internal/server/middleware_test.go, internal/server/models/organization.go, internal/server/organizations.go, internal/server/server.go, ui/pages/signup/index.js
=> fix: signup redirect should expect full domain

ui/pages/login/callback.js
=> fix: login page rendering on sso login

docs/dev/organization-request-flow.md
=> fix: org flow docs update from discussions

ui/pages/login/callback.js
Fixes https://github.com/infrahq/infra/issues/2943 in all cases – this was happening due to React 18 + Next.js's multiple renders and mount/unmounts.
=> fix: dont re-render login page on sso login

internal/server/metrics.go
Add prometheus metrics to monitor number of organizations
=> feat: add orgs prom metrics

.github/workflows/cd-core.yaml, .goreleaser.yml, docs/getting-started/quickstart.md, docs/install/install-infra-cli.md, docs/install/upgrade.md, docs/partials/cli-install.md
- remove unused goreleaser configurations
- remove artifact upload to gemfury, s3; artifacts will be downloaded directly from github releases
=> maintain: simplify build and install processes by removing unnecessary steps

CONTRIBUTING.md
Update the contributing doc to demonstrate setting up a multi-tenant Infra server.
=> maintain: update contributing doc

internal/server/middleware_test.go
=> fix: overlapping prs caused a build failure

ui/pages/signup/index.js
The organization name placeholder is isconsistent with other fields in the signup UI
=> maintain: reword org name placeholder

internal/server/data/migrations.go, internal/server/data/migrations_test.go, internal/server/data/schema.sql, internal/server/data/schema/parse.go, internal/server/data/sqlfunc.go, internal/server/data/sqlfunc_test.go, uid/snowid.go
=> feat: add sql functions uidStrToInt and uidIntToStr

internal/server/data/migrations_test.go, internal/server/data/sqlfunc.go
=> fix: fixes issue caused by bad merge

internal/server/data/provider_test.go
These tests were added to protect against a reported bug where users not linked to a provider had their sessions revoked when the provider was deleted. The reported issue could not be reproduced.
Resolves #3010
=> maintain: validate that provider user sessions are revoked on provider delete

internal/server/data/migrations.go, internal/server/data/migrations_test.go
I missed updating all the foreign keys, like I had done previously.
Added test coverage for the bug as well.
=> fix: migration for orgID

helm/charts/infra/Chart.yaml, helm/charts/infra/README.md, helm/charts/infra/templates/NOTES.txt
Add helm readme and upgrade instructions from <0.20.0.
=> feat(helm): bump infra helm chart to 0.20.0

docs/install/upgrade.md
Point server and connector upgrade to Helm README.md
=> maintain: update Helm upgrade docs

internal/server/email/smtp.go
=> fix: remove smtp testClient

ui/pages/groups/index.js
=> fix: fix the groups page browser title

README.md, docs/install/install-on-kubernetes.md
Signed-off-by: Matthew Williams <m@technovangelist.com>
Doh! I updated the Readme and the Kubernetes doc to create a values yaml file, and updated the command to use upgrade --install...but forgot to add the values option to load the file we created.
Resolves #
=> maintain: forgot to add the values file to the cmd

internal/server/data/access_key_test.go
=> improve: fix typo

helm/charts/infra/Chart.yaml
=> feat(helm): bump helm version to 0.20.1

.github/workflows/ci-core.yaml, internal/tools/querylinter/go.mod, internal/tools/querylinter/go.sum
=> Updated go linter to v1.49.0

api/redirect.go, internal/access/passwordreset.go, internal/access/passwordreset_test.go, internal/access/verification.go, internal/server/data/identity.go, internal/server/data/identity_test.go, internal/server/data/migrations.go, internal/server/data/migrations_test.go, internal/server/data/organization_test.go, internal/server/data/schema.sql, internal/server/email/forgotdomain.go, internal/server/email/passwordreset.go, internal/server/email/signup.go, internal/server/email/smtp_test.go, internal/server/email/templates/signup.text.html, internal/server/email/templates/signup.text.plain, internal/server/email/userinvite.go, internal/server/forgotdomain.go, internal/server/handlers.go, internal/server/models/identity.go, internal/server/models/model.go, internal/server/passwordreset.go, internal/server/passwordreset_test.go, internal/server/redirect.go, internal/server/redirect_test.go, internal/server/routes.go, internal/server/users.go
- adds email verification tokens to identity
- wraps common email links with a verification check and redirect
- adds supports for server handlers that redirect instead of rendering responses.
=> feat: transparent email verification

internal/server/email/forgotdomain.go, internal/server/email/passwordreset.go, internal/server/email/sendgrid.go, internal/server/email/signup.go, internal/server/email/smtp.go, internal/server/email/smtp_test.go, internal/server/email/userinvite.go
=> fix: transactional emails should skip marketing list unsubscribes

internal/kubernetes/kubernetes.go
Reduce the log level of using an internal node address to debug
=> maintain: reduce internal node address log noise

ui/pages/groups/index.js, ui/pages/providers/add.js, ui/pages/users/index.js
=> fix: rename texts and add modal

internal/server/grants_test.go, internal/server/handlers_test.go
Add a test case for each endpoint that tries to use an admin for the wrong organization.
=> Add some multi-org cases for the grants API endpoints

helm/charts/infra/Chart.yaml
This bumps appVersion to 0.15.2.
=> maintain: bump helm chart to 0.20.4

internal/server/email/sendgrid.go, internal/validate/email.go, internal/validate/email_test.go
should probably avoid explicitly wrong emails and give better messages about it.
closes #3291
=> fix: better errors on bad email

ui/pages/groups/[id].js
adding metadata section on group
=> feat: add metadata section

ui/components/role-select.js, ui/lib/grants.js
- fixing subject and privilege sorting 
- adding new sorting for role select
=> fix: sorting bugs

.golangci.yml, internal/server/providers_test.go
=> improve: fix lint (xxxs)

api/access_key.go, api/client.go, api/client_test.go, internal/access/access_key.go, internal/access/access_key_test.go, internal/access/identity_test.go, internal/cmd/keys.go, internal/server/access_keys.go, internal/server/access_keys_test.go, internal/server/config.go, internal/server/data/access_key.go, internal/server/data/access_key_test.go, internal/server/data/provider_test.go, internal/server/models/access_key.go, internal/server/providers_test.go, internal/server/routes.go, internal/server/signup_test.go, internal/server/testdata/openapi3.json
=> fix: allow users to delete their own access keys from cli

ui/components/grant-form.js, ui/pages/login/index.js, ui/pages/settings/index.js, ui/pages/users/index.js
- fix the default select for role select component
- fix the login with button's text overflow
- hide revoke when there is only one admin on the list on admin setting page
- sort user on the users table to make sure the self is always on the top of the list
=> fix: minor ui bugs

ui/components/table.js, ui/pages/destinations/index.js, ui/pages/groups/index.js, ui/pages/providers/[id].js, ui/pages/providers/index.js, ui/pages/users/index.js
couple improvement on the tables
- made the interaction more consistent (other than the users page - since we need more time to design and implement the user detail page)
- modified the provider edit page
- modified the width of the columns so that the first column of the table has same length throughout the app
- removed `added` columns from all the tables because it is not a very useful information for users
https://user-images.githubusercontent.com/63033505/193854442-ef0acc38-a05b-4a22-a140-461350093154.mov
=> improve: table revisit

ui/components/grant-form.js, ui/pages/account/index.js, ui/pages/destinations/index.js, ui/pages/groups/[id].js, ui/pages/groups/index.js, ui/pages/providers/[id].js, ui/pages/providers/add.js, ui/pages/providers/index.js, ui/pages/users/index.js
- make sure the hover state and disabled state have consistent UI throughout the app
=> improve: buttons behaviour and colours

internal/access/destination.go, internal/cmd/connector_test.go, internal/server/data/destination.go, internal/server/data/destination_test.go, internal/server/data/selectors.go, internal/server/middleware.go, internal/server/middleware_test.go
Update the queries for GetDestination and ListDestination to use SQL, and add a few more test cases.
=> Use SQL for GetDestination and ListDestination

ui/components/layouts/dashboard.js, ui/components/notification.js, ui/lib/hooks.js, ui/pages/account/index.js, ui/pages/destinations/[id]/index.js, ui/pages/groups/[id].js, ui/pages/providers/[id].js
- improve notification component to clear the timeout when unmount and cancel the timer when click away
- add org name to the profile dropdown menu
=> improve: org name and notification

api/client.go, api/client_test.go, api/grant.go, api/types.go, internal/access/grant.go, internal/access/request.go, internal/server/data/data.go, internal/server/data/grant_test.go, internal/server/grants.go, internal/server/grants_test.go, internal/server/routes.go, internal/server/testdata/openapi3.json, internal/validate/email.go, internal/validate/numbers.go, internal/validate/string.go, internal/validate/validate.go
Branched from #3400
This PR adds the API support for long polling of list grants requests. Best viewed by individual commit.
=> Add API handler support for ListGrants blocking request

api/scim.go, internal/access/scim.go, internal/server/data/access_key.go, internal/server/data/data.go, internal/server/data/destination.go, internal/server/data/encryption_key.go, internal/server/data/grant.go, internal/server/data/group.go, internal/server/data/identity.go, internal/server/data/provideruser.go, internal/server/data/provideruser_test.go, internal/server/routes.go, internal/server/scim.go, internal/server/scim_test.go
This change includes endpoints to create, update, get, patch and delete users from an identity provider using SCIM.
Resolves #3378
=> feat: users scim

internal/server/debug.go
And close the transaction before blocking to prevent long running transactions.
=> Make pprof endpoint a blocking request

internal/server/data/deviceflowauthrequest.go, ui/components/layouts/dashboard-no-sidebar.js, ui/pages/device/index.js
=> improve: change device flow input and layout to separate boxes with no sidebar

ui/components/grant-form.js, ui/pages/destinations/[id]/index.js
- allow namespaces to have `cluter-admin` role
- fix check icon styling on select roles
=> fix: namespaces access with small tweak

ui/components/update-password.js, ui/pages/login/index.js
- update password requires old password
- make password update a component to pass old password from login
After a user logged in with a one time password, they could not update their password. This was due to the "update user" endpoint requiring the old password.
=> fix: update password after one-time password

metrics/metrics.go
The timing for a request is not emitted until after the request ends, so when requests are slow or there are many blocking requests we don't have a good picture of the current request load. This new gauge metric tells us how many requests are being handled.
I tested this manually with some blocking requests. I think an automated test for this might be possible, but we don't have a pattern for testing metrics yet.
=> Add a gauge metric for active requests

internal/access/identity.go, internal/access/provider.go, internal/access/scim.go, internal/server/authn/oidc.go, internal/server/authn/oidc_test.go, internal/server/config.go, internal/server/data/access_key.go, internal/server/data/data.go, internal/server/data/identity.go, internal/server/data/provider.go, internal/server/data/provider_test.go, internal/server/data/selectors.go, internal/server/data/tables_test.go, internal/server/middleware.go, internal/server/providers.go, internal/server/providers_test.go
This PR converts the provider data functions to SQL, and adds more test coverage of each function. 
=> Convert provider queries to use sql

ui/pages/destinations/[id]/index.js
- since selecting all namespaces may take up a lot of space when there are many namespaces, will only show the first 5 namespaces 
- add bulk remove access to remove namespaces access  
https://user-images.githubusercontent.com/63033505/199264325-0057915f-5e6b-4b05-820c-4ab6983eebaa.mov
=> maintain: cluster namespace improvements

internal/server/server.go, internal/server/server_test.go
Fixes #3161
This problem is most obvious when a new client is making requests to an old server that does not yet have the new API path. Previously the response would be an HTML page from the UI. With this fix it should be a JSON API error response, which is much easier to debug.
The test for this was updated to enable the UI proxy, so that the test covers the same scenario as production. I had to also switch from `httptest.ResponseRecorder` to `httptest.Server`, because the response recorder does not work with the proxy (it would panic).
I found https://stackoverflow.com/questions/36357791/gin-router-path-segment-conflicts-with-existing-wildcard, which confirms this is a difficult problem to solve. One of the options there is to use a middleware (which is actually our problem), but it …
=> Fix response body for unknown paths

api/client.go
Update the API version to 0.16.2
=> maintain: update api version

helm/charts/infra/templates/connector/deployment.yaml, helm/charts/infra/templates/connector/service.yaml, helm/charts/infra/values.yaml
Split from https://github.com/infrahq/infra/pull/3563 to avoid out-of-sync deployment issues. Should be merged after #3563 has been merged and released
=> fix(helm): http connector service

.github/workflows/ci-core.yaml, internal/connector/connector.go, internal/server/destination_test.go
This PR includes 3 one line fixes (one per commit). Details in the commit messages
=> Fix CI flake and log message

ui/components/delete-modal.js, ui/components/grant-form.js, ui/components/layouts/dashboard.js, ui/components/notification.js, ui/components/role-select.js, ui/components/scim-key.js, ui/package-lock.json, ui/package.json, ui/pages/destinations/[id]/index.js, ui/pages/destinations/add.js, ui/pages/forgot-domain/index.js, ui/pages/groups/[id].js, ui/pages/login/organizations.js, ui/pages/password-reset/index.js, ui/pages/providers/add.js, ui/pages/users/index.js
update @heroicons from 1.0.6 to 2.0.13
=> maintain: update icon library

ui/components/scim-key.js, ui/pages/settings/index.js, ui/pages/settings/providers/add.js
- check image is not loading and has console error
- tab looks odd
=> fix: setting page ui bug on prod

ui/pages/destinations/[id]/index.js
=> improve: destination namespace bulk remove

ui/next.config.js
=> fix: csp issue that lead to checkbox check image cannot load

docs/manage/idp/okta.md
=> maintain: add instructions for scim on Okta

ui/pages/destinations/add.js
not a true representation of leap year but accurate enough for our purposes
=> improve: approx. leap year for connector access keys

api/grant.go, docs/api/openapi3.json
Updates grants api in openapi.json
Resolves #
=> fix: document the Grants API so that it is right in the openapi.json doc

helm/charts/infra/Chart.yaml
update helm for 0.18.0 release
=> update helm for 0.18.0 release

api/access_key.go, api/grant.go, api/group.go, api/provider.go, api/user.go, docs/api/openapi3.json
Important for the 1st version of the docs
This pr rounds out all the GET endpoints needed for the first version of the api docs.
Resolves #
=> fix: documentation for all the get endpoints

internal/server/backgroundjobs.go, internal/server/backgroundjobs_test.go
Branched from #3643
I made some changes to this code in #3643, so adding these tests to show that I didn't break anything
=> Add test coverage for background job wrapper

README.md
update readme with 'infra list'
=> update readme with 'infra list' 

internal/claims/claims.go, internal/server/data/token.go
Fixes https://github.com/infrahq/infra/issues/2014
=> Remove unused JWT nonce field

internal/server/config.go
machine configuration has been deprecated since v0.13.0 so it's probably safe to delete.
=> maintain: remove deprecated machine grant subject

internal/server/data/migrations.go
The other query was not working for me. It was failing here: 
> internal/server/data TestMigrations/2022-11-22T14:00/run_again_to_check_idempotency (0.02s
> migrations_test.go:95: assertion failed: error is not nil: rename access key extension deadline: ERROR: column "extension" does not exist (SQLSTATE 42703)
I believe this fails for us locally because our database has multiple schemas. The previous query didn't include `table_schema`, so it would make schemas that were not the one being tested. That's why it passes in CI (because there is only 1 schema).
`migrator.HasColumn` uses `table_schema = CURRENT_SCHEMA()`.
=> Use migrator helper to check for columns

internal/kubernetes/kubernetes.go
Fix connector endpoint query to always return the HTTPS port number which it was previously only returning when the service type was _not_ NodePort.
Resolves #3731
=> fix(connector): return endpoint https port

internal/server/providers/azure.go, internal/server/providers/azure_test.go
While troubleshooting #3751 I noticed errors from the Azure API during group sync are being suppressed. This change updates the response checking to log any errors from Azure API responses in the server logs.
Resolves #3751
=> fix: log azure error details

internal/cmd/cmd.go, internal/cmd/ssh.go, internal/cmd/ssh_test.go
Fix the failing build due to conflicts after last night's merge.
=> fix: build conflicts

go.mod, go.sum, internal/cmd/connector_test.go, internal/connector/connector.go, internal/kubernetes/kubernetes.go
=> Revert "Use standard kubernetes loading instead of custom options in the connector"

internal/access/access_key.go, internal/access/access_key_test.go
Sessions authenticated with access keys are blocked from creating additional access keys to prevent self-renewal. 
This change removes this restriction for an admin access key to create connector access keys.
Resolves #3725
=> feat: allow access keys to create connector access keys

internal/access/grant.go, internal/server/grants_test.go
Fixes https://github.com/infrahq/internal/issues/34
=> Fix UpdateGrants

internal/cmd/grants.go
=> fix issue with "unknown user" message

.github/workflows/cd-containers.yaml
If all attempts to sync the image fails, the job should fail.
=> fix: exit 1 if all attempts fail

.goreleaser.yml, package-files/connector.example.yaml, package-files/postinstall.sh, package-files/preinstall.sh, package-files/preremove.sh, package-files/systemd/infra.service
- Update Linux packages to include systemd service
- Add archlinux package
=> os packages

ui/components/table.js, ui/pages/destinations/index.js
- add ssh to destinations table
https://user-images.githubusercontent.com/63033505/208481803-69257409-c06c-45b2-a7d8-8953efa821aa.mov
=> feat: add ssh to destinations table

.github/workflows/cd-containers.yaml
=> fix: update build version for container images

ui/pages/destinations/index.js
=> fix: show ssh url when it is available

.github/workflows/ci-core.yaml, test/dockerfiles/install-debian.sh, test/dockerfiles/install-redhat.sh
Docs PR: https://github.com/infrahq/website/pull/15
Also updates `ci-core` config to run when any files under `test/` are changed.
=> Update acceptance test to use the same instructions as the docs

ui/next.config.js
Add a few more CSP directives to improve security posture.
=> improve: add more csp directives

ui/components/scim-key.js, ui/pages/settings/providers/[id].js
Fix providers settings links missed in https://github.com/infrahq/infra/pull/3988
=> fix: settings providers link

ui/pages/destinations/index.js
=> fix: ssh delete modal

ui/next.config.js, ui/pages/login/callback.js
The problem seems like to be the redirect in callback component. After the login is done, it redirects to `/` which it is calling the Index component. In the Index component it checks the router and redirects the path to `/destinations` 
The fixes for this are:
1) to redirect to `/destinations` directly instead of `/`. 
2) added redirect in the `next.config.js` to make sure the `/` is always redirect to `/destinations` without going through Index component
Resolves #3985
=> fix: ui first login flashes

ui/lib/hooks.js, ui/next.config.js, ui/pages/_app.js, ui/pages/login/callback.js, ui/pages/login/index.js
This PR properly clears the cache when logging a user in or out.
=> Reset local user cache after login and logout

.golangci.yml, internal/cmd/kubernetes.go, internal/cmd/kubernetes_test.go, internal/connector/authn.go, internal/connector/connector_test.go, internal/kubernetes/kubernetes.go, internal/server/access_keys.go, internal/server/data/migrations_test.go, internal/server/metrics_test.go, internal/server/openapi_test.go, internal/server/providers/azure.go, internal/server/providers/oidc_test.go, internal/server/server_test.go
Fix and remove excluded linting rules
=> fix: linting errors unseen by exclusion rules

ui/components/delete-modal.js, ui/components/grant-form.js, ui/components/table.js, ui/pages/access-control/index.js, ui/pages/groups/[id].js, ui/pages/settings/index.js, ui/pages/users/index.js
- review and refactor how we handle groups user table after sending the request to server side
- add multi select on groups users table
- small improvement on access control and table components
=> fix: groups page improvement

internal/server/data/identity.go
In #4039 I need all the IDs of the groups so that we can use these IDs to send `pg_notify` notifications about changes to group membership, and to set the `update_index` of these groups.
This PR extracts a function to return a mapping of group name->ID, and uses that mapping to replace the sub-select in the "remove groups" operation, and the "does group exist" lookup in the "add groups" operation.
Extracted from #4039
=> Refactor AssignIdentityToGroups to use IDs

README.md
=> Remove social links from readme

ui/pages/destinations/[id]/index.js, ui/pages/destinations/index.js, ui/pages/groups/[id].js, ui/pages/groups/index.js, ui/pages/settings/index.js, ui/pages/settings/providers/[id].js, ui/pages/users/index.js
fix the inconsistency of
- button text
- modal title
- remove button behaviour and position on table
Resolves #3914
Resolves #4073
=> fix: Inconsistent UI

ui/components/table.js, ui/pages/access-control/index.js, ui/pages/destinations/index.js
- gave a fixed height for access control table 
- introduced min width for cell on access control table
- removed `roles` preselection on grant access modal 
- fixed router bug on `?p=0`
- fixed access control new grants behaviour 
Resolves #4074
=> fix: minor ui improvements

ui/pages/users/index.js
- rename `remove infra user` to `remove`
Resolves #4078
=> fix: rename remove user button
